<?php /** The thread (screen `thread-view`): the first message and its replies; the reply composer. Data: c, rootId, rows, running, may, me, pane (bool: the right pane), here, tz */
$cid = (int) $c['channel_id']; $lastId = $rows === [] ? 0 : (int) $rows[count($rows) - 1]['message_id']; $back = channel_path($c); ?>
<?php if (!$pane): ?><?= view('shared/header.php', ['id' => 'thread-view', 'title' => 'Thread', 'crumbs' => [['Home', '/'], [in_array($c['kind'], ['dm', 'group_dm'], true) ? 'Direct messages' : 'Channels', in_array($c['kind'], ['dm', 'group_dm'], true) ? '/dm/' : '/channels/'], [$c['label'], $back], ['Thread', null]], 'back' => back_link() ?? [$back, $c['label']]]) ?><div class="main-content"><?php endif; ?>
<div class="sp-thread<?= $pane ? ' sp-thread-pane' : ' card' ?>" id="thread-pane" data-channel="<?= $cid ?>" data-root="<?= (int) $rootId ?>" data-last="<?= $lastId ?>" data-since="/channels/<?= $cid ?>/threads/<?= (int) $rootId ?>/since" data-hashes="<?= e(json_encode(row_hashes($rows))) ?>">
    <?php if ($pane): ?><div class="fs-12 text-muted mb-2"><?= hx_link($back . '#message-row-' . (int) $rootId, 'In ' . e($c['label']), '', 'id="thread-pane-channel-link"') ?> · <a href="/channels/<?= $cid ?>/threads/<?= (int) $rootId ?>" id="thread-pane-open-page">open as a page</a></div><?php endif; ?>
    <div class="sp-messages sp-thread-messages<?= $pane ? '' : ' p-2' ?>" id="thread-messages" hx-get="/channels/<?= $cid ?>/threads/<?= (int) $rootId ?>/since" hx-trigger="every 3s [document.visibilityState=='visible'], every 20s" hx-vals="js:{after: SPChannel.threadAfter(), hashes: SPChannel.threadHashes()}" hx-target="this" hx-swap="beforeend" hx-sync="this:drop">
        <?php foreach ($rows as $i => $m): ?><?= view('channels/partials/message-row.php', ['m' => $m, 'c' => $c, 'me' => $me, 'tz' => $tz, 'inThread' => true, 'may' => $may, 'oob' => false]) ?><?php if ($i === 0): ?><div class="sp-thread-replies-label fs-11 text-muted px-2" id="thread-replies-label"><?= (int) $m['reply_count'] ?> repl<?= (int) $m['reply_count'] === 1 ? 'y' : 'ies' ?></div><?php endif; ?><?php endforeach; ?>
    </div>
    <div class="sp-thinking fs-12 text-muted px-2 py-1<?= $running === [] ? ' d-none' : '' ?>" id="thread-thinking"><?= $running === [] ? '' : e($running[0]['agent_name']) . ' is thinking…' ?></div>
    <div class="sp-composer-wrap<?= $pane ? '' : ' p-2' ?>" id="thread-composer-wrap"><?= view('channels/partials/composer.php', ['c' => $c, 'action' => 'reply', 'rootId' => $rootId, 'may' => $may, 'compact' => true]) ?></div>
</div>
<?php if (!$pane): ?></div><link rel="stylesheet" href="/assets/css/channel.css"><script src="/assets/js/richtext.js"></script><script src="/assets/js/channel.js"></script><?php endif; ?>
