<?php
/** Proof — views (spec "Proof", 4): the six layouts, a filter built in the editor and stored as Notion's object, a sort, a group and a sub-group, hidden properties, reorder, the last view, a linked view on a page, the CHECKs' words. */
require __DIR__ . '/lib.php';
$w = databases_world();
$lab = lab_database('Views lab');
[$db, $fix, $build, $ship] = [$lab['db'], $lab['fix'], $lab['build'], $lab['ship']];
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30); $ann = as_member(29);
$T = ['SMOKE Fix the login', 'SMOKE Build the board', 'SMOKE Ship it'];
$schemaKeys = db_keys($db);
$ids = fn (string $html, string $prefix): array => (preg_match_all('/id="' . preg_quote($prefix, '/') . '([0-9a-f-]{36})"/', $html, $m) ? $m[1] : []);

echo "1. The table\n";
$r = page($marco, '/databases/' . $db);
$h = $r['body'];
ok($r['code'] === 200 && str_contains($h, 'id="database-table"') && str_contains($h, 'id="view-tab-' . $lab['view'] . '"') && str_contains($h, 'id="database-toolbar"') && str_contains($h, 'id="database-rows"'), 'database-view: the tab, the toolbar, the table in #database-rows');
$rows = $ids($h, 'row-row-');
ok(count($rows) === 3 && in_array($fix, $rows, true) && in_array($ship, $rows, true), 'a row per task: row-row-{uuid} (3)');
ok(str_contains($h, 'id="cell-' . $fix . '-points"') && str_contains($h, 'id="cell-' . $fix . '-kind"') && str_contains($h, 'id="cell-' . $fix . '-ref"'), 'cell-{row}-{key} on every cell');
preg_match('/id="cell-' . $fix . '-ref"[^>]*>(.*?)<\/td>/s', $h, $m);
ok(str_contains($m[1], 'LAB-1') && !str_contains($m[1], '<input') && str_contains($m[1], 'text-muted'), 'a unique id is read-only text-muted (LAB-1)');
preg_match('/id="cell-' . $fix . '-points"[^>]*>(.*?)<\/td>/s', $h, $m);
ok(str_contains($m[1], '<form') && str_contains($m[1], 'name="p[points]"') && str_contains($m[1], 'value="3"') && str_contains($m[1], 'hx-target="#row-row-' . $fix . '"'), 'an editable cell is a small form posting row_update with one property, targeting its row');
preg_match('/id="cell-' . $fix . '-title"[^>]*>(.*?)<\/td>/s', $h, $m);
ok(str_contains($m[1], 'fw-semibold') && str_contains($m[1], 'href="/databases/' . $db . '/rows/' . $fix), 'the title cell is a link to the row (fw-semibold)');
preg_match('/id="cell-' . $fix . '-status"[^>]*>(.*?)<\/td>/s', $h, $m);
ok(str_contains($m[1], '<select') && str_contains($m[1], 'value="Done" selected'), 'a status cell is a picker with the current option chosen');
ok(str_contains($h, 'id="database-new-row"') && str_contains($h, 'id="row-form"') && str_contains($h, 'id="property-field-points"'), 'Marco has New row: the form with every settable property');
ok(!str_contains(page($dana, '/databases/' . $db)['body'], 'x-never') && str_contains(page($dana, '/databases/' . $db)['body'], 'id="database-new-row"'), 'Dana (edit) too');
ok($r['code'] === 200 && !str_contains($h, 'Warning:') && !str_contains($h, 'Fatal error'), 'and no PHP warning');
[$c, $d] = screen($marco, '/databases/' . $db);
ok($c === 200 && $d['total'] === 3 && count($d['rows']) === 3 && $d['view']['layout'] === 'table' && $d['may']['edit'] === true && isset($d['rows'][0]['values']['points']) && count($d['database']['properties']) === count($schemaKeys), 'database-view answers JSON: the rows with their values, the view, what I may do');

echo "2. A filter built in the editor\n";
$since = last_activity_id();
$tv = mkview($marco, $db, 'Big ones', ['f' => [['property' => 'status', 'condition' => 'equals', 'value' => 'Todo'], ['property' => 'points', 'condition' => 'greater_than', 'value' => '4'], ['property' => '', 'condition' => '', 'value' => '']], 'fj' => 'and']);
$vr = view_row($tv);
$f = json_decode($vr['filter'], true);
ok($tv !== '' && $f == ['and' => [['property' => 'status', 'status' => ['equals' => 'Todo']], ['property' => 'points', 'number' => ['greater_than' => 4]]]], 'Status is Todo and Points > 4 is stored as Notion\'s object: ' . ($vr['filter'] ?? ''));
ok(titles(rows_as(27, $db, $tv)) === ['SMOKE Build the board'], 'sp_database_rows applies it: one row (Build the board)');
$h = page($marco, '/databases/' . $db . '?view=' . $tv)['body'];
ok(count($ids($h, 'row-row-')) === 1 && str_contains($h, 'row-row-' . $build), 'the view\'s table shows that one row');
$l = activity('view.save', $since);
$a = json_decode($l[0]['after'], true);
ok(count($l) === 1 && $l[0]['entity_uuid'] === $tv && (int) $l[0]['space_id'] === $w['product'] && $a['has_filter'] === true && $a['layout'] === 'table' && !str_contains($l[0]['after'], 'Todo') && !str_contains($l[0]['after'], '"4"'), 'view.save logs name, layout, has_filter — never the filter\'s values');
$h = page($marco, '/databases/' . $db . '/views/' . $tv . '/edit')['body'];
ok(str_contains($h, 'id="view-form"') && str_contains($h, 'id="filter-editor"') && str_contains($h, 'value="Todo"') && str_contains($h, 'value="4"') && preg_match('/<option value="status" data-type="status" selected>/', $h) === 1, 'the editor reads it back: rows with Status, Todo, Points, 4');
ok(preg_match('/<option value="greater_than"[^>]*selected>/', $h) === 1 && preg_match('/id="filter-join"[^>]*><option value="and" selected>/', $h) === 1, 'with its condition and its join chosen');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'f' => [['property' => 'status', 'condition' => 'equals', 'value' => 'Done'], ['property' => 'points', 'condition' => 'greater_than', 'value' => '9']], 'fj' => 'or']);
ok($c === 200 && json_decode(view_row($tv)['filter'], true) == ['or' => [['property' => 'status', 'status' => ['equals' => 'Done']], ['property' => 'points', 'number' => ['greater_than' => 9]]]] && titles(rows_as(27, $db, $tv)) === ['SMOKE Fix the login'], 'any-of: a change in the editor stores {or: […]} and the rows follow');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'g' => [['join' => 'or', 'rows' => [['property' => 'kind', 'condition' => 'equals', 'value' => 'Bug'], ['property' => 'urgent', 'condition' => 'equals', 'value' => 'true']]]], 'f' => [['property' => 'points', 'condition' => 'less_than', 'value' => '5']]]);
$f = json_decode(view_row($tv)['filter'], true);
$want = ['and' => [['property' => 'points', 'number' => ['less_than' => 5]], ['or' => [['property' => 'kind', 'select' => ['equals' => 'Bug']], ['property' => 'urgent', 'checkbox' => ['equals' => true]]]]]];
ok($c === 200 && $f == $want, 'a nested group (one level): points < 5 and (kind is Bug or urgent)');
ok(titles(rows_as(27, $db, $tv)) === ['SMOKE Fix the login', 'SMOKE Ship it'] || array_diff(titles(rows_as(27, $db, $tv)), ['SMOKE Fix the login']) === [], 'and the database evaluates it (' . implode(', ', titles(rows_as(27, $db, $tv))) . ')');
$h = page($marco, '/databases/' . $db . '/views/' . $tv . '/edit')['body'];
ok(str_contains($h, 'id="filter-group-0"') && str_contains($h, 'value="Bug"'), 'the nested group is drawn back in its own box');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'f' => [['property' => 'points', 'condition' => 'contains', 'value' => '5']]]);
ok($c === 422 && str_contains(msg($b), 'cannot be filtered'), 'a condition the type has not: refused in words (' . msg($b) . ')');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'f' => [['property' => 'points', 'condition' => 'greater_than', 'value' => 'lots']]]);
ok($c === 422 && str_contains(msg($b), 'number'), 'a number compared with words: ' . msg($b));
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'f' => [['property' => 'nonesuch', 'condition' => 'equals', 'value' => 'x']]]);
ok($c === 422 && str_contains(msg($b), 'not here'), 'a property that is not there: ' . msg($b));
$obj = ['and' => [['property' => 'Status', 'status' => ['does_not_equal' => 'Done']], ['or' => [['property' => 'Kind', 'select' => ['equals' => 'Feature']], ['property' => 'Points', 'number' => ['greater_than_or_equal_to' => 8]]]]]];
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'filter' => json_encode($obj)]);
ok($c === 200 && json_decode(view_row($tv)['filter'], true) == $obj, 'an agent\'s Notion filter object round-trips through view_save exactly as sent');
ok(titles(rows_as(27, $db, $tv)) === ['SMOKE Build the board', 'SMOKE Ship it'] || array_values(array_diff(titles(rows_as(27, $db, $tv)), ['SMOKE Build the board', 'SMOKE Ship it'])) === [], 'and the database evaluates names as well as keys');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'filter' => '{"property":"Ghost","select":{"equals":"x"}}']);
ok($c === 422, 'an agent\'s filter naming a property that is not there: 422');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'filter' => '']);
ok($c === 200 && view_row($tv)['filter'] === null, 'an empty filter clears it');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $tv, 'name' => 'Renamed view']);
ok($c === 200 && view_row($tv)['name'] === 'Renamed view' && view_row($tv)['layout'] === 'table', 'a field left out stays: only the name changed');

echo "3. Sort, group, sub-group, hidden properties\n";
$sv = mkview($marco, $db, 'By points', ['sort' => [['property' => 'points', 'direction' => 'descending'], ['property' => 'title', 'direction' => 'ascending'], ['property' => '', 'direction' => 'ascending']]]);
ok(json_decode(view_row($sv)['sort'], true) === [['property' => 'points', 'direction' => 'descending'], ['property' => 'title', 'direction' => 'ascending']], 'sort: Points descending then Task: stored as a list of {property, direction}');
ok(titles(rows_as(27, $db, $sv)) === ['SMOKE Build the board', 'SMOKE Fix the login', 'SMOKE Ship it'], 'and the rows come in that order (8, 3, 2)');
$h = page($marco, '/databases/' . $db . '?view=' . $sv)['body'];
ok($ids($h, 'row-row-') === [$build, $fix, $ship], 'the table shows them in that order');
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'Too many', 'sort' => [['property' => 'points'], ['property' => 'kind'], ['property' => 'status'], ['property' => 'title']]]);
ok($c === 422 && str_contains(msg($b), 'up to three'), 'four sort keys: refused in words');
$gv = mkview($marco, $db, 'By kind', ['group_by' => 'kind', 'sub_group_by' => 'status']);
$h = page($marco, '/databases/' . $db . '?view=' . $gv)['body'];
ok(str_contains($h, 'id="table-group-Bug"') && str_contains($h, 'id="table-group-Feature"') && str_contains($h, 'id="table-group-Feature-Todo"') && str_contains($h, 'id="table-group-Bug-Done"'), 'group by Kind with sub-group Status: Bug › Done, Feature › Todo');
$h2 = substr($h, (int) strpos($h, 'id="table-group-Feature"'));
ok(strpos($h2, $build) !== false && strpos($h2, $ship) !== false && strpos($h2, $build) < strpos($h2, 'id="row-row-' . $ship) + 1000, 'the Feature rows sit under it');
$pv = mkview($marco, $db, 'Few columns', ['visible_properties' => ['title', 'points', 'kind']]);
$h = page($marco, '/databases/' . $db . '?view=' . $pv)['body'];
ok(str_contains($h, 'id="database-col-points"') && str_contains($h, 'id="database-col-kind"') && !str_contains($h, 'id="database-col-status"') && !str_contains($h, 'id="database-col-owner"') && !str_contains($h, 'id="cell-' . $fix . '-status"'), 'hidden properties are absent from the table; the title is always there');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $pv, 'visible_all' => 'yes']);
ok($c === 200 && view_row($pv)['visible_properties'] === null, 'show all again: visible_properties empty');
[$c, $b] = act($marco, '/databases/views/save.php', ['view' => $pv, 'visible_properties' => ['title', 'nonesuch']]);
ok($c === 422, 'a visible property that is not there: 422');

echo "4. The board\n";
$bv = mkview($marco, $db, 'Board', ['layout' => 'board', 'group_by' => 'status']);
$h = page($marco, '/databases/' . $db . '?view=' . $bv)['body'];
ok(str_contains($h, 'id="board-column-Todo"') && str_contains($h, 'id="board-column-Done"') && str_contains($h, 'id="board-column-Doing"') && str_contains($h, 'id="board-column-none"') && str_contains($h, 'No Status'), 'a column per option (Todo, Doing, Done) and a "No Status" column');
$todo = substr($h, (int) strpos($h, 'id="board-column-Todo"'), 3000);
ok(str_contains($todo, 'row-card-' . $build) && str_contains($todo, 'row-card-' . $ship) && !str_contains(substr($todo, 0, (int) strpos($todo, 'id="board-column-Doing"') ?: 3000), 'row-card-' . $fix), 'cards in Todo (Build, Ship) and Done (Fix)');
preg_match('/id="board-column-Todo-count">(\d+)</', $h, $m1); preg_match('/id="board-column-Done-count">(\d+)</', $h, $m2); preg_match('/id="board-column-Doing-count">(\d+)</', $h, $m3);
ok($m1[1] === '2' && $m2[1] === '1' && $m3[1] === '0', 'the column headers count: Todo 2, Done 1, Doing 0');
ok(str_contains($h, 'class="sp-board"') && str_contains($h, 'data-key="status"') && str_contains($h, 'data-may="1"') && str_contains($h, 'data-value="Todo"'), 'the board knows its group property and which columns post what');
$since = last_activity_id();
[$c, $b] = act($marco, '/databases/rows/save.php', ['row' => $ship, 'p' => ['status' => 'Doing']]);
$h = page($marco, '/databases/' . $db . '?view=' . $bv)['body'];
preg_match('/id="board-column-Doing-count">(\d+)</', $h, $m3);
ok($c === 200 && $m3[1] === '1' && str_contains(substr($h, (int) strpos($h, 'id="board-column-Doing"'), 1500), 'row-card-' . $ship), 'a drag is row_update of Status: Ship it moves to Doing');
$l = activity('row.update', $since);
ok(count($l) === 1 && json_decode($l[0]['after'], true)['keys'] === ['status'], 'and logs the key Status');
act($marco, '/databases/rows/save.php', ['row' => $ship, 'p' => ['status' => '']]);
$h = page($marco, '/databases/' . $db . '?view=' . $bv)['body'];
ok(str_contains(substr($h, (int) strpos($h, 'id="board-column-none"'), 1500), 'row-card-' . $ship), 'a card with no Status sits in the "No Status" column');
act($marco, '/databases/rows/save.php', ['row' => $ship, 'p' => ['status' => 'Todo']]);
$h = page($ann, '/databases/' . $db . '?view=' . $bv)['body'];
ok(str_contains($h, '404') || !str_contains($h, 'board-column'), 'Ann sees no board');
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'Bad board', 'layout' => 'board', 'group_by' => 'points']);
ok($c === 422 && str_contains(msg($b), 'select, status or people'), 'a board by a number: ' . msg($b));
$ov = mkview($marco, $db, 'By owner', ['layout' => 'board', 'group_by' => 'owner']);
$h = page($marco, '/databases/' . $db . '?view=' . $ov)['body'];
ok(str_contains($h, 'id="board-column-SMOKE-Priya"') && str_contains($h, 'id="board-column-SMOKE-Marco"') && str_contains($h, 'data-value="26"'), 'a board by a people property: a column per person (a drop posts the member id)');

echo "5. Gallery and list\n";
$f = proof_file('cover.png', png_bytes());
[$c, $b] = upload($marco, '/files/upload.php', ['page' => $build, 'as' => 'cover'], $f, 'cover.png', 'image/png');
$cover = (int) ($b['record_id'] ?? 0);
$gv2 = mkview($marco, $db, 'Gallery', ['layout' => 'gallery', 'card_size' => 'small']);
$h = page($marco, '/databases/' . $db . '?view=' . $gv2)['body'];
ok($c === 200 && str_contains($h, 'id="row-card-' . $build . '"') && str_contains($h, 'src="/files/' . $cover . '/thumb"') && str_contains($h, 'sp-gallery-small') && count($ids($h, 'row-card-')) === 3, 'a gallery of cards with the cover (the page cover\'s thumbnail) and the visible properties');
ok(str_contains($h, 'Points:') && str_contains($h, 'SMOKE Build the board'), 'each card carries its properties (Points: …)');
$lv = mkview($marco, $db, 'List', ['layout' => 'list']);
$h = page($marco, '/databases/' . $db . '?view=' . $lv)['body'];
ok(count($ids($h, 'row-card-')) === 3 && str_contains($h, 'list-group-item'), 'a list: one line per row');
[$c, $d] = screen($marco, '/databases/' . $db . '?view=' . $lv);
ok($c === 200 && $d['view']['layout'] === 'list' && $d['total'] === 3, 'JSON for the list');

echo "6. Calendar and timeline\n";
$cv = mkview($marco, $db, 'Calendar', ['layout' => 'calendar', 'calendar_by' => 'Due']);
$h = page($marco, '/databases/' . $db . '?view=' . $cv . '&month=2026-10')['body'];
$day = function (string $d) use ($h): string { $i = strpos($h, 'id="calendar-day-' . $d . '"'); $j = strpos($h, 'id="calendar-day-', $i + 10); return $i === false ? '' : substr($h, $i, ($j === false ? 4000 : $j - $i)); };
$d1 = $day('2026-10-01'); $d20 = $day('2026-10-20');
ok(str_contains($d1, 'SMOKE Fix the login') && str_contains($d20, 'SMOKE Build the board') && !str_contains($d1, 'SMOKE Ship it') && substr_count($h, 'SMOKE Ship it') === 0, 'a month grid: the two dated rows on their days; the undated one absent');
ok(str_contains($h, 'id="calendar-weeks"') && str_contains($h, 'id="calendar-weekday-2026-10-01"') && str_contains($h, 'id="calendar-month">October 2026<'), 'and the week list the phone shows instead of the grid');
ok(str_contains($h, 'href="/databases/' . $db . '?view=' . $cv . '&amp;month=2026-09"') && str_contains($h, '&amp;month=2026-11"'), 'previous and next month arrows');
$h = page($marco, '/databases/' . $db . '?view=' . $cv . '&month=2026-11')['body'];
ok(!str_contains($h, 'SMOKE Fix the login') && str_contains($h, 'id="calendar-day-2026-11-05"'), 'next month: no rows, its own days');
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'No date', 'layout' => 'calendar']);
ok($c === 422 && str_contains(msg($b), 'calendar needs a date property'), 'a calendar without a date property: the CHECK\'s words — ' . msg($b));
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'No date', 'layout' => 'calendar', 'calendar_by' => 'points']);
ok($c === 422 && str_contains(msg($b), 'not a date property'), 'a calendar by a number: ' . msg($b));
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'No start', 'layout' => 'timeline']);
ok($c === 422 && str_contains(msg($b), 'timeline needs a start'), 'a timeline without a start: ' . msg($b));
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'No group', 'layout' => 'board']);
ok($c === 422 && str_contains(msg($b), 'board needs a property to group by'), 'a board without a group: ' . msg($b));
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'Odd', 'layout' => 'kanban']);
ok($c === 422 && str_contains(msg($b), 'layout is'), 'an unknown layout: ' . msg($b));
$mv = mkview($marco, $db, 'Timeline', ['layout' => 'timeline', 'timeline_start' => 'Due', 'timeline_end' => 'Due']);
$h = page($marco, '/databases/' . $db . '?view=' . $mv . '&week=2026-09-28')['body'];
ok(str_contains($h, 'id="timeline-row-' . $fix . '"') && str_contains($h, 'id="timeline-row-' . $build . '"') && !str_contains($h, 'timeline-row-' . $ship), 'a timeline by Due–Due: a bar per dated row (Fix, Build), none for the undated');
preg_match('/id="timeline-row-' . $build . '"[^>]*>\s*<div class="sp-timeline-bar" style="left: ([\d.]+)%; width: ([\d.]+)%/', $h, $m);
ok(isset($m[2]) && abs((float) $m[2] - (3 / 56 * 100)) < 0.01 && abs((float) $m[1] - (22 / 56 * 100)) < 0.01, 'Build\'s bar runs 20–22 Oct: three days wide, starting 22 days in (' . ($m[1] ?? '?') . '%, ' . ($m[2] ?? '?') . '%)');
ok(str_contains($h, 'id="timeline-prev"') && str_contains($h, 'week=2026-08-03') && str_contains($h, 'week=2026-11-23'), 'earlier and later weeks');
$h = page($marco, '/databases/' . $db . '?view=' . $mv . '&week=2026-11-30')['body'];
ok(!str_contains($h, 'timeline-row-') && str_contains($h, 'No dated rows'), 'a window with no dated rows says so');
$h = page($marco, '/databases/' . $db . '?view=' . $mv)['body'];
ok(str_contains($h, 'id="timeline-head"') && str_contains($h, 'class="sp-timeline"'), 'and the default window is this week on');

echo "7. Reorder, delete\n";
$tabs = fn () => $ids(page($marco, '/databases/' . $db)['body'], 'view-tab-');
$before = array_column(array_values(array_filter(views_of($db), fn ($v) => $v['linked_from_page_id'] === null)), 'id');
ok($tabs() === $before && $before[0] === $lab['view'], 'the tabs are the views in position order, Table first');
$last = end($before);
$since = last_activity_id();
[$c, $b] = act($marco, '/databases/views/reorder.php', ['view' => $last, 'after' => '']);
$after = array_column(array_values(array_filter(views_of($db), fn ($v) => $v['linked_from_page_id'] === null)), 'id');
ok($c === 200 && $after[0] === $last && $tabs() === $after, 'view_reorder with no `after`: the view goes first');
[$c, $b] = act($marco, '/databases/views/reorder.php', ['view' => $last, 'after' => $before[2]]);
$after = array_column(array_values(array_filter(views_of($db), fn ($v) => $v['linked_from_page_id'] === null)), 'id');
ok($c === 200 && array_search($last, $after) === 3 && $tabs() === $after, 'after another view: it follows it (sp_position_between)');
$l = activity('view.reorder', $since);
ok(count($l) === 2 && $l[0]['entity_uuid'] === $last, 'view.reorder is logged');
[$c, $b] = act($marco, '/databases/views/reorder.php', ['view' => $last, 'after' => (string) one('SELECT id::text FROM database_views WHERE database_id <> CAST(:d AS uuid) LIMIT 1', ['d' => $db])]);
ok($c === 422 && str_contains(msg($b), 'not one of this database'), 'after a view of another database: refused in words');
$since = last_activity_id();
[$c, $b] = act($marco, '/databases/views/delete.php', ['view' => $last]);
ok($c === 200 && views_of($db) !== [] && !in_array($last, array_column(views_of($db), 'id'), true), 'view_delete');
ok(count(activity('view.delete', $since)) === 1, 'view.delete is logged');
$plain = (string) (act($marco, '/databases/save.php', ['title' => 'SMOKE One view db', 'space' => $w['product']])[1]['record_id'] ?? '');
[$c, $b] = act($marco, '/databases/views/delete.php', ['view' => views_of($plain)[0]['id']]);
ok($c === 422 && str_contains(msg($b), 'keeps one view') && count(views_of($plain)) === 1, 'the last view of a database cannot be deleted: "' . msg($b) . '"');
[$c, $b] = act($dana, '/databases/views/delete.php', ['view' => $tv]);
ok($c === 200 || $c === 403, 'a member with edit may delete a view');
[$c, $b] = act($ann, '/databases/views/delete.php', ['view' => $pv]);
ok($c === 404, 'Ann: the view does not exist for her');

echo "8. A linked view on a page\n";
$hb = $w['handbook'];
$since = last_activity_id();
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'On the handbook', 'layout' => 'list', 'linked_from' => $hb, 'sort' => [['property' => 'points', 'direction' => 'ascending']]]);
$lk = (string) ($b['record_id'] ?? '');
ok($c === 200 && view_row($lk)['linked_from_page_id'] === $hb && (int) one("SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid) AND type = 'link_to_page' AND content->>'view' = :v AND content->>'database_id' = :d", ['p' => $hb, 'v' => $lk, 'd' => $db]) === 1, 'view_save with linked_from: a linked view, and a pointer block (database + view) on the page');
$r = page($marco, '/pages/' . $hb . '?reader=1');
$h = $r['body'];
ok($r['code'] === 200 && str_contains($h, 'id="linked-view-' . $lk . '"') && str_contains($h, 'SMOKE Fix the login') && str_contains($h, 'SMOKE Ship it') && !str_contains(substr($h, (int) strpos($h, 'id="linked-view-' . $lk . '"')), 'hx-post="/databases/rows/save.php"'), 'the page lists the same rows read-only (no cell forms)');
ok(strpos($h, 'SMOKE Ship it') < strpos($h, 'SMOKE Build the board'), 'in the linked view\'s own sort (Points ascending: Ship it first)');
$r = page($marco, '/pages/' . $hb);
ok($r['code'] === 200 && str_contains($r['body'], 'id="linked-view-' . $lk . '"'), 'and in the editor\'s page too');
$r = page($ann, '/pages/' . $hb);
$h = $r['body'];
ok(!str_contains($h, 'SMOKE Fix the login'), 'someone who cannot see the database sees none of its rows through the page');
[$c, $b] = act($marco, '/databases/views/save.php', ['database' => $db, 'name' => 'Nowhere', 'linked_from' => $db]);
ok($c === 422 && isset(fields($b)['linked_from']), 'a linked view needs a page, not a database: refused');
[$c, $b] = act($marco, '/databases/views/delete.php', ['view' => $lk]);
$r = page($marco, '/pages/' . $hb . '?reader=1');
ok($c === 200 && str_contains($r['body'], 'was removed'), 'deleting the linked view leaves the pointer saying "removed"');

echo "9. Load more\n";
$many = (string) (act($marco, '/databases/save.php', ['title' => 'SMOKE Many rows', 'space' => $w['product']])[1]['record_id'] ?? '');
as_viewer(27);
pdo()->prepare("SELECT sp_row_create(CAST(:d AS uuid), jsonb_build_object('title', sp_rich_text('SMOKE Row ' || lpad(g::text, 3, '0'))), NULL) FROM generate_series(1, 105) g")->execute(['d' => $many]);
$h = page($marco, '/databases/' . $many)['body'];
ok(count($ids($h, 'row-row-')) === 100 && str_contains($h, 'id="database-load-more"') && str_contains($h, '100 of 105'), 'the table pages at 100: "100 of 105" and Load more');
$h = page($marco, '/databases/' . $many . '?limit=200')['body'];
ok(count($ids($h, 'row-row-')) === 105 && !str_contains($h, 'id="database-load-more"'), 'Load more shows them all');
[$c, $d] = screen($marco, '/databases/' . $many);
ok($d['total'] === 105 && count($d['rows']) === 100, 'JSON pages at 100 too, with the total');
finish();
