<?php
/** Proof — exports (spec "Proof", 9): a page as md and as html (the subpages folder, the images), a database as csv (relations as titles) and json, a space zip with index.md holding only what the exporter may see, a channel as json/md/csv for a period with threads nested, everything with no DM, the download logged, a stranger's 404, delete unlinks, the agent pause in the registry. */
require __DIR__ . '/lib.php';
$w = worker_world(); $fx = fixtures();
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30); $owner = as_member(1); $bea = as_member(28);
$product = $w['product']; $launch = $w['launch'];
$run = substr(md5((string) microtime(true)), 0, 6);
$mkdir = fn (string $p) => $p;

echo "1. A page: Markdown, one file\n";
$top = mk_in($marco, $product, "SMOKE export top $run");
$kid = mk_in($marco, $product, "SMOKE export kid $run", ['parent' => $top]);
$gk = mk_in($marco, $product, "SMOKE export grandkid $run", ['parent' => $kid]);
act($marco, '/blocks/append.php', ['page' => $top, 'markdown' => "Top **words** and a list:\n\n- one\n- two\n\nA picture follows."]);
act($marco, '/blocks/append.php', ['page' => $kid, 'markdown' => "Kid page words.\n\n[[SMOKE export top $run]]"]);
act($marco, '/blocks/append.php', ['page' => $gk, 'markdown' => "Grandkid words."]);
$solo = mk_in($marco, $product, "SMOKE export solo $run");
act($marco, '/blocks/append.php', ['page' => $solo, 'markdown' => "# A heading\n\nSolo text with `code`."]);
$log0 = last_activity_id();
[$c, $b] = act($marco, '/exports/page.php', ['page' => $solo, 'format' => 'md']);
$e1 = (int) $b['record_id'];
ok($c === 200 && ($b['ok'] ?? false) && $b['status'] === 'done' && str_ends_with($b['location'], 'notice=made'), 'export_page answers at once: ' . ($b['did'] ?? ''));
$row = export_row($e1); $path = export_path($e1);
ok($row['status'] === 'done' && $row['kind'] === 'page' && $row['format'] === 'md' && str_ends_with($path, '.md') && is_file($path) && (int) $row['byte_size'] === filesize($path), 'one .md file under storage/exports/<id>/, its size on the row');
$md = file_get_contents($path);
ok(str_starts_with($md, "# SMOKE export solo $run") && str_contains($md, 'Solo text with `code`.'), 'the text is sp_page_markdown(): the title, then the blocks');
ok(strtotime($row['expires_at']) > time() + 6.9 * 86400 && strtotime($row['expires_at']) < time() + 7.1 * 86400, 'it expires in 7 days');
$ev = activity_after('page.export', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"format": "md"') && str_contains((string) $ev[0]['after'], '"export_id": ' . $e1) && !str_contains((string) $ev[0]['after'], 'Solo text'), 'page.export logged with ids, never text');

echo "2. A page: HTML, and with subpages and images\n";
act($marco, '/blocks/append.php', ['page' => $top, 'markdown' => 'x']);
$blk = (string) one("SELECT id::text FROM blocks WHERE page_id = CAST(:p AS uuid) AND type = 'paragraph' ORDER BY position DESC LIMIT 1", ['p' => $top]);
[, $b] = upload($marco, '/files/upload.php', ['block' => $blk], proof_file('exp.png', png_bytes(20, 12)), 'exp.png', 'image/png');
$aid = (int) $b['attachment']['attachment_id'];
[$c, $b] = act($marco, '/exports/page.php', ['page' => $solo, 'format' => 'html']);
$h = file_get_contents(export_path((int) $b['record_id']));
ok($c === 200 && str_starts_with($h, '<!doctype html>') && str_contains($h, '<title>SMOKE export solo') && str_contains($h, '@media print') && str_contains($h, '<code') && !str_contains($h, '<script'), 'HTML: a standalone document with the print styles inline, no script');
[$c, $b] = act($marco, '/exports/page.php', ['page' => $top, 'format' => 'md', 'include_subpages' => 'yes']);
$e2 = (int) $b['record_id']; $z = zip_files(export_path($e2));
$names = array_keys($z);
ok(str_ends_with(export_path($e2), '.zip') && in_array("SMOKE export top $run.md", $names, true) && in_array("SMOKE export top $run/SMOKE export kid $run.md", $names, true) && in_array("SMOKE export top $run/SMOKE export kid $run/SMOKE export grandkid $run.md", $names, true), 'with include_subpages: a zip — the page, a folder of its subpages, theirs in turn');
ok(in_array("files/$aid-exp.png", $names, true) && str_contains($z["SMOKE export top $run.md"], "files/$aid-exp.png") && !str_contains($z["SMOKE export top $run.md"], '/files/' . $aid . ')'), 'the image is copied into files/ and the link made relative: ' . (preg_match('/!\[[^\]]*\]\(([^)]+)\)/', $z["SMOKE export top $run.md"], $m) ? $m[1] : 'no image link'));
ok(str_contains($z["SMOKE export top $run/SMOKE export kid $run.md"], 'Kid page words'), 'a subpage holds its own text');
[$c, $b] = act($marco, '/exports/page.php', ['page' => $top, 'format' => 'html', 'include_subpages' => 'yes']);
$zh = zip_files(export_path((int) $b['record_id']));
ok(isset($zh["SMOKE export top $run.html"]) && isset($zh["SMOKE export top $run/SMOKE export kid $run.html"]) && str_contains($zh["SMOKE export top $run.html"], 'src="files/' . $aid . '-exp.png"'), 'HTML with subpages: .html files, the images as files beside them');
$tn = (string) one('SELECT count(*) FROM exports WHERE id = :i', ['i' => $e2]);
[$c, $b] = act($marco, '/exports/page.php', ['page' => $solo, 'format' => 'pdf']);
ok($c === 422 && str_contains(msg($b), 'md or html'), 'a format a page does not have: 422 in words');
$hidkid = mk_in($marco, $product, "SMOKE export hidden kid $run", ['parent' => $top]); act($marco, '/pages/restrict.php', ['page' => $hidkid]);
act($marco, '/blocks/append.php', ['page' => $hidkid, 'markdown' => 'SMOKE secret words of the hidden kid']);
[$c, $b] = act($priya, '/exports/page.php', ['page' => $top, 'format' => 'md', 'include_subpages' => 'yes']);
$zp = zip_files(export_path((int) $b['record_id']));
ok($c === 200 && isset($zp["SMOKE export top $run/SMOKE export kid $run.md"]) && !str_contains(implode("\n", array_keys($zp)), 'hidden kid') && !str_contains(implode("\n", $zp), 'secret words'), 'Priya\'s export of the page with subpages leaves out the subpage restricted away from her — its name and its words');
[$c, $b] = act($marco, '/exports/page.php', ['page' => $top, 'format' => 'md', 'include_subpages' => 'yes']);
ok(str_contains(implode("\n", array_keys(zip_files(export_path((int) $b['record_id'])))), 'hidden kid'), 'while Marco\'s export of the same page has it');
$hid = mk_in($marco, $product, "SMOKE export hidden $run"); act($marco, '/pages/restrict.php', ['page' => $hid]);
[$c, $b] = act($priya, '/exports/page.php', ['page' => $hid]);
ok($c === 404, 'a page restricted away from her: 404, as everywhere');
[$c, $b] = act(as_member(29), '/exports/page.php', ['page' => $top]);
ok(in_array($c, [403, 404], true), 'a guest has no export.own: refused');

echo "3. A database: csv and json\n";
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['tree']);
$hb = (string) one("SELECT id::text FROM pages WHERE plain_title = 'SMOKE Handbook' AND archived_at IS NULL ORDER BY created_at DESC LIMIT 1");
$tdb = (string) one("SELECT p.id::text FROM pages p JOIN databases d ON d.id = p.id WHERE p.plain_title = 'SMOKE Tasks' AND p.parent_page_id = CAST(:h AS uuid)", ['h' => $hb]);
$log0 = last_activity_id();
[$c, $b] = act($marco, '/exports/database.php', ['database' => $tdb, 'format' => 'csv']);
$csv = file_get_contents(export_path((int) $b['record_id']));
$lines = array_map('str_getcsv', array_filter(explode("\n", $csv)));
ok($c === 200 && $lines[0] === ['Task', 'Points', 'Done', 'Due', 'Kind', 'Tags', 'Link', 'Notes', 'SMOKE Epics'] && count($lines) === 6, 'a CSV: the header and every row (5): ' . count($lines));
$ship = array_values(array_filter($lines, fn ($l) => $l[0] === 'SMOKE Ship it'))[0] ?? [];
ok(($ship[8] ?? '') === 'SMOKE Epic One, SMOKE Epic Two' && ($ship[2] ?? '') === 'No' && ($ship[5] ?? '') === 'ops', 'relations are exported as titles, a checkbox as Yes/No');
$ev = activity_after('page.export', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"format": "csv"'), 'page.export logged for it');
// a rollup and people
$lab = lab_database('Export lab ' . $run);
$epic = $w['epics']; $launchEpic = $w['launch_epic'];
act($marco, '/databases/rows/relation.php', ['row' => $launchEpic, 'property' => 'Tasks', 'targets' => [$w['fix'], $w['build']]]);
[$c, $b] = act($marco, '/exports/database.php', ['database' => $epic, 'format' => 'csv']);
$el = array_map('str_getcsv', array_filter(explode("\n", file_get_contents(export_path((int) $b['record_id'])))));
$hdr = $el[0]; $launchRow = array_values(array_filter($el, fn ($l) => $l[0] === 'SMOKE Launch'))[0] ?? [];
$pi = array_search('Points', $hdr, true); $ti = array_search('Tasks', $hdr, true);
ok($c === 200 && $launchRow !== [] && ($launchRow[$pi] ?? '') === '11' && str_contains((string) ($launchRow[$ti] ?? ''), 'SMOKE Fix the login'), 'a rollup is exported as displayed (11 points), its relation by the tasks\' titles');
[$c, $b] = act($marco, '/exports/database.php', ['database' => $lab['db'], 'format' => 'csv']);
$ll = array_map('str_getcsv', array_filter(explode("\n", file_get_contents(export_path((int) $b['record_id'])))));
$oi = array_search('Owner', $ll[0], true);
ok(array_values(array_filter($ll, fn ($l) => $l[0] === 'SMOKE Fix the login'))[0][$oi] === 'SMOKE Priya', 'people are exported by name');
[$c, $b] = act($marco, '/exports/database.php', ['database' => $tdb, 'format' => 'json']);
$j = json_decode(file_get_contents(export_path((int) $b['record_id'])), true);
ok($c === 200 && $j['database']['title'] === 'SMOKE Tasks' && count($j['database']['properties']) === 9 && count($j['rows']) === 5 && ($j['rows'][0]['values']['smoke_epics'] ?? '') !== '', 'JSON: the schema (9 properties) and the 5 rows with their values');
$view = views_of($lab['db'])[0]['id'];
as_viewer(27);
$vid = mkview($marco, $lab['db'], 'Export view', ['layout' => 'table', 'visible_properties' => 'points,kind']);
[$c, $b] = act($marco, '/exports/database.php', ['database' => $lab['db'], 'format' => 'csv', 'view' => $vid]);
$vl = array_map('str_getcsv', array_filter(explode("\n", file_get_contents(export_path((int) $b['record_id'])))));
ok($c === 200 && $vl[0] === ['Task', 'Points', 'Kind'] && count($vl) === 4, 'a view: only its visible properties (Task, Points, Kind): ' . json_encode($vl[0]));
[$c, $b] = act($marco, '/exports/database.php', ['database' => $lab['db'], 'format' => 'csv', 'view' => $view . 'x']);
ok($c === 422 && isset(fields($b)['view']), 'a view that is not this database\'s: 422');
[$c, $b] = act($marco, '/exports/database.php', ['database' => $top, 'format' => 'csv']);
ok($c === 404 || $c === 422, 'a page is not a database (' . $c . ')');

echo "4. A space: only what the exporter may see\n";
$hid2 = mk_in($marco, $product, "SMOKE export space hidden $run"); act($marco, '/pages/restrict.php', ['page' => $hid2]);
[$c, $b] = act($dana, '/exports/space.php', ['space' => $product, 'format' => 'md']);
ok($c === 403, 'Dana (a member, no export.space): refused in words: ' . msg($b));
give_roles(30, ['space_owner', 'user']);
act($marco, '/spaces/members/owner.php', ['space' => $product, 'member' => 30, 'owner' => 'yes']);
$log0 = last_activity_id();
[$c, $b] = act($dana, '/exports/space.php', ['space' => $product, 'format' => 'md']);
$e4 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && ($b['status'] ?? '') === 'queued' && export_row($e4)['status'] === 'queued' && !is_file(export_path($e4)), 'as an owner with export.space her export is QUEUED for the worker, not made in the request');
$ev = activity_after('space.export', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"space_id": ' . $product), 'space.export logged');
$html = req('GET', '/exports/', ['jar' => $dana])['body'];
ok(str_contains($html, 'id="export-row-' . $e4 . '"') && str_contains($html, 'hx-trigger="every 3s"'), 'the list shows it as a card that polls itself');
$r = step('exports');
ok(($r['done'] ?? 0) >= 1 && export_row($e4)['status'] === 'done', 'the worker\'s exports step made it: ' . json_encode($r));
$zd = zip_files(export_path($e4));
as_viewer(30);
$seen = array_column(q("SELECT plain_title FROM mcp_pages WHERE space_id = :s AND archived_at IS NULL AND NOT is_template AND kind = 'page' AND parent_database_id IS NULL", ['s' => $product]), 'plain_title');
preg_match_all('/\[([^\]]*)\]\(/', $zd['index.md'], $mm); $inIndex = array_values(array_filter($mm[1], fn ($t) => !str_contains($t, '(database')));
$visAll = array_column(q("SELECT plain_title FROM mcp_pages WHERE space_id = :s AND archived_at IS NULL AND NOT is_template", ['s' => $product]), 'plain_title');
ok(isset($zd['index.md']) && array_diff($seen, $inIndex) === [] && array_diff($inIndex, $visAll) === [], 'index.md lists exactly the pages Dana sees (' . count($seen) . ' of them) and nothing else');
$allNames = implode("\n", array_keys($zd));
ok(str_contains($allNames, 'SMOKE Tasks.csv') && str_contains($allNames, 'SMOKE Tasks/SMOKE Fix the login.md'), 'databases are a CSV plus their rows as pages in a folder');
[$c, $b] = act($marco, '/exports/space.php', ['space' => $product, 'format' => 'md']);
step('exports');
$zm = zip_files(export_path((int) $b['record_id']));
as_viewer(27);
preg_match_all('/\[([^\]]*)\]\(/', $zm['index.md'], $mm2);
ok(in_array("SMOKE export space hidden $run", $mm2[1], true), 'Marco\'s own export of the same space does list it (the difference is the exporter)');
[$c, $b] = act($marco, '/exports/space.php', ['space' => $product, 'format' => 'html']);
step('exports');
$zh = zip_files(export_path((int) $b['record_id']));
ok(count(array_filter(array_keys($zh), fn ($n) => str_ends_with($n, '.html'))) > 5 && isset($zh['index.md']), 'a zip of HTML for the same space');
[$c, $b] = act($marco, '/exports/space.php', ['space' => $product, 'format' => 'json']);
step('exports');
$sj = json_decode(file_get_contents(export_path((int) $b['record_id'])), true);
ok(($sj['space']['name'] ?? '') === 'SMOKE Product' && count($sj['pages']) > 5 && $sj['databases'] !== [], 'JSON for the space: its pages (with Markdown) and databases');
[$c, $b] = act($priya, '/exports/space.php', ['space' => $product]);
ok($c === 403, 'Priya (not an owner): 403');
give_roles(30, ['user']);
act($marco, '/spaces/members/owner.php', ['space' => $product, 'member' => 30, 'owner' => 'no']);

echo "5. A channel: json, md, csv; a period; threads nested\n";
[$c, $b] = act($marco, '/channels/save.php', ['space' => $product, 'name' => 'smoke-exp-' . $run, 'kind' => 'public', 'topic' => 'Export proof']);
$ch = (int) $b['record_id'];
act($priya, '/channels/join.php', ['channel' => $ch]);
[, $b] = post($marco, $ch, 'SMOKE early message'); $early = (int) $b['record_id'];
[, $b] = post($priya, $ch, 'SMOKE root message with a thread'); $rootm = (int) $b['record_id'];
reply($marco, $rootm, 'SMOKE reply in the thread');
act($priya, '/channels/messages/react.php', ['message' => $rootm, 'emoji' => '👍']);
[, $b] = post($marco, $ch, 'SMOKE late message'); $late = (int) $b['record_id'];
as_postgres("SET session_replication_role = replica; UPDATE messages SET created_at = created_at - interval '10 days' WHERE id = $early; UPDATE messages SET created_at = created_at - interval '3 days' WHERE id IN ($rootm, " . ((int) one('SELECT max(id) FROM messages WHERE thread_root_id = :r', ['r' => $rootm])) . ')');
$from = date('Y-m-d', strtotime('-5 days')); $to = date('Y-m-d', strtotime('-1 day'));
$log0 = last_activity_id();
[$c, $b] = act($marco, '/exports/channel.php', ['channel' => $ch, 'format' => 'json', 'from' => $from, 'to' => $to]);
$e5 = (int) $b['record_id'];
ok($c === 200 && $b['status'] === 'queued' && export_row($e5)['status'] === 'queued', 'a channel export is queued');
$ev = activity_after('channel.export', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"from": "' . $from . '"') && str_contains((string) $ev[0]['after'], '"format": "json"'), 'channel.export logged with the period and the format');
step('exports');
$j = json_decode(file_get_contents(export_path($e5)), true);
$texts = array_column($j['messages'], 'text');
ok($j['channel']['name'] === 'smoke-exp-' . $run && $texts === ['SMOKE root message with a thread'], 'the period holds only the message from 3 days ago (not the 10-day-old one, not today\'s): ' . json_encode($texts));
ok(count($j['messages'][0]['thread']) === 1 && $j['messages'][0]['thread'][0]['text'] === 'SMOKE reply in the thread' && $j['messages'][0]['thread'][0]['author'] === 'SMOKE Marco', 'the thread is nested under its message, authors by name');
ok($j['messages'][0]['reactions'][0] === ['emoji' => '👍', 'count' => 1] && $j['messages'][0]['author'] === 'SMOKE Priya', 'reactions and the author\'s name');
[$c, $b] = act($marco, '/exports/channel.php', ['channel' => $ch, 'format' => 'md']); step('exports');
$mdt = file_get_contents(export_path((int) $b['record_id']));
ok(str_contains($mdt, '## ' . date('Y-m-d', strtotime('-3 days'))) && str_contains($mdt, '**SMOKE Priya**') && str_contains($mdt, '> **SMOKE Marco**') && str_contains($mdt, 'SMOKE early message') && str_contains($mdt, 'SMOKE late message'), 'Markdown: a heading a day, threads quoted under their message; no period = everything');
[$c, $b] = act($marco, '/exports/channel.php', ['channel' => $ch, 'format' => 'csv', 'from' => $from]); step('exports');
$cl = array_map('str_getcsv', array_filter(explode("\n", file_get_contents(export_path((int) $b['record_id'])))));
ok($cl[0][0] === 'message_id' && count($cl) === 4 && $cl[1][4] === 'SMOKE root message with a thread' && $cl[2][3] === (string) $rootm, 'CSV: a row per message and reply, the reply knows its thread; "from" alone is open-ended');
[$c, $b] = act($marco, '/exports/channel.php', ['channel' => $ch, 'format' => 'json', 'from' => '2026-13-45']);
ok($c === 422 && str_contains(msg($b), 'date'), 'a bad date: 422 in words');
[$c, $b] = act($marco, '/exports/channel.php', ['channel' => $ch, 'format' => 'json', 'from' => '2026-10-10', 'to' => '2026-10-01']);
ok($c === 422 && str_contains(msg($b), 'ends before'), 'a period that ends before it starts: 422');
[, $db0] = act($owner, '/dm/open.php', ['member' => 26]); $dm = (int) $db0['record_id'];
post($owner, $dm, 'SMOKE private words in a DM');
[$c, $b] = act($owner, '/exports/channel.php', ['channel' => $dm, 'format' => 'json']);
ok($c === 422 && str_contains(msg($b), 'direct message'), 'a DM is never exported: 422');
[$c, $b] = act($priya, '/exports/channel.php', ['channel' => $ch, 'format' => 'json']);
ok($c === 403, 'a member who does not own the space: 403');

echo "6. Everything\n";
$log0 = last_activity_id();
[$c, $b] = act($marco, '/exports/all.php', []);
ok($c === 403, 'Marco has no export.all: 403');
[$c, $b] = act($owner, '/exports/all.php', []);
$e6 = (int) $b['record_id'];
ok($c === 200 && $b['status'] === 'queued' && export_row($e6)['format'] === 'zip', 'the admin\'s export of everything is queued');
ok(count(activity_after('export.all', $log0)) === 1, 'export.all logged');
step('exports');
$za = zip_files(export_path($e6));
$an = array_keys($za);
ok(count(array_filter($an, fn ($n) => str_starts_with($n, 'SMOKE Product/'))) > 10 && isset($za['SMOKE Product/index.md']) && isset($za['SMOKE Product/channels/smoke-exp-' . $run . '.md']), 'a folder per space with its pages, index.md and its channels as Markdown');
$blob = implode("\n", $za);
ok(!str_contains($blob, 'SMOKE private words in a DM') && count(array_filter($an, fn ($n) => preg_match('#(^|/)(dm|direct)#i', $n))) === 0, 'no direct message is in it');
ok(str_contains($blob, 'SMOKE root message with a thread') && isset($za['SMOKE Product/channels/smoke-launch.md']), 'but the channels are');

echo "7. Download, delete, strangers\n";
$log0 = last_activity_id();
$r = req('GET', '/exports/download.php?id=' . $e1, ['jar' => $marco]);
ok($r['code'] === 200 && str_contains($r['headers'], 'X-Content-Type-Options: nosniff') && str_contains($r['headers'], 'attachment; filename="SMOKE export solo') && $r['body'] === $md, 'the maker downloads it: nosniff, an attachment, the same bytes');
$ev = activity_after('export.download', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"export_id": ' . $e1) && str_contains((string) $ev[0]['after'], '"byte_size"') && export_row($e1)['downloaded_at'] !== null, 'export.download logged (export_id, kind, byte_size), downloaded_at stamped');
ok(req('GET', '/exports/download.php?id=' . $e1, ['jar' => $priya])['code'] === 404, 'a stranger\'s download is a 404 (as if it did not exist)');
ok(req('GET', '/exports/download.php?id=' . $e1)['code'] === 401 || req('GET', '/exports/download.php?id=' . $e1)['code'] === 302, 'no session: not served');
ok(req('GET', '/exports/download.php?id=' . $e1, ['jar' => $owner])['code'] === 200, 'the Spaces admin may download anyone\'s');
ok(req('GET', '/exports/download.php?id=99999999', ['jar' => $marco])['code'] === 404, 'an export that does not exist: 404');
[$c, $b] = act($priya, '/exports/delete.php', ['export' => $e1]);
ok($c === 404, 'Priya cannot delete Marco\'s export (404)');
[$c, $b] = act($owner, '/exports/delete.php', ['export' => $e1]);
ok($c === 404, 'not even the admin through export_delete: it is the maker\'s own');
$aid = (int) one("SELECT id FROM attachments WHERE record_type = 'export' AND record_id = :i", ['i' => $e1]);
$log0 = last_activity_id();
[$c, $b] = act($marco, '/exports/delete.php', ['export' => $e1]);
clearstatcache();
ok($c === 200 && !is_file($path) && export_row($e1)['storage_path'] === null && (int) one("SELECT count(*) FROM attachments WHERE record_type = 'export' AND record_id = :i", ['i' => $e1]) === 0, 'export_delete unlinks the file, takes the attachment, keeps the row');
$ev = activity_after('export.delete', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"via": "person"') && req('GET', '/exports/download.php?id=' . $e1, ['jar' => $marco])['code'] === 404, 'export.delete logged (via person); the download is gone');
$mine = screen($marco, '/exports/')[1]['exports'];
$gone = array_values(array_filter($mine, fn ($x) => $x['export_id'] === $e1))[0] ?? [];
ok(($gone['status'] ?? '') === 'expired' && $gone['download_url'] === null && count(array_filter($mine, fn ($x) => $x['created_by'] !== 27)) === 0, 'the list shows it expired with no Download; it lists only my exports');
$adm = screen($owner, '/exports/')[1];
ok($adm['all'] === true && count(array_filter($adm['exports'], fn ($x) => $x['created_by'] === 27)) > 3, 'the admin\'s list is everyone\'s');
[$c, $b] = act($marco, '/exports/delete.php', ['export' => $e4]);
ok($c === 404, 'an export of someone else (Dana\'s): not Marco\'s to delete');
pdo()->exec("UPDATE exports SET status = 'queued' WHERE id = $e5");
[$c, $b] = act($marco, '/exports/delete.php', ['export' => $e5]);
ok($c === 422 && str_contains(msg($b), 'still being made'), 'an export still being made cannot be deleted');
pdo()->exec("UPDATE exports SET status = 'done' WHERE id = $e5");

echo "8. The agent pause is in the registry\n";
$reg = json_decode((string) file_get_contents(dirname(__DIR__, 3) . '/mcp/action_registry.json'), true);
$cat = fn (string $k) => $reg['actions'][$k]['approval'] ?? null;
ok(($cat('export_space') ?? '') === 'external_send' && ($cat('export_channel') ?? '') === 'external_send' && ($cat('export_all') ?? '') === 'external_send', 'export_space, export_channel and export_all carry the category external_send');
ok(($cat('export_page') ?? null) === null && ($cat('export_database') ?? null) === null && ($cat('retention_set') ?? '') === 'other', 'export_page and export_database do not pause; retention_set is category other');
finish();
