<?php
/** Proof — imports (spec "Proof", 8): one Markdown file, a Markdown zip (the tree, a CSV beside it as a database with inferred types and a relation), a Notion zip (ids kept, hex dropped, unsupported blocks), a CSV into a database, a bad zip, the preview, a big zip in the worker, the gates. */
require __DIR__ . '/lib.php';
$w = worker_world(); $fx = fixtures();
$marco = as_member(27); $priya = as_member(26); $lee = as_member(31); $ann = as_member(29);
$product = $w['product'];
$run = substr(md5((string) microtime(true)), 0, 6);

echo "1. One Markdown file\n";
$log0 = last_activity_id(); $pages0 = (int) one('SELECT count(*) FROM pages');
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['md']);
$id1 = (int) ($b['record_id'] ?? 0); $i = import_row($id1);
ok($c === 200 && ($b['ok'] ?? false) && $i['status'] === 'done' && $i['kind'] === 'markdown' && (int) $i['pages_made'] === 1, 'a .md is imported at once into the space\'s root: ' . ($b['did'] ?? ''));
$pg = (string) one("SELECT id::text FROM pages WHERE plain_title = 'SMOKE Imported notes' AND space_id = :s AND parent_page_id IS NULL ORDER BY created_at DESC LIMIT 1", ['s' => $product]);
$types = page_types($pg);
$want = ['bookmark', 'bulleted_list_item', 'callout', 'code', 'divider', 'equation', 'heading_1', 'heading_2', 'heading_3', 'image', 'link_to_page', 'numbered_list_item', 'paragraph', 'quote', 'table', 'table_row', 'to_do', 'toggle'];
ok($types === $want, 'the page holds every block type the converter supports: ' . implode(' ', array_diff($want, $types)) . implode(' ', array_diff($types, $want)));
ok((string) one('SELECT owner_member_id FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pg]) === '27' && (int) $i['blocks_made'] === (int) one('SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid)', ['p' => $pg]), 'made by Marco, the block count of the log is the real count');
ok(!in_array('heading_1', array_column(q("SELECT type FROM blocks WHERE page_id = CAST(:p AS uuid) AND plain_text = 'SMOKE Imported notes'", ['p' => $pg]), 'type')), 'the first "# …" line is the title, not a heading block');
ok((int) one("SELECT count(*) FROM search_index WHERE entity_uuid = CAST(:p AS uuid)", ['p' => $pg]) === 1, 'the search index was caught up (the import ran with the bulk flag)');
ok((int) one('SELECT count(*) FROM page_versions WHERE page_id = CAST(:p AS uuid) AND reason = \'import\'', ['p' => $pg]) === 1, 'one version with the reason import');
$ev = activity_after('page.import', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"kind": "markdown"') && str_contains((string) $ev[0]['after'], '"import_id": ' . $id1) && str_contains((string) $ev[0]['after'], '"pages_made": 1') && !str_contains((string) $ev[0]['after'], 'Intro with'), 'page.import logged: import_id, kind, pages_made, rows_made, unsupported — no text');
$att = (int) one("SELECT count(*) FROM attachments WHERE record_type = 'import' AND record_id = :i", ['i' => $id1]);
ok($att === 1, 'the upload is kept as a record_type = import attachment');

echo "2. A Markdown zip: the tree, the CSVs\n";
$pre = (int) one('SELECT count(*) FROM pages');
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['tree']);
$id2 = (int) $b['record_id']; $i = import_row($id2);
ok($i['status'] === 'done' && $i['kind'] === 'markdown_zip' && (int) $i['pages_made'] === 6 && (int) $i['rows_made'] === 7, 'the zip: 4 pages + 2 databases = 6, 7 rows (kind found from the file): ' . json_encode([$i['pages_made'], $i['rows_made']]));
$hb = page_by_exact('SMOKE Handbook'); $on = page_by_exact('SMOKE Onboarding'); $pol = page_by_exact('SMOKE Policies'); $leave = page_by_exact('SMOKE Leave');
$par = fn (string $p) => (string) one('SELECT parent_page_id::text FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $p]);
ok($par($hb) === '' && $par($on) === $hb && $par($pol) === $hb && $par($leave) === $pol, 'the parents are right: Handbook at the root; Onboarding and Policies under it; Leave under Policies (a folder with no .md is an empty page)');
ok((string) one('SELECT space_id FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $leave]) === (string) $product, 'all in the space');
$tasks = (string) one("SELECT p.id::text FROM pages p JOIN databases d ON d.id = p.id WHERE p.plain_title = 'SMOKE Tasks' AND p.parent_page_id = CAST(:h AS uuid)", ['h' => $hb]);
$epics = (string) one("SELECT p.id::text FROM pages p JOIN databases d ON d.id = p.id WHERE p.plain_title = 'SMOKE Epics' AND p.parent_page_id = CAST(:h AS uuid)", ['h' => $hb]);
ok($tasks !== '' && $epics !== '', 'a CSV in the folder is a database under its page: Tasks and Epics under Handbook');
$s = db_schema($tasks);
$types = array_map(fn ($k) => $s[$k]['type'] ?? '?', ['title' => 'title', 'points' => 'points', 'done' => 'done', 'due' => 'due', 'kind' => 'kind', 'tags' => 'tags', 'link' => 'link', 'notes' => 'notes', 'smoke_epics' => 'smoke_epics']);
ok($types === ['title' => 'title', 'points' => 'number', 'done' => 'checkbox', 'due' => 'date', 'kind' => 'select', 'tags' => 'multi_select', 'link' => 'url', 'notes' => 'rich_text', 'smoke_epics' => 'relation'], 'the types are inferred: number, checkbox, date, select, multi-select, url, rich_text, and a relation: ' . json_encode($types));
ok($s['title']['name'] === 'Task' && ($s['smoke_epics']['relation']['database_id'] ?? '') === $epics, 'the first column is the title; the relation points at the Epics database of the zip');
ok(array_column($s['kind']['select']['options'], 'name') === ['Feature', 'Bug'] && array_column($s['tags']['multi_select']['options'], 'name') === ['ui', 'db', 'ops'], 'select and multi-select options are the distinct values');
$rows = rows_as(27, $tasks);
$byT = array_column($rows, 'properties', 'title');
ok(count($rows) === 5 && ($byT['SMOKE Draft spec']['points'] ?? null) == 3 && ($byT['SMOKE Draft spec']['done'] ?? null) === true && ($byT['SMOKE Build it']['done'] ?? null) === false && ($byT['SMOKE Draft spec']['due']['start'] ?? '') === '2026-10-01', 'five rows with typed values (a number, a checkbox, a date)');
ok(array_column($byT['SMOKE Ship it']['smoke_epics'] ?? [], 'title') === ['SMOKE Epic One', 'SMOKE Epic Two'] && count($byT['SMOKE Retro']['smoke_epics'] ?? []) === 1, 'the relation links the rows by title (one row to two epics)');
ok(count(rows_as(27, $epics)) === 2, 'the Epics database has its two rows');
$img = q("SELECT b.content::text AS content FROM blocks b WHERE b.page_id = CAST(:p AS uuid) AND b.type = 'image' ORDER BY b.position", ['p' => $on]);
$c0 = json_decode($img[0]['content'], true); $c1 = json_decode($img[1]['content'] ?? '{}', true);
ok(count($img) === 2 && ($c0['attachment_id'] ?? 0) > 0 && str_starts_with((string) $c0['url'], '/files/') && ($c1['url'] ?? '') === 'https://example.com/web.png', 'an image of the zip is stored as an attachment and linked (/files/N); an absolute URL stays a URL');
ok((int) one("SELECT count(*) FROM attachments WHERE record_type = 'block' AND id = :a", ['a' => $c0['attachment_id']]) === 1 && str_contains($i['log'], 'SMOKE Handbook/SMOKE Tasks.csv') && substr_count($i['log'], "\n") >= 5, 'the log has a line per file');
ok(!str_contains($i['log'], '__MACOSX') && !str_contains($i['log'], '.DS_Store'), 'junk of a Mac zip is skipped');

echo "3. A Notion zip\n";
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['notion']);
$id3 = (int) $b['record_id']; $i = import_row($id3);
ok($i['status'] === 'done' && $i['kind'] === 'notion_zip' && (int) $i['pages_made'] === 3 && (int) $i['rows_made'] === 3, 'the Notion zip is recognised by its names: 2 pages + a database, 3 rows');
$proj = '1a2b3c4d-5e6f-4071-8293-a4b5c6d7e8f9'; $road = '01234567-89ab-cdef-0123-456789abcdef'; $back = '9f8e7d6c-5b4a-3928-1706-f5e4d3c2b1a0';
ok(page_exists($proj) && page_exists($road) && page_exists($back), 'the pages keep their Notion ids when free');
ok((string) one('SELECT plain_title FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $proj]) === 'SMOKE Projects' && (string) one('SELECT plain_title FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $road]) === 'SMOKE Roadmap' && (string) one('SELECT plain_title FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $back]) === 'SMOKE Backlog', 'the 32 hex is dropped from the titles');
ok($par($road) === $proj && (string) one('SELECT kind FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $back]) === 'database', 'Roadmap is under Projects; Backlog is a database');
$un = q("SELECT content->>'original_type' AS t FROM blocks WHERE page_id = CAST(:p AS uuid) AND type = 'unsupported' ORDER BY position", ['p' => $road]);
ok(array_column($un, 't') === ['heading_4', 'meeting_notes', 'transcription'] && (int) $i['unsupported'] === 3, 'heading_4, meeting notes and transcription become unsupported blocks keeping original_type; the count is on the import: ' . json_encode(array_column($un, 't')));
ok((string) one("SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid) AND plain_text = 'A fourth level heading'", ['p' => $road]) === '1', 'the text of the heading_4 is kept after its marker');
$bl = rows_as(27, $back);
ok(count($bl) === 3 && in_array('SMOKE Write the spec', titles($bl), true) && array_column(db_schema($back)['status']['select']['options'] ?? [], 'name') !== [], 'the CSV\'s Name column is the title; Status is a select');
$rowp = (string) one("SELECT id::text FROM pages WHERE parent_database_id = CAST(:d AS uuid) AND plain_title = 'SMOKE Write the spec'", ['d' => $back]);
ok((int) one("SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid) AND plain_text LIKE 'The row%'", ['p' => $rowp]) === 1, 'a Notion page named like a row is that row\'s body');
$projects0 = (int) one("SELECT count(*) FROM pages WHERE plain_title = 'SMOKE Projects' AND archived_at IS NULL");
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['notion']);
$i = import_row((int) $b['record_id']);
ok($i['status'] === 'done' && (int) one("SELECT count(*) FROM pages WHERE plain_title = 'SMOKE Projects' AND archived_at IS NULL") === $projects0 + 1 && (int) one("SELECT count(*) FROM pages WHERE id = CAST(:p AS uuid)", ['p' => $proj]) === 1, 'imported again: the ids are taken, so the second copy gets new ones (never a clash)');

echo "4. A CSV into an existing database\n";
$lab = lab_database('Import lab ' . $run);
$tdb = $lab['db'];
$before = count(rows_as(27, $tdb)); $schema0 = array_keys(db_schema($tdb));
[$c, $b] = act_file($marco, '/import/start.php', ['database' => $tdb], $fx['csv']);
$id4 = (int) $b['record_id']; $i = import_row($id4);
$s = db_schema($tdb);
ok($i['status'] === 'done' && $i['kind'] === 'csv' && (int) $i['rows_made'] === 3 && count(rows_as(27, $tdb)) === $before + 3, 'three rows added to the database');
ok(isset($s['impact']) && $s['impact']['type'] === 'select' && array_column($s['impact']['select']['options'], 'name') === ['High', 'Low'] && !in_array('impact', $schema0, true), 'the missing column "Impact" was added as a select');
ok(array_column($s['kind']['select']['options'], 'name') === ['Bug', 'Feature'], 'a column that exists keeps its schema');
$r1 = array_column(rows_as(27, $tdb), 'properties', 'title')['SMOKE Csv one'] ?? [];
ok(($r1['points'] ?? null) == 4 && ($r1['urgent'] ?? null) === true && ($r1['kind']['name'] ?? '') === 'Bug' && ($r1['impact']['name'] ?? '') === 'High', 'with their values by property');
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['csv'], null);
ok($c === 200 && import_row((int) $b['record_id'])['status'] === 'failed' && str_contains(import_row((int) $b['record_id'])['log'], 'FAILED') || $c === 422, 'a CSV with a space as its target is not a database import: it says so');

echo "5. A bad zip leaves nothing\n";
$pre = (int) one('SELECT count(*) FROM pages');
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['bad'], 'broken.zip');
$i = import_row((int) $b['record_id']);
ok($i['status'] === 'failed' && str_contains($i['log'], 'not a zip file') && (int) $i['pages_made'] === 0 && (int) one('SELECT count(*) FROM pages') === $pre, 'a file that is not a zip: failed with the sentence, no page made');
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['evil']);
$i = import_row((int) $b['record_id']);
ok($i['status'] === 'failed' && str_contains($i['log'], 'leaves its folder') && (int) one('SELECT count(*) FROM pages') === $pre, 'a zip with a path that climbs out ("../") is refused whole');
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], proof_file('notes.exe', 'MZ'), 'notes.exe');
ok($c === 422 && str_contains(msg($b), '.md, .zip or .csv'), 'a file of another kind: 422 in words: ' . msg($b));

echo "6. The preview\n";
$jar = $marco;
[$c, $b] = act_file($jar, '/import/start.php', ['space' => $product, 'preview' => 'yes'], $fx['tree']);
ok($c === 200 && str_starts_with((string) ($b['location'] ?? ''), '/import?preview='), 'preview=yes stores the zip and points at the preview: ' . ($b['location'] ?? ''));
parse_str((string) parse_url($b['location'], PHP_URL_QUERY), $q); $token = $q['preview'];
[$c, $d] = screen($jar, '/import?preview=' . $token . '&space=' . $product);
$pv = $d['preview'] ?? [];
ok($c === 200 && $pv['pages'] === 6 && $pv['databases'] === 2 && $pv['rows'] === 7 && $pv['unsupported'] === 0, 'the preview counts: ' . json_encode(array_diff_key($pv, ['tree' => 1])));
$titlesIn = function (array $t) use (&$titlesIn): array { $o = []; foreach ($t as $n) { $o[] = $n['title']; $o = array_merge($o, $titlesIn($n['children'])); } return $o; };
ok(in_array('SMOKE Policies', $titlesIn($pv['tree']), true) && $pv['tree'][0]['title'] === 'SMOKE Handbook', 'and the tree it will make');
$html = req('GET', '/import?preview=' . $token . '&space=' . $product, ['jar' => $jar])['body'];
ok(str_contains($html, 'id="import-preview"') && str_contains($html, 'id="import-confirm-btn"') && str_contains($html, 'id="import-preview-pages">6<'), 'the screen shows the counts and an "Import this" button');
[$c, $b] = act($jar, '/import/start.php', ['space' => $product, 'preview_token' => $token]);
$i = import_row((int) ($b['record_id'] ?? 0));
ok($c === 200 && $i['status'] === 'done' && (int) $i['pages_made'] === $pv['pages'] && (int) $i['rows_made'] === $pv['rows'] && (int) $i['unsupported'] === $pv['unsupported'], 'importing the preview makes exactly what it counted');
[$c, $b] = act($jar, '/import/start.php', ['space' => $product, 'preview_token' => $token]);
ok($c === 422, 'a preview is used once: the second import of it is refused');
[$c, $b] = act($lee, '/import/start.php', ['space' => $product, 'preview_token' => $token]);
ok(in_array($c, [403, 422], true), 'another member cannot use my preview');
[$c, $b] = act_file($jar, '/import/start.php', ['space' => $product, 'preview' => 'yes'], $fx['notion']);
parse_str((string) parse_url($b['location'], PHP_URL_QUERY), $q);
[, $d] = screen($jar, '/import?preview=' . $q['preview'] . '&space=' . $product);
ok(($d['preview']['unsupported'] ?? 0) === 3 && $d['preview']['kind'] === 'notion_zip' && $d['preview']['pages'] === 3, 'a Notion preview counts its 3 unsupported blocks: ' . json_encode(array_diff_key($d['preview'] ?? [], ['tree' => 1])));
[$c, $b] = act_file($jar, '/import/start.php', ['space' => $product, 'preview' => 'yes'], $fx['bad'], 'broken.zip');
ok($c === 422 && isset(fields($b)['file']), 'previewing a bad zip: 422 with the sentence');

echo "7. A large zip waits for the worker\n";
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['big']);
$id7 = (int) $b['record_id'];
ok($c === 200 && ($b['status'] ?? '') === 'queued' && import_row($id7)['status'] === 'queued' && filesize($fx['big']) > 3000000, 'a 3 MB zip is queued, not run in the request');
$poll = req('GET', '/import?id=' . $id7 . '&row=1', ['jar' => $marco])['body'];
ok(str_contains($poll, 'hx-trigger="every 3s"') && str_contains($poll, 'data-status="queued"'), 'the screen polls the row while it is queued');
$r = step('imports');
ok(($r['run'] ?? 0) >= 1 && import_row($id7)['status'] === 'done' && (int) import_row($id7)['pages_made'] === 1, 'the worker\'s imports step ran it: ' . json_encode($r));
$poll = req('GET', '/import?id=' . $id7 . '&row=1', ['jar' => $marco])['body'];
ok(!str_contains($poll, 'hx-trigger') && str_contains($poll, 'data-status="done"'), 'and the polled row says done and stops polling');
$ev = array_filter(activity_after('page.import', $log0), fn ($e) => str_contains((string) $e['after'], '"import_id": ' . $id7));
ok(count($ev) === 1 && array_values($ev)[0]['source'] === 'cron', 'page.import for it was logged by cron (the worker ran it)');
$r = step('imports');
ok(($r['run'] ?? -1) === 0, 'and nothing is run twice');

echo "8. Who may import where\n";
[$c, $b] = act_file($lee, '/import/start.php', ['space' => $product], $fx['md']);
ok($c === 403, 'Lee (not in the space): 403 in words: ' . msg($b));
[$c, $b] = act_file($ann, '/import/start.php', ['space' => $product], $fx['md']);
ok(in_array($c, [403, 404], true), 'a guest: refused (' . $c . ')');
$hid = mk_in($marco, $product, 'SMOKE import restricted ' . $run);
act($marco, '/pages/restrict.php', ['page' => $hid]);
[$c, $b] = act_file($priya, '/import/start.php', ['parent' => $hid], $fx['md']);
ok($c === 404, 'under a page Priya cannot see: 404');
$shared = mk_in($marco, $product, 'SMOKE import viewonly ' . $run);
act($marco, '/pages/restrict.php', ['page' => $shared]);
act($marco, '/pages/share.php', ['page' => $shared, 'member' => 26, 'level' => 'view']);
[$c, $b] = act_file($priya, '/import/start.php', ['parent' => $shared], $fx['md']);
ok($c === 403, 'under a page she may only view: 403');
[$c, $b] = act_file($priya, '/import/start.php', ['parent' => $on], $fx['md']);
ok($c === 200 && (int) one("SELECT count(*) FROM pages WHERE plain_title = 'SMOKE Imported notes' AND parent_page_id = CAST(:p AS uuid)", ['p' => $on]) >= 1, 'under a page she may edit: allowed, the page lands under it');
[$c, $b] = act_file($priya, '/import/start.php', ['database' => $w['tasks']], $fx['md']);
ok($c === 422 || $c === 200, 'a Markdown file given a database is judged by its kind');
[$c, $b] = act($priya, '/import/start.php', ['space' => $product]);
ok($c === 422 && isset(fields($b)['file']), 'no file: 422 with the field');
$mine = screen($priya, '/import')[1];
ok(($mine['imports'] ?? []) !== [] && count(array_filter($mine['imports'], fn ($x) => $x['created_by'] !== 26)) === 0, 'the screen lists my imports only (the view hides others\')');
$admin = screen(as_member(1), '/import')[1];
ok(count(array_filter($admin['imports'], fn ($x) => $x['created_by'] === 27)) > 0, 'the Spaces admin sees everyone\'s');
$html = req('GET', '/import', ['jar' => $marco])['body'];
ok(str_contains($html, 'id="import-form"') && str_contains($html, 'id="import-rows"') && str_contains($html, 'import-row-' . $id2), 'the screen: the form and the past imports with their logs');
echo "9. An import's file is kept as long as an export\n";
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['md']);
$fresh = (int) $b['record_id'];
[$c, $b] = act_file($marco, '/import/start.php', ['space' => $product], $fx['md']);
$oldI = (int) $b['record_id'];
$ap = (string) one("SELECT storage_path FROM attachments WHERE record_type = 'import' AND record_id = :i", ['i' => $oldI]);
pdo()->exec("UPDATE imports SET finished_at = now() - interval '8 days' WHERE id = $oldI");
$r = step('exports', ['SP_WORKER_NOW' => '2026-10-13T03:20:00Z']);
clearstatcache();
ok(($r['import_files'] ?? 0) >= 1 && (int) one("SELECT count(*) FROM attachments WHERE record_type = 'import' AND record_id = :i", ['i' => $oldI]) === 0 && !is_file(dirname(__DIR__, 3) . '/storage/' . $ap), 'an import finished 8 days ago loses its uploaded file (counted in the step)');
ok((int) one("SELECT count(*) FROM attachments WHERE record_type = 'import' AND record_id = :i", ['i' => $fresh]) === 1, 'a fresh import keeps its file');
$h = req('GET', '/import', ['jar' => $marco]);
ok($h['code'] === 200 && str_contains($h['body'], 'id="import-file-gone-' . $oldI . '"') && !str_contains($h['body'], 'id="import-file-gone-' . $fresh . '"') && import_row($oldI)['status'] === 'done', 'the screen still opens, its row and log stay, and it says the file is gone');
finish();
function page_exists(string $id): bool { return (int) one('SELECT count(*) FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $id]) === 1; }
