<?php
/** Proof — JSON mode: the eight actions under action tokens answer {ok, did, record_id, location, refresh}; the screens answer data; an agent under a run token. */
require __DIR__ . '/lib.php';
$w = worker_world(); $fx = fixtures();
$product = $w['product']; $launch = $w['launch'];
$contract = fn (array $b) => ($b['ok'] ?? false) === true && array_key_exists('record_id', $b) && isset($b['location'], $b['did']) && array_key_exists('refresh', $b);
$marcoT = ['X-Action-Token: ' . person_token(27)]; $priyaT = ['X-Action-Token: ' . person_token(26)]; $ownerT = ['X-Action-Token: ' . person_token(1)];
kernel_state(function ($s) { $s['facts']['4801'] = ['valid' => true, 'is_agent' => true, 'member_id' => 40, 'run_id' => 4801, 'request_id' => 'req-4801', 'trigger' => 'chat', 'endpoints' => [['name' => 'Actions MCP']]]; return $s; });
$seamus = as_agent(run_token(40, 4801));
$page = mk_in(as_member(27), $product, 'SMOKE JSON export page ' . substr(md5((string) microtime(true)), 0, 6));
act(as_member(27), '/blocks/append.php', ['page' => $page, 'markdown' => 'JSON mode words']);
$ch = channel_by_name($product, 'smoke-launch') ?? $launch;

echo "1. import_start\n";
[$c, $b] = act_file_token('/import/start.php', ['space' => $product], $fx['md'], $marcoT);
ok($c === 200 && $contract($b) && (int) $b['record_id'] > 0 && str_starts_with($b['location'], '/import?id=' . $b['record_id']) && $b['status'] === 'done' && $b['pages_made'] === 1, 'import_start: the contract, the import\'s id, its counts: ' . json_encode($b));
$iy = (int) $b['record_id'];
[$c, $b] = act_file_token('/import/start.php', ['space' => $product], $fx['big'], $marcoT);
ok($c === 200 && $contract($b) && $b['status'] === 'queued', 'a large zip: the same contract, status queued');
step('imports');
[$c, $b] = act_token('/import/start.php', ['space' => $product], $marcoT);
ok($c === 422 && isset(fields($b)['file']), 'no file: 422 with the field');
[$c, $b] = act_file_token('/import/start.php', ['space' => $product], $fx['md'], $marcoT, 'x.exe');
ok($c === 422, 'a file of another kind: 422');
[$c, $b] = act_file_token('/import/start.php', ['space' => $product], $fx['md'], ['X-Action-Token: ' . person_token(31)]);
ok($c === 403, 'Lee (not in the space): 403');
[$c, $b] = act_file_token('/import/start.php', ['space' => $product], $fx['md'], $seamus);
ok($c === 200 && $contract($b), 'an agent that is a member of the space may import (nothing pauses it: no approval category)');
$ix = (int) $b['record_id'];

echo "2. The exports\n";
[$c, $b] = act_token('/exports/page.php', ['page' => $page, 'format' => 'md'], $marcoT);
$e1 = (int) $b['record_id'];
ok($c === 200 && $contract($b) && $e1 > 0 && $b['status'] === 'done' && $b['location'] === '/exports/?notice=made' && $b['byte_size'] > 0, 'export_page: the contract');
[$c, $b] = act_token('/exports/database.php', ['database' => $w['tasks'], 'format' => 'csv'], $marcoT);
ok($c === 200 && $contract($b) && $b['status'] === 'done', 'export_database: the contract');
[$c, $b] = act_token('/exports/space.php', ['space' => $product], $marcoT);
$e3 = (int) $b['record_id'];
ok($c === 200 && $contract($b) && $b['status'] === 'queued', 'export_space: the contract, queued');
[$c, $b] = act_token('/exports/channel.php', ['channel' => $ch, 'format' => 'json'], $marcoT);
ok($c === 200 && $contract($b) && $b['status'] === 'queued', 'export_channel: the contract, queued');
[$c, $b] = act_token('/exports/all.php', [], $ownerT);
ok($c === 200 && $contract($b) && $b['status'] === 'queued', 'export_all: the contract, queued');
[$c, $b] = act_token('/exports/all.php', [], $marcoT);
ok($c === 403, 'export_all by someone without export.all: 403');
step('exports');
[$c, $b] = act_token('/exports/page.php', ['page' => $page, 'format' => 'md'], $seamus);
ok($c === 200 && $contract($b), 'an agent exports a page it may see (the pause of export_space/channel/all is the hook\'s, in front of the endpoint)');
[$c, $b] = act_token('/exports/delete.php', ['export' => $e1], $marcoT);
ok($c === 200 && $contract($b) && (int) $b['record_id'] === $e1, 'export_delete: the contract');
[$c, $b] = act_token('/exports/delete.php', ['export' => $e1], $priyaT);
ok($c === 404, 'export_delete of something that is not yours: 404');

echo "3. retention_set\n";
[$c, $b] = act_token('/channels/retention.php', ['channel' => $ch, 'days' => 14], $marcoT);
ok($c === 200 && $contract($b) && (int) $b['record_id'] === $ch && $b['retention_days'] === 14, 'retention_set: the contract and the new days');
[$c, $b] = act_token('/channels/retention.php', ['channel' => $ch, 'days' => ''], $marcoT);
ok($c === 200 && $b['retention_days'] === null, 'empty keeps forever');
[$c, $b] = act_token('/channels/retention.php', ['channel' => $ch, 'days' => 5], $priyaT);
ok($c === 403, 'by a member: 403');

echo "4. The screens answer data\n";
$jar = as_member(27);
[$c, $d] = screen($jar, '/import');
ok($c === 200 && isset($d['imports'][0]['import_id'], $d['imports'][0]['status'], $d['imports'][0]['pages_made']) && isset($d['spaces']) && array_key_exists('preview', $d), '/import: imports (id, status, counts), spaces, preview');
[$c, $d] = screen($jar, '/import?id=' . $iy);
ok($c === 200 && $d['import']['import_id'] === $iy && isset($d['import']['log']), '/import?id=: one import with its log');
[$c, $d] = screen($jar, '/import?id=' . $ix);
ok($c === 404, 'an import of someone else\'s (the agent\'s) is a 404 for Marco');
[$c, $d] = screen($jar, '/exports/');
$e = $d['exports'][0] ?? [];
ok($c === 200 && isset($e['export_id'], $e['kind'], $e['format'], $e['status'], $e['subject'], $e['expires_at'], $e['byte_size']) && $d['all'] === false, '/exports/: my exports with their state, subject, size and expiry');
ok(count(array_filter($d['exports'], fn ($x) => $x['status'] === 'done' && str_starts_with((string) $x['download_url'], '/exports/download.php?id='))) >= 1, 'a finished one carries its download URL');
$r = req('GET', '/exports/', ['jar' => $jar, 'headers' => JSONH, ]);
ok($r['code'] === 200 && !str_contains($r['body'], 'storage_path') && !str_contains($r['body'], '/storage/'), 'no storage path in the data');
$r = req('GET', '/exports/', ['headers' => array_merge(JSONH, $seamus)]);
ok($r['code'] === 403, 'an agent is not given the screen (it uses the actions)');
$r = req('GET', '/import', ['headers' => array_merge(JSONH, $seamus)]);
ok($r['code'] === 403, 'nor the import screen');
$r = req('GET', '/exports/', ['headers' => JSONH]);
ok($r['code'] === 401, 'anonymous: 401');
$r = req('GET', '/exports/', ['jar' => as_member(29), 'headers' => JSONH]);
ok($r['code'] === 403, 'a guest: 403');
finish();
