<?php
/** Proof — the database's own passes through the worker (spec "Proof", 3, 4, 6, 7): scheduled messages and reminders, snapshots and the prune, wiki expiry, an export's expiry, the search index's catch-up. */
require __DIR__ . '/lib.php';
$w = wiki_world();
$w += agents_world();
$marco = as_member(27); $priya = as_member(26);
$launch = $w['launch'];
drain_outbox();
pdo()->exec("UPDATE members SET last_seen_at = now() - interval '3 hours' WHERE id IN (26, 28, 30)");

echo "1. Scheduled messages\n";
$t = (new DateTimeImmutable('+1 hour'))->format('Y-m-d H:i');
[$c, $b] = post($marco, $launch, 'SMOKE scheduled ping @SMOKE Priya @SMOKE Seamus', ['schedule_for' => $t]);
$sid = (int) $b['record_id'];
ok($c === 200 && message_db($sid)['sent_at'] === null, 'a scheduled message waits, unsent');
$count0 = (int) channel_row($launch)['message_count']; $n0 = last_note_id(); $log0 = last_activity_id();
step('scheduled');
ok(message_db($sid)['sent_at'] === null, 'not due: the pass leaves it');
pdo()->exec("UPDATE messages SET scheduled_for = now() - interval '1 minute' WHERE id = $sid");
$r = step('scheduled');
ok(($r['sent'] ?? 0) === 1 && message_db($sid)['sent_at'] !== null, 'due: sent on the pass (counted 1)');
ok((int) channel_row($launch)['message_count'] === $count0 + 1, 'the channel\'s message count follows');
ok(count(notes(26, 'mention', $n0)) === 1, 'the mention notified Priya');
ok(dispatch_id_of($sid, 40) > 0, 'the mention of an agent became a dispatch for Seamus');
$ev = activity_after('message.post', $log0);
ok(count($ev) === 1 && $ev[0]['source'] === 'cron' && str_contains((string) $ev[0]['after'], '"via": "scheduled"') && !str_contains((string) $ev[0]['after'], 'ping'), 'message.post logged by cron with via = scheduled, no words');
$r = step('scheduled');
ok(($r['sent'] ?? -1) === 0, 'a second pass releases nothing');

echo "2. Reminders\n";
[$c, $b] = act($priya, '/reminders/save.php', ['text' => 'SMOKE the reminder', 'remind_at' => date('Y-m-d\TH:i', time() + 86400 * 2), 'message' => $w['priya_msg']]);
$rid = (string) ($b['record_id'] ?? '');
ok($c === 200 && $rid !== '', 'Priya makes a reminder two days out');
$n0 = last_note_id(); $log0 = last_activity_id();
$r = step('reminders');
ok(count(notes(26, 'reminder', $n0)) === 0, 'not due: nothing');
pdo()->exec("UPDATE reminders SET remind_at = now() - interval '1 minute' WHERE id = " . (int) $rid);
$r = step('reminders');
ok(($r['fired'] ?? 0) === 1 && count(notes(26, 'reminder', $n0)) === 1, 'due: one reminder notice');
$r = step('reminders');
ok(($r['fired'] ?? -1) === 0 && count(notes(26, 'reminder', $n0)) === 1, 'and only once');
ok(count(activity_after('reminder.fire', $log0)) === 1, 'reminder.fire logged (cron)');

echo "3. Snapshots and the prune\n";
$pg = mk_in($marco, $w['product'], 'SMOKE snapshot page');
act($marco, '/blocks/append.php', ['page' => $pg, 'markdown' => 'First words.']);
$v0 = (int) one('SELECT version_no FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pg]);
$r = step('snapshots');
ok((int) one('SELECT version_no FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pg]) === $v0, 'a page edited just now is not quiet yet: no version');
pdo()->exec("UPDATE pages SET last_edited_at = now() - interval '2 hours' WHERE id = CAST('$pg' AS uuid)");
$log0 = last_activity_id();
$r = step('snapshots');
$v1 = (int) one('SELECT version_no FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pg]);
ok($v1 === $v0 + 1 && ($r['versions'] ?? 0) >= 1, 'a quiet, changed page got a version by the pass');
ok((string) one("SELECT reason FROM page_versions WHERE page_id = CAST(:p AS uuid) ORDER BY version_no DESC LIMIT 1", ['p' => $pg]) === 'interval', 'with the reason interval');
step('snapshots');
ok((int) one('SELECT version_no FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pg]) === $v1 && count(array_filter(activity_after('page.version_save', $log0), fn ($e) => $e['entity_uuid'] === $pg)) === 1, 'nothing twice: no new version, one page.version_save logged');
pdo()->exec("SELECT set_config('app.member_id', '27', false)");
for ($i = 0; $i < 3; $i++) { pdo()->exec("SELECT sp_version_save(CAST('$pg' AS uuid), 'manual')"); }
$days = (int) one('SELECT version_retention_days FROM sp_settings WHERE id = 1');
as_postgres("SET session_replication_role = replica; UPDATE page_versions SET created_at = now() - interval '" . ($days + 10) . " days' WHERE page_id = '$pg'");
$newest = (int) one('SELECT max(id) FROM page_versions WHERE page_id = CAST(:p AS uuid)', ['p' => $pg]);
$before = (int) one('SELECT count(*) FROM page_versions WHERE page_id = CAST(:p AS uuid)', ['p' => $pg]);
$r = step('prune');
$after = (int) one('SELECT count(*) FROM page_versions WHERE page_id = CAST(:p AS uuid)', ['p' => $pg]);
ok($before >= 4 && $after === 1 && (int) one('SELECT max(id) FROM page_versions WHERE page_id = CAST(:p AS uuid)', ['p' => $pg]) === $newest && ($r['pruned'] ?? 0) >= $before - 1, "versions past $days days pruned ($before → $after), the newest kept");

echo "4. Wiki expiry\n";
$n0 = last_note_id(); $log0 = last_activity_id();
$ex = $w['expired'];
pdo()->exec("UPDATE pages SET verification_state = 'verified' WHERE id = CAST('$ex' AS uuid)");       // (a rerun on the same database starts from the same place)
pdo()->exec("DELETE FROM notifications WHERE dedupe_key = 'wiki_expired:$ex'");
ok((string) one('SELECT verification_state FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $ex]) === 'verified', 'the page is still "verified" in the row though its date has passed');
$r = step('wiki');
ok((string) one('SELECT verification_state FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $ex]) === 'expired' && ($r['expired'] ?? 0) >= 1, 'the pass marks it expired');
$nn = array_filter(notes(26, 'verification', $n0), fn ($x) => str_contains($x['title'], 'SMOKE Wiki Expired'));
ok(count($nn) === 1, 'its owner (Priya) was told');
step('wiki');
ok(count(array_filter(notes(26, 'verification', $n0), fn ($x) => str_contains($x['title'], 'SMOKE Wiki Expired'))) === 1, 'and told once');
$ev = array_filter(activity_after('page.verify', $log0), fn ($e) => $e['entity_uuid'] === $ex);
ok(count($ev) === 1 && str_contains((string) array_values($ev)[0]['after'], 'expired'), 'page.verify with state expired logged by cron');

echo "5. An export's expiry\n";
[$c, $b] = act($marco, '/exports/page.php', ['page' => $pg, 'format' => 'md']);
$eid = (int) $b['record_id'];
$path = export_path($eid);
ok($c === 200 && is_file($path) && export_row($eid)['status'] === 'done', 'Marco\'s page export is made, a file under storage/exports/');
$aid = (int) one("SELECT id FROM attachments WHERE record_type = 'export' AND record_id = :i", ['i' => $eid]);
ok($aid > 0, 'and an export attachment serves it through the gated door');
$r = req('GET', '/files/' . $aid, ['jar' => $marco]);
ok($r['code'] === 200 && str_contains($r['headers'], 'X-Content-Type-Options: nosniff'), '/files/{id} gives it to its maker');
$r2 = req('GET', '/files/' . $aid, ['jar' => as_member(28)]);
ok($r2['code'] === 404, '…and 404 to a stranger');
pdo()->exec("UPDATE exports SET expires_at = now() - interval '1 day' WHERE id = $eid");
$log0 = last_activity_id();
$r = step('exports');
clearstatcache();
ok(!is_file($path) && ($r['expired'] ?? 0) >= 1, 'past its 7 days the file is removed by the pass');
ok(export_row($eid)['storage_path'] === null && (int) one("SELECT count(*) FROM attachments WHERE record_type = 'export' AND record_id = :i", ['i' => $eid]) === 0, 'the row keeps no path, the attachment is gone');
$list = screen($marco, '/exports/')[1];
$mine = array_values(array_filter($list['exports'], fn ($e) => $e['export_id'] === $eid))[0] ?? [];
ok(($mine['status'] ?? '') === 'expired' && $mine['download_url'] === null, 'the list says expired and offers no download');
$r = req('GET', '/exports/download.php?id=' . $eid, ['jar' => $marco]);
ok($r['code'] === 404, 'a download of it is a 404');
$ev = activity_after('export.delete', $log0);
ok(count($ev) >= 1 && str_contains((string) $ev[0]['after'], 'expiry'), 'export.delete logged by cron with via = expiry');

echo "6. The search index's catch-up\n";
pdo()->exec("SELECT set_config('app.member_id', '27', false)");
pdo()->beginTransaction();
pdo()->exec("SELECT set_config('app.sp_bulk', '1', true)");
$bulk = (string) one("SELECT sp_page_create(" . (int) $w['product'] . ", NULL, sp_rich_text('SMOKE bulk indexed zebra'), 'page')::text");
pdo()->prepare("SELECT sp_block_insert(CAST(:p AS uuid), NULL, NULL, 'paragraph', jsonb_build_object('rich_text', sp_rich_text('quokkaword in the bulk page')))")->execute(['p' => $bulk]);
pdo()->commit();
ok((int) one("SELECT count(*) FROM search_index WHERE entity_uuid = CAST(:p AS uuid)", ['p' => $bulk]) === 0, 'a page made with app.sp_bulk on is not in the index');
$r = step('search');
ok(($r['indexed'] ?? 0) >= 1 && (int) one("SELECT count(*) FROM search_index WHERE entity_uuid = CAST(:p AS uuid)", ['p' => $bulk]) === 1, 'the pass catches it up');
ok(in_array('SMOKE bulk indexed zebra', array_column(screen($marco, '/search?q=quokkaword')[1]['pages'] ?? [], 'title'), true) || str_contains(req('GET', '/search?q=quokkaword', ['jar' => $marco])['body'], 'SMOKE bulk indexed zebra'), 'and search finds it');
finish();
