<?php
/** Proof — retention and the trash (spec "Proof", 5, and "Retention", 9): a 7-day channel loses a day-8 message and its file; the trash purge takes a page past the setting with its subtree and files, not a younger one; retention_set's gates. */
require __DIR__ . '/lib.php';
$w = worker_world();
$marco = as_member(27); $priya = as_member(26); $owner = as_member(1); $dana = as_member(30);
$product = $w['product'];

echo "1. retention_set\n";
[$c, $b] = act($marco, '/channels/save.php', ['space' => $product, 'name' => 'smoke-retention-' . substr(md5((string) microtime(true)), 0, 6), 'kind' => 'public', 'topic' => 'Retention']);
$ch = (int) $b['record_id'];
act(as_member(26), '/channels/join.php', ['channel' => $ch]);
$log0 = last_activity_id();
[$c, $b] = act($marco, '/channels/retention.php', ['channel' => $ch, 'days' => 7]);
ok($c === 200 && (int) channel_row($ch)['retention_days'] === 7, 'the space owner (channel.manage) sets 7 days');
$ev = activity_after('channel.retention_set', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"retention_days": 7') && str_contains((string) $ev[0]['before'], 'null'), 'channel.retention_set logged with before and after');
[$c, $b] = act($owner, '/channels/retention.php', ['channel' => $ch, 'days' => 30]);
ok($c === 200 && (int) channel_row($ch)['retention_days'] === 30, 'the admin sets it too (30)');
[$c, $b] = act($priya, '/channels/retention.php', ['channel' => $ch, 'days' => 1]);
ok($c === 403 && str_contains(msg($b), 'Only an owner of the space') && (int) channel_row($ch)['retention_days'] === 30, 'a member is refused in words: ' . msg($b));
[$c, $b] = act($marco, '/channels/retention.php', ['channel' => $ch, 'days' => 99999]);
ok($c === 422 && isset(fields($b)['days']), 'days out of range: 422');
[$c, $b] = act($marco, '/channels/retention.php', ['channel' => $ch, 'days' => 7]);
[, $dmb] = act($owner, '/dm/open.php', ['member' => 26]);
$dm = (int) $dmb['record_id'];
[$c, $b] = act($owner, '/channels/retention.php', ['channel' => $dm, 'days' => 7]);
ok($c === 422 && str_contains(msg($b), 'direct message') && channel_row($dm)['retention_days'] === null, 'a DM: 422 "A direct message has no retention"');
$html = req('GET', '/channels/' . $ch, ['jar' => $marco])['body'];
ok(str_contains($html, 'id="channel-view-retention"') && str_contains($html, 'Messages older than 7 days are deleted'), 'the channel header says "Messages older than 7 days are deleted"');
$html = req('GET', '/channels/' . $w['launch'], ['jar' => $marco])['body'];
act($marco, '/channels/retention.php', ['channel' => $w['launch'], 'days' => '']);
ok(!str_contains(req('GET', '/channels/' . $w['launch'], ['jar' => $marco])['body'], 'Messages older than'), 'a channel that keeps everything says nothing');

echo "2. The pass deletes a day-8 message and its file\n";
[, $b] = upload($marco, '/files/upload.php', ['message' => $ch], proof_file('ret.png', png_bytes(12, 8)), 'ret.png', 'image/png');
$aid = (int) $b['attachment']['attachment_id'];
[, $b] = post($marco, $ch, 'SMOKE the old one with a picture', ['attachments' => (string) $aid]);
$old = (int) $b['record_id'];
[, $b] = post($marco, $ch, 'SMOKE the young one');
$young = (int) $b['record_id'];
[, $b] = post($priya, $ch, 'SMOKE a day-6 message');
$six = (int) $b['record_id'];
$file = dirname(__DIR__, 3) . '/storage/' . one('SELECT storage_path FROM attachments WHERE id = :a', ['a' => $aid]);
ok(is_file($file), 'the attachment\'s file is on disk');
as_postgres("SET session_replication_role = replica; UPDATE messages SET created_at = now() - interval '8 days' WHERE id = $old; UPDATE messages SET created_at = now() - interval '6 days' WHERE id = $six");
$log0 = last_activity_id();
$r = step('retention');
clearstatcache();
ok(($r['deleted'] ?? 0) === 1 && message_db($old) === [], 'a day-8 message in a 7-day channel is deleted');
ok(message_db($young) !== [] && message_db($six) !== [], 'a young one and a day-6 one are kept');
ok((int) one('SELECT count(*) FROM attachments WHERE id = :a', ['a' => $aid]) === 0 && !is_file($file) && ($r['files'] ?? 0) >= 1, 'its attachment\'s row and file are gone');
$ev = activity_after('message.delete', $log0);
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"via": "retention"') && str_contains((string) $ev[0]['after'], '"count": 1') && $ev[0]['source'] === 'cron' && !str_contains((string) $ev[0]['after'], 'old one'), 'message.delete logged by cron: via retention, a count, no words');
$r = step('retention');
ok(($r['deleted'] ?? -1) === 0, 'and nothing twice');
$kept = (int) one("SELECT count(*) FROM messages WHERE channel_id = :c AND created_at < now() - interval '30 days'", ['c' => $w['launch']]);
ok($kept === 0 || (int) one('SELECT retention_days FROM channels WHERE id = :c', ['c' => $w['launch']]) === 0 || channel_row($w['launch'])['retention_days'] === null, 'a channel with no retention is never touched');

echo "3. The trash purge\n";
$root = mk_in($marco, $product, 'SMOKE trash old root');
$kid = mk_in($marco, $product, 'SMOKE trash old kid', ['parent' => $root]);
$young_page = mk_in($marco, $product, 'SMOKE trash young');
act($marco, '/blocks/append.php', ['page' => $root, 'markdown' => 'a paragraph to hold a file']);
$blk = (string) one("SELECT id::text FROM blocks WHERE page_id = CAST(:p AS uuid) AND type = 'paragraph' LIMIT 1", ['p' => $root]);
[, $b] = upload($marco, '/files/upload.php', ['block' => $blk], proof_file('trash.png', png_bytes(10, 10)), 'trash.png', 'image/png');
$aBlock = (int) $b['attachment']['attachment_id'];
[, $b] = upload($marco, '/files/upload.php', ['page' => $kid], proof_file('cover.png', png_bytes(14, 10)), 'cover.png', 'image/png');
$aCover = (int) $b['attachment']['attachment_id'];
$files = array_map(fn ($a) => dirname(__DIR__, 3) . '/storage/' . one('SELECT storage_path FROM attachments WHERE id = :a', ['a' => $a]), [$aBlock, $aCover]);
ok(is_file($files[0]) && is_file($files[1]), 'a block\'s file and a subpage\'s cover are on disk');
act($marco, '/pages/trash.php', ['page' => $root]);
act($marco, '/pages/trash.php', ['page' => $young_page]);
ok(one('SELECT archived_at FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $kid]) !== null, 'trashing the root trashed the subpage with it');
$days = (int) one('SELECT trash_retention_days FROM sp_settings WHERE id = 1');
pdo()->exec("UPDATE pages SET archived_at = now() - interval '" . ($days + 1) . " days' WHERE id = CAST('$root' AS uuid)");
pdo()->exec("UPDATE pages SET archived_at = now() - interval '5 days' WHERE id = CAST('$young_page' AS uuid)");
$log0 = last_activity_id();
$r = step('trash');
clearstatcache();
ok((int) one("SELECT count(*) FROM pages WHERE id IN (CAST('$root' AS uuid), CAST('$kid' AS uuid))") === 0 && ($r['purged'] ?? 0) >= 2, "a page $days+ days in the trash is purged for good with its subpage: " . json_encode($r));
ok((int) one("SELECT count(*) FROM pages WHERE id = CAST('$young_page' AS uuid)") === 1, 'one trashed 5 days ago is still there');
ok((int) one('SELECT count(*) FROM attachments WHERE id IN (:a, :b)', ['a' => $aBlock, 'b' => $aCover]) === 0 && !is_file($files[0]) && !is_file($files[1]) && ($r['files'] ?? 0) >= 2, 'the files of the purged pages (a block\'s, a cover) are gone with their rows');
$ev = array_values(array_filter(activity_after('page.delete', $log0), fn ($e) => $e['entity_uuid'] === $root));
ok(count($ev) === 1 && str_contains((string) $ev[0]['after'], '"via": "trash"') && str_contains((string) $ev[0]['after'], '"subtree_count": 2') && $ev[0]['source'] === 'cron', 'page.delete logged by cron: via trash, subtree_count 2');
$r = step('trash');
ok(($r['purged'] ?? -1) === 0, 'and nothing twice');
finish();
