<?php
/** Proof — search (spec "Proof", 6): `rate limit` finds the page and the message with <mark> (escaped around it); each modifier narrows; a bad date is dropped with a notice; chips are removable; paging at 25; Dana finds only what she may see, a guest only what is shared; an empty query with is:page lists recent pages; the parser. */
require __DIR__ . '/lib.php';
require dirname(__DIR__, 3) . '/app/features/search/parse.php';
$w = databases_world();
$w = wiki_world() + $w;
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30); $ann = as_member(29);
$launch = $w['launch'];
$res = static function (string $jar, string $qs): array { [$c, $d] = screen($jar, '/search?' . $qs); return [$c, $d]; };
$all = static fn (array $d): array => array_merge(...array_values($d['results'] ?? ['page' => []]));
$titles = static fn (array $d): array => array_column($all($d), 'title');

echo "1. The parser\n";
$p = parse_search_query('rate limit in:#ops from:@priya has:link before:2026-09-01 after:2026-08-01 is:page space:Product');
ok($p['q'] === 'rate limit' && $p['in'] === '#ops' && $p['from'] === '@priya' && $p['has'] === 'link' && $p['before'] === '2026-09-01' && $p['after'] === '2026-08-01' && $p['is'] === 'page' && $p['space'] === 'Product' && $p['notices'] === [], 'every modifier is read and the words are what is left');
$p = parse_search_query('a in:#x in:#y after:2026-02-30 is:video has:everything ratio:2 from:');
ok($p['in'] === '#x' && $p['after'] === null && $p['is'] === null && $p['has'] === null && $p['q'] === 'a ratio:2' && count($p['notices']) === 5, 'a second modifier, a bad date, an unknown value and an empty one are dropped with a notice each; a word that only looks like a modifier stays a word');
$p = parse_search_query('"rate limit" from:"smoke priya"');
ok($p['q'] === '"rate limit"' && $p['from'] === 'smoke priya', 'a quoted phrase stays; a quoted value is one');
ok(parse_search_query('IN:#Ops Is:Page')['in'] === '#Ops' && parse_search_query('IS:Page')['is'] === 'page', 'modifier names are case-blind');

echo "2. rate limit finds the page and the message, the match marked\n";
[$c, $d] = $res($marco, 'q=rate+limit');
$pg = array_values(array_filter($d['results']['page'] ?? [], static fn (array $r): bool => $r['title'] === 'SMOKE Rate limits'));
$msg = $d['results']['message'] ?? [];
ok($c === 200 && count($pg) === 1 && count($msg) >= 2 && $d['total'] >= 4, 'the page, the messages and the comment (' . $d['total'] . ' in all)');
ok(str_contains($pg[0]['excerpt'], '<mark>rate</mark> <mark>limit</mark>') || str_contains($pg[0]['excerpt'], '<mark>rate limit</mark>') || str_contains($pg[0]['excerpt'], '<mark>'), 'the excerpt carries <mark> around the match: ' . substr($pg[0]['excerpt'], 0, 60));
$r = page($marco, '/search?q=rate+limit');
ok($r['code'] === 200 && str_contains($r['body'], 'id="search-results"') && str_contains($r['body'], 'id="search-group-page"') && str_contains($r['body'], 'id="search-group-message"') && str_contains($r['body'], 'id="search-group-comment"') && str_contains($r['body'], '<mark>'), 'the page: grouped Pages · Messages · Comments, with <mark>');
$order = array_map(static fn (string $k): int|false => strpos($r['body'], 'id="search-group-' . $k . '"'), ['page', 'message', 'comment']);
ok($order[0] < $order[1] && $order[1] < $order[2], 'in that order');
post($marco, $launch, 'SMOKE <b>raw</b> <script>alert(1)</script> rate limit trick');
$r = page($marco, '/search?q=trick');
post($marco, $launch, 'SMOKE Tom & "Jerry" <i>quoted</i> trick2');
$r2 = page($marco, '/search?q=trick2');
ok(!str_contains($r['body'], '<b>raw') && !str_contains($r['body'], '<script>alert(1)') && str_contains($r['body'], '<mark>trick</mark>') && str_contains($r2['body'], 'Tom &amp; &quot;Jerry&quot;') && !str_contains($r2['body'], '<i>quoted'),
    'the words are escaped; only the mark tags are tags (markup in a message never reaches the page as markup)');
ok(str_contains($r['body'], 'id="search-form"') && str_contains($r['body'], 'name="q"') && !str_contains($r['body'], 'hx-trigger="keyup'), 'Enter searches; typing does not (no live search)');

echo "3. Each modifier narrows\n";
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit is:message'));
ok(count($d['results']['page']) === 0 && count($d['results']['comment']) === 0 && count($d['results']['message']) >= 2, 'is:message: messages only');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit is:page'));
ok(count($d['results']['message']) === 0 && count($d['results']['page']) >= 1, 'is:page: pages only');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit is:comment'));
ok(count($d['results']['comment']) === 1 && str_contains($d['results']['comment'][0]['url'], '/pages/' . page_by_title('SMOKE Pricing 2027') . '#comment-'), 'is:comment: the comment, linking to its page and #comment-id');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit in:#smoke-launch'));
ok(count($d['results']['message']) >= 2 && count($d['results']['page']) === 0, 'in:#smoke-launch: that channel\'s messages');
ok(array_unique(array_column($d['results']['message'], 'channel_id')) === [$launch], 'only that channel');
[$c, $d2] = $res($marco, 'q=' . urlencode('rate limit in:' . $launch));
ok(count($d2['results']['message']) === count($d['results']['message']), 'in: takes a channel id too');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit from:@marco'));
ok(count($all($d)) >= 3 && array_unique(array_column(array_filter($all($d), static fn (array $r): bool => $r['who'] !== null), 'who')) !== [], 'from:@marco: only what Marco wrote');
$wrote = array_unique(array_map(static fn (array $r): int => $r['who']['member_id'], array_filter($all($d), static fn (array $r): bool => $r['who'] !== null)));
ok($wrote === [27], 'every hit is his (' . implode(',', $wrote) . ')');
[$c, $d] = $res($priya, 'q=' . urlencode('rate limit from:@me'));
$wrote = array_unique(array_map(static fn (array $r): int => $r['who']['member_id'], array_filter($all($d), static fn (array $r): bool => $r['who'] !== null)));
ok(count($all($d)) >= 1 && $wrote === [26], 'from:@me is the caller');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit has:link'));
ok(count($all($d)) >= 2 && count($all($d)) < $res($marco, 'q=rate+limit')[1]['total'], 'has:link: fewer than without it');
ok(count(array_filter($all($d), static fn (array $r): bool => $r['kind'] === 'message' && str_contains($r['excerpt'], 'ships Friday'))) === 1 && array_filter($all($d), static fn (array $r): bool => $r['title'] === 'SMOKE Rate limits') !== [], 'the message with the link and the page with the link');
[$c, $d] = $res($marco, 'q=' . urlencode('Friday has:file'));
ok($c === 200 && count($all($d)) === 0, 'has:file: nothing here has a file');
[, $b] = post($marco, $launch, 'SMOKE vintage rate limit memo');
$vint = (int) $b['record_id'];
pdo()->exec("UPDATE messages SET sent_at = now() - interval '40 days' WHERE id = $vint");
$day = static fn (int $ago): string => date('Y-m-d', time() - $ago * 86400);
[$c, $d] = $res($marco, 'q=' . urlencode('vintage before:' . $day(30)));
ok(count($d['results']['message']) === 1, 'before: a month ago finds the 40-day-old memo');
[$c, $d] = $res($marco, 'q=' . urlencode('vintage after:' . $day(30)));
ok(count($all($d)) === 0, 'after: a month ago does not');
[$c, $d] = $res($marco, 'q=' . urlencode('vintage after:' . $day(41) . ' before:' . $day(39)));
ok(count($d['results']['message']) === 1, 'after and before together bracket it');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit space:"SMOKE Product"'));
$sid = $w['product'];
ok($c === 200 && array_unique(array_column($all($d), 'space_id')) === [$sid] && count($all($d)) >= 2, 'space: by name');
[$c, $d] = $res($marco, 'q=rate+limit&space=' . $sid . '&is=page');
ok($c === 200 && count($d['results']['message']) === 0 && count($d['results']['page']) >= 1, 'the selects send the same modifiers as their own params');

echo "4. A bad modifier is dropped with a notice; chips remove\n";
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit before:2026-13-45'));
ok($c === 200 && $d['total'] >= 4 && count($d['notices']) === 1 && str_contains($d['notices'][0], 'not a date'), 'a bad date: the search still runs, one notice says so');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit in:#nowhere'));
ok($c === 200 && $d['total'] === 0 && str_contains(implode(' ', $d['notices']), '#nowhere'), 'a channel that is not there: nothing found, and told');
[$c, $d] = $res($marco, 'q=' . urlencode('rate limit from:@nobodyatall'));
ok($c === 200 && $d['total'] === 0 && str_contains(implode(' ', $d['notices']), '@nobodyatall'), 'a person who is not there: nothing found, and told');
$r = page($marco, '/search?q=' . urlencode('rate limit in:#smoke-launch from:@marco has:link is:message'));
ok(str_contains($r['body'], 'id="search-chips"') && str_contains($r['body'], 'id="search-chip-in"') && str_contains($r['body'], 'id="search-chip-from"') && str_contains($r['body'], 'id="search-chip-has"') && str_contains($r['body'], 'id="search-chip-is"'), 'the modifiers are chips');
preg_match('/id="search-chip-in-remove"/', $r['body'], $m);
preg_match('/<a href="([^"]+)"[^>]*id="search-chip-in-remove"/', $r['body'], $m);
$href = html_entity_decode($m[1] ?? '');
ok($href !== '' && !str_contains($href, 'in=') && str_contains($href, 'from=') && str_contains($href, 'has=link') && str_contains($href, 'is=message') && str_contains($href, 'q=rate+limit'), 'a chip\'s remove link keeps the rest: ' . $href);
$r2 = page($marco, $href);
ok($r2['code'] === 200 && !str_contains($r2['body'], 'id="search-chip-in"') && str_contains($r2['body'], 'id="search-chip-from"'), 'and the search re-runs without it');
ok(str_contains($r['body'], 'id="search-form-field-is"') && str_contains($r['body'], 'id="search-form-field-in"') && str_contains($r['body'], 'id="search-form-field-from"') && str_contains($r['body'], 'id="search-form-field-after"'), 'the same modifiers are selects');

echo "5. Paging at 25\n";
for ($i = 1; $i <= 30; $i++) { post($marco, $launch, "SMOKE pagetest number $i"); }
[$c, $d1] = $res($marco, 'q=pagetest');
[$c, $d2] = $res($marco, 'q=pagetest&page=2');
ok($d1['total'] === 30 && count($all($d1)) === 25 && count($all($d2)) === 5 && $d2['page'] === 2, '30 hits: 25 on the first page, 5 on the second');
ok(array_intersect(array_column($d1['results']['message'], 'message_id'), array_column($d2['results']['message'], 'message_id')) === [], 'no hit twice');
$r = page($marco, '/search?q=pagetest');
ok(str_contains($r['body'], 'id="search-next"') && !str_contains($r['body'], 'id="search-prev"') && str_contains($r['body'], 'Results 1–25 of 30'), 'page 1: Next, no Previous');
$r = page($marco, '/search?q=pagetest&page=2');
ok(!str_contains($r['body'], 'id="search-next"') && str_contains($r['body'], 'id="search-prev"') && str_contains($r['body'], 'Results 26–30 of 30'), 'page 2: Previous, no Next');

echo "6. Who may see what\n";
[$c, $d] = $res($marco, 'q=Hidden+is:page');
ok(in_array('SMOKE Wiki Hidden', $titles($d), true), 'Marco finds his private page');
[$c, $d] = $res($dana, 'q=Hidden+is:page');
ok($c === 200 && !in_array('SMOKE Wiki Hidden', $titles($d), true), 'Dana does not');
post($marco, $w['leads_channel'], 'SMOKE secret rate limit for the leads');
[$c, $d] = $res($priya, 'q=' . urlencode('secret rate limit'));
ok(count($d['results']['message']) === 1, 'Priya (in #smoke-leads-only) finds the leads\' message');
[$c, $d] = $res($dana, 'q=' . urlencode('secret rate limit'));
ok($c === 200 && $d['total'] === 0, 'Dana (not in it) finds nothing');
[$c, $d] = $res($dana, 'q=' . urlencode('rate limit in:#smoke-leads-only'));
ok($c === 200 && $d['total'] === 0 && count($d['notices']) === 1, 'and in: a channel she cannot read is "no such channel"');
[$c, $d] = $res($ann, 'q=' . urlencode('rate limit'));
$g = $titles($d);
ok($c === 200 && count($d['results']['message']) >= 2 && !in_array('SMOKE Rate limits', $g, true) && !in_array('SMOKE Wiki Hidden', $g, true) && count($d['results']['page']) === 0, 'the guest finds the channel she is a guest of, and no page that is not shared');
act($marco, '/pages/share-guest.php', ['page' => page_by_title('SMOKE Rate limits'), 'guest' => 29, 'level' => 'view']);
[$c, $d] = $res($ann, 'q=' . urlencode('rate limit is:page'));
ok(array_column($d['results']['page'], 'title') === ['SMOKE Rate limits'], 'shared with her: now exactly that page');
[$c, $d] = $res($ann, 'q=' . urlencode('secret rate limit'));
ok($d['total'] === 0, 'the leads\' message still not');

echo "7. Pages and rows: breadcrumbs, links; empty queries\n";
[$c, $d] = $res($marco, 'q=' . urlencode('Pricing 2027 is:page'));
$pr = array_values(array_filter($d['results']['page'], static fn (array $r): bool => $r['title'] === 'SMOKE Pricing 2027'))[0] ?? [];
ok($pr !== [] && $pr['where'] === ['SMOKE Product', 'SMOKE Product handbook', 'SMOKE Pricing'] && $pr['url'] === '/pages/' . $w['pricing2027'], 'a page: the space and its ancestors as the breadcrumb, a link to it');
[$c, $d] = $res($marco, 'q=' . urlencode('login is:row'));
$row = $d['results']['row'][0] ?? [];
ok($c === 200 && count($d['results']['row']) === 1 && $row['title'] === 'SMOKE Fix the login' && $row['url'] === '/databases/' . $w['tasks'] . '/rows/' . $w['fix'] && $row['where'][0] === 'SMOKE Product', 'a row: its database row page, in its space');
[$c, $d] = $res($marco, 'q=' . urlencode('is:page'));
ok($c === 200 && count($d['results']['page']) === min(25, $d['total']) && $d['total'] >= 10 && count($d['results']['message']) === 0, 'an empty query with is:page lists recent pages (' . $d['total'] . ' of them)');
$when = array_column($d['results']['page'], 'at'); $s = $when; rsort($s);
ok($when === $s, 'newest first');
$r = page($marco, '/search');
ok($r['code'] === 200 && str_contains($r['body'], 'id="search-help"') && str_contains($r['body'], 'in:#ops') && !str_contains($r['body'], 'id="search-results"'), 'nothing at all: the syntax help, no results');
[$c, $d] = $res($marco, 'q=zzzqqqnothing');
ok($c === 200 && $d['total'] === 0 && page($marco, '/search?q=zzzqqqnothing')['body'] !== '' && str_contains(page($marco, '/search?q=zzzqqqnothing')['body'], 'id="search-empty"'), 'no hits: said so');

echo "8. Logged\n";
$since = last_activity_id();
page($marco, '/search?q=' . urlencode('rate limit is:page'));
$l = activity('screen.view', $since);
$after = json_decode((string) ($l[0]['after'] ?? '{}'), true);
ok(count($l) === 1 && $after['q'] === 'rate limit' && $after['filters'] === ['is'], 'screen.view with the words and the modifiers used: ' . ($l[0]['after'] ?? '-'));
finish();
