<?php
/** Proof — the dispatch loop (spec "Proof", 2–4): a mention, a 202 then done, a DM, a group DM — the worker's step against the fake kernel's chat endpoint. */
require __DIR__ . '/lib.php';
$w = agents_world();
$priya = as_member(26); $marco = as_member(27);
$launch = $w['launch'];

echo "1. A mention\n";
kernel_chat(['reply' => "The launch is **Friday**. @channel heads up, thanks @SMOKE Priya — see the Pricing page.\n\nSecond paragraph."]);
$n0 = last_note_id(); $a0 = last_activity_id(); $calls0 = chat_calls();
[$c, $b] = post($priya, $launch, '@SMOKE Seamus what is the launch date?');
$m = (int) $b['record_id'];
$d = dispatch_id_of($m, 40);
$row = dispatch_db($d);
ok($d > 0 && $row['kind'] === 'mention' && (int) $row['acting_member_id'] === 26 && $row['conversation_id'] === 'spaces:thread:' . $m && $row['status'] === 'sent', 'one dispatch: mention, acting Priya, the thread as the conversation');
$r = worker_pass();
ok(($r['called'] ?? 0) === 1 && ($r['answered'] ?? 0) === 1 && ($r['failed'] ?? 9) === 0, 'the worker\'s pass called the kernel once and it answered: ' . json_encode($r));
$log = array_slice(chat_log(), $calls0);
ok(count($log) === 1 && (int) $log[0]['agent'] === 40 && (int) $log[0]['acting'] === 26, 'the call was ?agent=<Seamus> with X-Acting-Member <Priya>');
ok(str_contains((string) $log[0]['utterance'], 'what is the launch date?') && $log[0]['conversation_id'] === 'spaces:thread:' . $m && (int) $log[0]['wait'] === 25, 'the utterance, the conversation id and wait 25');
ok(str_contains((string) $log[0]['context'], 'You are SMOKE Seamus, a member of Spaces') && str_contains((string) $log[0]['context'], 'mentioned in #smoke-launch of space SMOKE Product')
    && str_contains((string) $log[0]['context'], 'SMOKE Priya: ') && str_contains((string) $log[0]['context'], 'what is the launch date?') && str_contains((string) $log[0]['context'], 'Never write @channel, @here or @everyone.'), 'the context: who it is, where, the thread\'s lines, the "never @channel" sentence');
$done = dispatch_db($d);
$reply = (int) $done['reply_message_id'];
$rm = message_db($reply);
ok($done['status'] === 'answered' && $reply > 0 && $rm['kind'] === 'message' && (int) $rm['author_member_id'] === 40 && (int) $rm['thread_root_id'] === $m && $rm['sent_at'] !== null, 'the reply landed in the thread as Seamus');
$runs = body_runs($reply);
$types = array_map(fn ($x) => ($x['type'] ?? '') . ':' . ($x['mention']['type'] ?? ''), $runs);
ok(!in_array('mention:channel', $types, true) && str_contains($rm['plain_text'], '@channel') && count(array_filter($runs, fn ($x) => ($x['type'] ?? '') === 'mention' && ($x['mention']['type'] ?? '') === 'member' && (string) ($x['mention']['id'] ?? '') === '26')) === 1,
    '@channel stripped to words, @SMOKE Priya a mention run');
ok(str_contains($rm['plain_text'], "Second paragraph") && str_contains($rm['plain_text'], 'Friday'), 'the Markdown reply became the message (both paragraphs)');
ok((int) one('SELECT agent_run_id FROM messages WHERE id = :m', ['m' => $reply]) > 0, 'agent_run_id is set on the reply');
$rep = activity_after('agent.reply', $a0);
ok(count($rep) === 1 && (int) $rep[0]['actor_member_id'] === 40 && (int) $rep[0]['message_id'] === $m && (int) $rep[0]['channel_id'] === $launch && $rep[0]['source'] === 'cron', 'agent.reply logged (actor the agent, source cron)');
$after = json_decode($rep[0]['after'], true);
ok((float) $after['cost'] === 0.0345 && $after['currency'] === 'USD' && $after['reply_length'] > 20 && (int) $after['dispatch_id'] === $d && !str_contains($rep[0]['after'], 'Friday') && !str_contains($rep[0]['after'], 'Second'), 'agent.reply carries cost, currency and length — never the words');
$call = activity_after('agent.dispatch', $a0);
ok(count($call) === 1 && !str_contains($call[0]['after'], 'launch date'), 'agent.dispatch logged without the utterance');
ok(count(notes(26, 'agent_replied', $n0)) === 1, 'Priya told (agent_replied)');
ok(count(notes(26, 'mention', $n0)) <= 1 && count(notes(30, 'mention', $n0)) === 0 && count(notes(27, 'mention', $n0)) === 0, 'the stripped @channel told no one else');
$r = worker_pass();
ok(($r['called'] ?? 9) === 0 && ($r['polled'] ?? 9) === 0 && chat_calls() === $calls0 + 1, 'a second pass dispatches nothing');
$t = page($marco, '/channels/' . $launch . '/threads/' . $m);
ok($t['code'] === 200 && str_contains($t['body'], 'id="thread-row-' . $reply . '"') && str_contains($t['body'], 'badge bg-soft-info text-info">agent') && !str_contains($t['body'], 'is thinking'), 'the thread shows the reply with the agent chip');

echo "2. 202, then done\n";
kernel_chat(['mode' => 'running', 'pending' => true]);
$calls0 = chat_calls(); $a0 = last_activity_id();
[$c, $b] = post($priya, $launch, '@SMOKE Seamus summarise the thread, please');
$m2 = (int) $b['record_id']; $d2 = dispatch_id_of($m2, 40);
$r = worker_pass();
$row = dispatch_db($d2);
ok(($r['called'] ?? 0) === 1 && ($r['running'] ?? 0) === 1 && $row['status'] === 'sent' && (int) $row['run_id'] >= 9000 && $row['pending_message_id'] !== null, '202: running with the run id, the placeholder born: ' . json_encode($r));
$ph = (int) $row['pending_message_id'];
ok(message_db($ph)['kind'] === 'agent_pending' && (int) message_db($ph)['thread_root_id'] === $m2, 'the placeholder is an agent_pending row in the thread');
$t = page($marco, '/channels/' . $launch . '/threads/' . $m2);
ok(str_contains($t['body'], 'id="message-pending-' . $ph . '"') && str_contains($t['body'], 'SMOKE Seamus</span> is thinking') && str_contains($t['body'], 'aria-live="polite"') && str_contains($t['body'], 'spinner-border'), 'the thread page: "SMOKE Seamus is thinking…" with the spinner, aria-live polite');
[$c, $js] = screen($marco, '/channels/' . $launch . '/threads/' . $m2);
ok($c === 200 && count(array_filter($js['replies'] ?? $js['messages'] ?? [], fn ($x) => ($x['kind'] ?? '') === 'agent_pending')) >= 0 && str_contains(json_encode($js), 'agent_pending'), 'the thread as JSON carries the pending row');
$ch = page($marco, '/channels/' . $launch);
ok(str_contains($ch['body'], 'id="channel-thinking"') && str_contains($ch['body'], 'SMOKE Seamus is thinking'), 'the channel view shows the thinking line');
$r = worker_pass();
ok(($r['called'] ?? 9) === 0 && ($r['polled'] ?? 0) === 1 && ($r['running'] ?? 0) === 1 && dispatch_db($d2)['status'] === 'sent' && chat_calls() === $calls0 + 2, 'the next pass GETs the run (still going) and posts no second turn');
$polls = array_values(array_filter(chat_log(), fn ($l) => $l['poll'] !== null));
ok(end($polls)['poll'] === (int) $row['run_id'] && (int) end($polls)['acting'] === 26, 'the poll asked for that run, the asker acting');
kernel_chat(['mode' => 'running', 'pending' => false, 'run_reply' => 'It ships **Friday**, said the Pricing page.']);
$known = json_encode([(string) $ph => 'pending']);
$r = worker_pass();
$row = dispatch_db($d2);
ok(($r['polled'] ?? 0) === 1 && ($r['answered'] ?? 0) === 1 && $row['status'] === 'answered' && (int) $row['reply_message_id'] === $ph, 'finished: the placeholder became the reply (same row): ' . json_encode($r));
ok(message_db($ph)['kind'] === 'message' && str_contains(message_db($ph)['plain_text'], 'Friday'), 'the message says what the agent said');
$p = req('GET', '/channels/' . $launch . '/threads/' . $m2 . '/since?after=' . $ph . '&hashes=' . urlencode($known), ['jar' => $marco]);
ok($p['code'] === 200 && str_contains($p['body'], 'hx-swap-oob="outerHTML"') && str_contains($p['body'], 'Friday'), 'the thread poll shows the change');
$rep = activity_after('agent.reply', $a0);
ok(count($rep) === 1 && (int) json_decode($rep[0]['after'], true)['run_id'] === (int) $row['run_id'] && (float) json_decode($rep[0]['after'], true)['cost'] === 0.0123, 'agent.reply carries the run and cost');

echo "3. A DM and a group DM\n";
kernel_chat(['reply' => 'Plan: ship Friday. (from {agent})']);
[$c, $b] = act($priya, '/dm/open.php', ['member' => 40]);
$dm = (int) $b['record_id'];
$calls0 = chat_calls();
[$c, $b] = post($priya, $dm, 'Seamus, remind me of the plan');
$dmsg = (int) $b['record_id']; $dd = dispatch_id_of($dmsg, 40);
ok($dd > 0 && dispatch_db($dd)['kind'] === 'dm', 'a DM to Seamus dispatches kind dm');
$r = worker_pass();
$row = dispatch_db($dd);
ok($row['status'] === 'answered' && (int) message_db((int) $row['reply_message_id'])['channel_id'] === $dm && str_contains(message_db((int) $row['reply_message_id'])['plain_text'], 'from 40'), 'answered in the DM');
$log = array_slice(chat_log(), $calls0);
ok(str_contains((string) $log[0]['context'], 'sent a direct message') && !str_contains((string) $log[0]['context'], 'mentioned in'), 'the context says it was a direct message');
ok(dispatch_db($dd)['conversation_id'] === 'spaces:dm:' . $dm, 'the DM is the conversation (spaces:dm:<channel>)');
ok(message_db((int) $row['reply_message_id'])['thread_root_id'] === null && (int) message_db($dmsg)['reply_count'] === 0, 'the reply is a top-level message of the DM, the question has no thread');
$r = page($priya, '/dm/' . $dm);
ok(str_contains($r['body'], 'id="message-row-' . (int) $row['reply_message_id'] . '"') && str_contains($r['body'], 'Plan: ship Friday.') && !str_contains($r['body'], '1 reply') && str_contains($r['body'], 'badge bg-soft-info text-info">agent'), 'the DM shows the reply inline with the agent chip and no "1 reply"');
ok(str_contains((string) $log[0]['context'], 'The conversation so far') && str_contains((string) $log[0]['context'], 'Answer in this conversation'), 'the context says "the conversation so far"');
kernel_chat(['reply' => 'Second answer. (from {agent})']);
$calls1 = chat_calls();
[$c, $b] = post($priya, $dm, 'and what about the date?');
$dmsg2 = (int) $b['record_id'];
worker_pass();
$log2 = array_slice(chat_log(), $calls1);
ok(count($log2) === 1 && $log2[0]['conversation_id'] === 'spaces:dm:' . $dm && str_contains((string) $log2[0]['context'], 'SMOKE Priya: Seamus, remind me of the plan') && str_contains((string) $log2[0]['context'], 'SMOKE Seamus: Plan: ship Friday.') && str_contains((string) $log2[0]['context'], 'and what about the date?'),
    'the next DM message has the DM\'s earlier turns as its context: one conversation, with memory');
ok(str_contains(page($priya, '/dm/' . $dm)['body'], 'Second answer.'), 'and its answer is inline too');
kernel_chat(['reply' => 'Plan: ship Friday. (from {agent})']);
[$c, $b] = act($priya, '/dm/open-group.php', ['members' => [40, 42]]);
$gdm = (int) $b['record_id'];
ok($c === 200 && $gdm > 0, 'a group DM with two agents opens');
$calls0 = chat_calls();
[$c, $b] = post($priya, $gdm, 'both of you: say hello');
$gmsg = (int) $b['record_id'];
$gd = q("SELECT id, agent_member_id FROM agent_dispatches WHERE record_id = :m ORDER BY agent_member_id", ['m' => $gmsg]);
ok(count($gd) === 2 && (int) $gd[0]['agent_member_id'] === 40 && (int) $gd[1]['agent_member_id'] === 42, 'a group DM: two dispatches');
$r = worker_pass();
ok(($r['called'] ?? 0) === 2 && ($r['answered'] ?? 0) === 2, 'one pass, two calls, two answers: ' . json_encode($r));
$texts = q("SELECT author_member_id, plain_text FROM messages WHERE channel_id = :c AND kind = 'message' AND author_member_id IN (40, 42) ORDER BY author_member_id", ['c' => $gdm]);
ok(count($texts) === 2 && str_contains($texts[0]['plain_text'], 'from 40') && str_contains($texts[1]['plain_text'], 'from 42'), 'two replies in the group DM, one each');
$log = array_slice(chat_log(), $calls0);
ok(array_column($log, 'agent') == ['40', '42'] || array_column($log, 'agent') == [40, 42], 'the kernel was asked as each agent in turn');
finish();
