<?php
/** Proof — refused and failed, approvals, and no loops (spec "Proof", 5–6). */
require __DIR__ . '/lib.php';
$w = agents_world();
$priya = as_member(26); $marco = as_member(27); $owner = as_member(1);
$launch = $w['launch'];
$mention = function (string $who, string $text) use ($priya, $launch): array { [$c, $b] = post($priya, $launch, "@SMOKE $who $text"); $m = (int) $b['record_id']; return [$m, dispatch_id_of($m, $who === 'Seamus' ? 40 : 42)]; };

echo "1. A refusal\n";
kernel_chat(['status' => 403, 'message' => 'SMOKE Seamus has no grant on Spaces.']);
[$m, $d] = $mention('Seamus', 'refuse me');
$a0 = last_activity_id();
$r = worker_pass();
$row = dispatch_db($d);
ok(($r['refused'] ?? 0) === 1 && $row['status'] === 'refused' && $row['detail'] === 'SMOKE Seamus has no grant on Spaces.' && $row['pending_message_id'] === null, '403: refused with the kernel\'s sentence, no placeholder: ' . json_encode($r));
ok(q("SELECT count(*) AS n FROM messages WHERE kind = 'agent_pending' AND thread_root_id = :m", ['m' => $m])[0]['n'] == 0, 'nothing is "thinking" in the thread');
$f = activity_after('agent.fail', $a0);
ok(count($f) === 1 && json_decode($f[0]['after'], true)['detail'] === 'SMOKE Seamus has no grant on Spaces.' && !str_contains($f[0]['after'], 'refuse me'), 'agent.fail logged with the detail, not the words');
$r = worker_pass();
ok(($r['called'] ?? 9) === 0, 'a refused dispatch is not offered again');

echo "2. A 500: backoff, five attempts, told once, Retry\n";
kernel_chat(['mode' => 'error500']);
[$m, $d] = $mention('Seamus', 'fail me');
$n0 = last_note_id(); $calls0 = chat_calls();
$r = worker_pass();
$row = dispatch_db($d);
ok(($r['failed'] ?? 0) === 1 && $row['status'] === 'sent' && (int) $row['attempts'] === 2 && strtotime($row['next_attempt_at']) > time() + 60, 'a 500: sent again with attempts 2 and next_attempt_at ahead: ' . json_encode($r));
ok(str_contains((string) $row['detail'], '500'), 'the detail says what happened');
$r = worker_pass();
ok(($r['called'] ?? 9) === 0 && chat_calls() === $calls0 + 1, 'the pass skips it until it is due');
for ($i = 3; $i <= 5; $i++) { make_due($d); worker_pass(); }
$row = dispatch_db($d);
ok($row['status'] === 'sent' && (int) $row['attempts'] === 5, 'four failures: still trying (attempts 5)');
ok(count(notes(26, 'agent_replied', $n0)) === 0, 'Priya has not been told yet');
make_due($d);
$r = worker_pass();
$row = dispatch_db($d);
ok($row['status'] === 'failed' && (int) $row['attempts'] === 6, 'the fifth failure: failed for good');
$told = notes(26, 'agent_replied', $n0);
ok(count($told) === 1 && str_contains($told[0]['title'], 'could not answer') && str_contains($told[0]['title'], 'SMOKE Seamus') && (int) $told[0]['message_id'] === $m, 'Priya is told once: "SMOKE Seamus could not answer"');
make_due($d);
$r = worker_pass();
ok(($r['called'] ?? 9) === 0 && count(notes(26, 'agent_replied', $n0)) === 1, 'a failed dispatch is not offered again and nobody is told twice');
$page = page($owner, '/admin/dispatches?status=failed');
ok(str_contains($page['body'], 'id="dispatch-row-' . $d . '-retry-btn"'), 'the admin sees Retry on it');
$a0 = last_activity_id();
[$c, $b] = act($owner, '/admin/dispatches/retry.php', ['dispatch' => $d]);
$row = dispatch_db($d);
ok($c === 200 && $row['status'] === 'sent' && (int) $row['attempts'] === 5 && strtotime($row['next_attempt_at']) <= time(), 'Retry: back to sent, due now, attempts kept (never above five)');
$lg = activity_after('agent.dispatch', $a0);
ok(count($lg) === 1 && json_decode($lg[0]['after'], true)['retry'] === true && (int) $lg[0]['actor_member_id'] === 1, 'agent.dispatch logged with after.retry = true');
kernel_chat(['reply' => 'Back now. (the retry worked)']);
$r = worker_pass();
$row = dispatch_db($d);
ok($row['status'] === 'answered' && str_contains(message_db((int) $row['reply_message_id'])['plain_text'], 'the retry worked'), 'answered on the next pass');
[$c, $b] = act($owner, '/admin/dispatches/retry.php', ['dispatch' => $d]);
ok($c === 422 && str_contains(msg($b), 'Only a failed dispatch'), 'an answered dispatch is not retried (422 in words)');
[$c, $b] = act($priya, '/admin/dispatches/retry.php', ['dispatch' => $d]);
ok($c === 403, 'a Member may not retry: ' . msg($b));

echo "3. A run that disappears: the placeholder goes\n";
kernel_chat(['mode' => 'running', 'pending' => true]);
[$m, $d] = $mention('Seamus', 'lose my run');
worker_pass();
$ph = (int) dispatch_db($d)['pending_message_id'];
ok($ph > 0 && message_db($ph)['kind'] === 'agent_pending', 'a run going: the placeholder is there');
kernel_chat(['mode' => 'running', 'pending' => true, 'run_status' => 404]);
$r = worker_pass();
$row = dispatch_db($d);
ok(($r['polled'] ?? 0) === 1 && ($r['failed'] ?? 0) === 1 && $row['status'] === 'sent' && $row['run_id'] === null && (int) $row['attempts'] === 2 && message_db($ph) === [], 'the kernel forgot the run: failed once, the placeholder removed, back in the queue');
echo "   the 10-minute limit\n";
kernel_chat(['mode' => 'running', 'pending' => true]);
make_due($d);
worker_pass();
$row = dispatch_db($d);
$ph = (int) $row['pending_message_id'];
$r = worker_pass(['SP_WORKER_NOW' => gmdate('Y-m-d H:i:s', time() + 11 * 60) . ' UTC']);
$row = dispatch_db($d);
ok(($r['failed'] ?? 0) === 1 && str_contains((string) $row['detail'], 'did not finish') && $row['status'] === 'sent' && message_db($ph) === [], 'a run still going after ten minutes: failed "the run did not finish", the placeholder removed');
ok(is_array($r) && isset($r['called']), 'SP_WORKER_NOW moves the clock of a pass (this one ran at +11 minutes)');

echo "4. An approval the kernel paused\n";
kernel_chat(['mode' => 'approval']);
[$m, $d] = $mention('Librarian', 'publish the roadmap');
$r = worker_pass();
$row = dispatch_db($d);
ok(($r['awaiting'] ?? 0) === 1 && $row['status'] === 'awaiting_approval' && str_contains((string) $row['detail'], 'request 77'), 'pending_approval: awaiting_approval with the request id in the detail: ' . json_encode($r));
$ph = (int) $row['pending_message_id'];
$t = page($marco, '/channels/' . $launch . '/threads/' . $m);
ok($ph > 0 && str_contains($t['body'], 'id="message-pending-' . $ph . '"') && str_contains($t['body'], "is waiting for a person's approval") && !str_contains($t['body'], 'is thinking'), 'the placeholder stays and says it is waiting for a person\'s approval');
$r = worker_pass();
ok(($r['called'] ?? 9) === 0, 'an awaiting dispatch is not called again');
$page = page($owner, '/admin/dispatches?status=awaiting_approval');
ok(str_contains($page['body'], 'id="dispatch-row-' . $d . '-status">awaiting approval'), 'the admin lists it under "Awaiting approval"');

echo "5. No loops\n";
kernel_chat(['reply' => 'Ask @SMOKE Librarian — they keep the wiki.']);
[$m, $d] = $mention('Seamus', 'who keeps the wiki?');
$calls0 = chat_calls();
worker_pass();
$reply = (int) dispatch_db($d)['reply_message_id'];
$runs = body_runs($reply);
ok(count(array_filter($runs, fn ($x) => ($x['type'] ?? '') === 'mention' && (string) ($x['mention']['id'] ?? '') === '42')) === 1, 'Seamus\'s reply mentions the Librarian (a real mention run)');
ok(q("SELECT count(*) AS n FROM agent_dispatches WHERE record_id = :m", ['m' => $reply])[0]['n'] == 0, 'and dispatches nothing');
$r = worker_pass();
ok(($r['called'] ?? 9) === 0 && chat_calls() === $calls0 + 1, 'the Librarian is never woken by an agent');
$t = (new DateTimeImmutable('+2 hours'))->format('Y-m-d H:i');
[$c, $b] = post($priya, $launch, '@SMOKE Seamus later please', ['schedule_for' => $t]);
$sm = (int) $b['record_id'];
ok($c === 200 && message_db($sm)['sent_at'] === null && dispatch_id_of($sm, 40) === 0, 'a scheduled message mentioning Seamus dispatches nothing yet');
pdo()->exec("UPDATE messages SET sent_at = now() WHERE id = $sm");
$sd = dispatch_id_of($sm, 40);
ok($sd > 0 && dispatch_db($sd)['status'] === 'sent', 'when it is sent (the worker\'s step), the dispatch is written');
[$m, $d] = $mention('Seamus', 'forget this one');
act($priya, '/channels/messages/delete-own.php', ['message' => $m]);
ok(message_db($m)['deleted_at'] !== null, 'a message deleted before its turn is a tombstone');
$calls0 = chat_calls();
$r = worker_pass();
$utter = array_column(array_slice(chat_log(), $calls0), 'utterance');
ok(!array_filter($utter, fn ($u) => str_contains((string) $u, 'forget this one')) && dispatch_db($d)['status'] === 'sent', 'a tombstoned message is skipped: the kernel never heard it');
finish();
