<?php
/** Proof — the Librarian's proposals (spec "Proof", 7): made through the Actions MCP path (a run token + relay), listed, accepted, dismissed, scoped to what a member may see. */
require __DIR__ . '/lib.php';
$w = agents_world();
$priya = as_member(26); $marco = as_member(27); $bea = as_member(28); $owner = as_member(1);
$launch = $w['launch']; $product = $w['product'];
kernel_state(function ($s) { $s['facts']['4201'] = ['valid' => true, 'is_agent' => true, 'member_id' => 42, 'run_id' => 4201, 'request_id' => 'req-4201', 'trigger' => 'duty', 'endpoints' => [['name' => 'Actions MCP']]]; return $s; });
$lib = as_agent(run_token(42, 4201));

echo "1. The Librarian proposes a thread as a page\n";
[$c, $b] = post($priya, $launch, 'SMOKE We decided: the launch banner stays blue. Anyone against?');
$root = (int) $b['record_id'];
reply($marco, $root, 'SMOKE Agreed, blue it is.');
[$c, $b] = act_token('/pages/save.php', ['title' => 'SMOKE Decision: the launch banner', 'space' => $product, 'markdown' => "The launch banner stays blue.\n\nDecided in #smoke-launch."], $lib);
$draft = (string) ($b['record_id'] ?? '');
ok($c === 200 && is_uuid_s($draft), 'the Librarian made a draft first (page_create): ' . msg($b));
$n0 = last_note_id(); $a0 = last_activity_id();
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'thread_to_page', 'title' => 'Make the banner decision a page', 'reason' => 'Decided in a thread with two replies; nobody will find it there.', 'message' => $root, 'proposed_page' => $draft], $lib);
$pid = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $pid > 0 && ($b['ok'] ?? false) === true && isset($b['location'], $b['did'], $b['refresh']), 'proposal_make under the run token: the contract: ' . msg($b));
$row = q('SELECT kind, status, subject_message_id, subject_channel_id, proposed_page_id::text AS draft, proposed_by FROM librarian_proposals WHERE id = :p', ['p' => $pid])[0];
ok($row['kind'] === 'thread_to_page' && $row['status'] === 'proposed' && (int) $row['subject_message_id'] === $root && (int) $row['subject_channel_id'] === $launch && $row['draft'] === $draft && (int) $row['proposed_by'] === 42, 'the row: the thread\'s first message, its channel, the draft, proposed by the Librarian');
$lg = activity_after('librarian.propose', $a0);
$after = json_decode($lg[0]['after'] ?? '{}', true);
ok(count($lg) === 1 && $lg[0]['source'] === 'agent' && (int) $lg[0]['agent_run_id'] === 4201 && $lg[0]['entity_uuid'] === $draft && (int) $after['proposal_id'] === $pid && $after['kind'] === 'thread_to_page' && !str_contains($lg[0]['after'], 'banner'), 'librarian.propose logged: source agent, the run, the draft as entity_uuid, no words');
ok(count(notes(27, 'proposal', $n0)) === 1 && count(notes(26, 'proposal', $n0)) === 0, 'the space owner (Marco) is told once, Priya is not');
[$c, $b, $raw] = act_token('/proposals/save.php', ['kind' => 'thread_to_page', 'title' => 'Again', 'reason' => 'again', 'message' => $root], $lib);
ok($c === 422 && str_contains(msg($b), 'already proposed'), 'a second proposal for the same thread: 422 "already proposed" ');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'thread_to_page', 'title' => 'Via a reply', 'reason' => 'x', 'message' => (int) one("SELECT id FROM messages WHERE thread_root_id = :r ORDER BY id LIMIT 1", ['r' => $root])], $lib);
ok($c === 422, 'a reply names its root: still "already proposed"');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'orphan', 'title' => 'x', 'reason' => 'x'], $lib);
ok($c === 422, 'no subject: refused in words — ' . msg($b));
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'nonsense', 'title' => 'x', 'reason' => 'x', 'page' => $draft], $lib);
ok($c === 422, 'an unknown kind: refused — ' . msg($b));
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'verify', 'title' => 'x', 'reason' => 'x', 'message' => $root], $lib);
ok($c === 422 && str_contains(msg($b), 'about a page'), 'a verify proposal is about a page: ' . msg($b));
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'orphan', 'title' => 'x', 'reason' => 'x', 'page' => '00000000-0000-4000-8000-000000000000'], $lib);
ok($c === 404, 'a page the Librarian cannot see: 404');
[$c, $b] = act($priya, '/dm/open.php', ['member' => 30]);
$dmc = (int) $b['record_id'];
[$c, $b] = post($priya, $dmc, 'private words');
[$c, $b] = act($priya, '/proposals/save.php', ['kind' => 'unanswered', 'title' => 'x', 'reason' => 'x', 'message' => (int) $b['record_id']]);
ok($c === 422 || $c === 404, 'a direct message is not proposed about (' . $c . ')');

echo "2. The list\n";
$r = page($marco, '/proposals/');
ok($r['code'] === 200 && str_contains($r['body'], 'id="proposal-card-' . $pid . '"') && str_contains($r['body'], 'Make the banner decision a page') && str_contains($r['body'], 'id="proposal-card-' . $pid . '-kind"') && str_contains($r['body'], 'Thread to page'), 'a card: the kind chip, the title');
ok(str_contains($r['body'], 'We decided: the launch banner stays blue') && str_contains($r['body'], 'SMOKE Decision: the launch banner') && str_contains($r['body'], 'id="proposal-card-' . $pid . '-draft"'), 'the subject (the thread\'s first line) and the draft are named and linked');
ok(str_contains($r['body'], 'id="proposal-accept-' . $pid . '-parent"') && str_contains($r['body'], 'Top of a space') && str_contains($r['body'], 'id="proposal-dismiss-' . $pid . '-reason"'), 'Accept asks where (a space root or a page); Dismiss takes a reason');
foreach (['proposal-tab-proposed', 'proposal-tab-accepted', 'proposal-tab-dismissed', 'proposal-kind-all', 'proposal-kind-thread_to_page'] as $id) { ok(str_contains($r['body'], 'id="' . $id . '"'), "the tab/filter $id is there"); }
$r = page($marco, '/proposals/?kind=verify');
ok(!str_contains($r['body'], 'id="proposal-card-' . $pid . '"') && str_contains($r['body'], 'id="proposal-list-empty"'), 'the kind filter narrows the list');

echo "3. Accept\n";
[, $b] = act($marco, '/pages/save.php', ['title' => 'SMOKE Decisions', 'space' => $product]);
$decisions = (string) $b['record_id'];
[$c, $b] = act($marco, '/proposals/accept.php', ['proposal' => $pid]);
ok($c === 422 && isset(fields($b)['parent']), 'accepting without saying where: 422 on the parent');
[$c, $b] = act($bea, '/proposals/accept.php', ['proposal' => $pid, 'parent' => $decisions]);
ok($c === 404, 'Bea (who cannot see the thread) cannot accept it: 404');
$a0 = last_activity_id();
[$c, $b] = act($marco, '/proposals/accept.php', ['proposal' => $pid, 'parent' => $decisions]);
ok($c === 200 && ($b['ok'] ?? false) === true && $b['location'] === '/pages/' . $draft, 'Marco accepts naming Product › SMOKE Decisions: ' . msg($b));
ok(one('SELECT parent_page_id::text FROM pages WHERE id = CAST(:d AS uuid)', ['d' => $draft]) === $decisions && one('SELECT status FROM librarian_proposals WHERE id = :p', ['p' => $pid]) === 'accepted' && (int) one('SELECT decided_by FROM librarian_proposals WHERE id = :p', ['p' => $pid]) === 27, 'the draft moved there (sp_page_move) and the proposal is accepted by Marco');
ok((int) one("SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid) AND type = 'child_page'", ['p' => $decisions]) === 1, 'the parent holds the draft\'s edge block');
$lg = activity_after('librarian.accept', $a0);
ok(count($lg) === 1 && $lg[0]['entity_uuid'] === $draft && (int) $lg[0]['actor_member_id'] === 27, 'librarian.accept logged with the page as entity_uuid');
[$c, $b] = act($marco, '/proposals/accept.php', ['proposal' => $pid, 'parent' => $decisions]);
ok($c === 422 && str_contains(msg($b), 'already accepted'), 'accepting twice: 422 in words');
$r = page($marco, '/proposals/?status=accepted');
ok(str_contains($r['body'], 'id="proposal-card-' . $pid . '"') && str_contains($r['body'], 'id="proposal-card-' . $pid . '-open-btn"'), 'it moved to the Accepted tab with an Open button');

echo "4. A space root, and the other kinds\n";
[$c, $b] = act_token('/pages/save.php', ['title' => 'SMOKE Decision: two', 'space' => $product, 'markdown' => 'two'], $lib);
$draft2 = (string) $b['record_id'];
[$c, $b] = post($priya, $launch, 'SMOKE We decided: tabs, not spaces.');
$root2 = (int) $b['record_id'];
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'thread_to_page', 'title' => 'Tabs decision', 'reason' => 'a decision', 'message' => $root2, 'proposed_page' => $draft2], $lib);
$p2 = (int) $b['record_id'];
[$c, $b] = act($marco, '/proposals/accept.php', ['proposal' => $p2, 'space' => $product]);
ok($c === 200 && one('SELECT parent_page_id FROM pages WHERE id = CAST(:d AS uuid)', ['d' => $draft2]) === null && (int) one('SELECT space_id FROM pages WHERE id = CAST(:d AS uuid)', ['d' => $draft2]) === $product, 'a space root as the destination: the draft is a root page of Product');
$stale = mk_in($marco, $product, 'SMOKE Stale thing');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'verify', 'title' => 'Verify the stale thing', 'reason' => 'Not verified for six months', 'page' => $stale], $lib);
$p3 = (int) $b['record_id'];
ok($c === 200, 'a verify proposal about a page');
[$c, $b] = act($marco, '/proposals/accept.php', ['proposal' => $p3]);
ok($c === 200 && $b['location'] === '/pages/' . $stale && one('SELECT status FROM librarian_proposals WHERE id = :p', ['p' => $p3]) === 'accepted', 'a verify one is accepted and links to the page (the acceptor verifies there)');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'thread_to_page', 'title' => 'No draft', 'reason' => 'x', 'message' => (int) post($priya, $launch, 'SMOKE a thread with no draft')[1]['record_id']], $lib);
$p4 = (int) $b['record_id'];
[$c, $b] = act($marco, '/proposals/accept.php', ['proposal' => $p4, 'parent' => $decisions]);
ok($c === 422 && str_contains(msg($b), 'no draft'), 'a thread_to_page one with no draft: 422 "the Librarian made no draft"');
[$c, $b] = act($marco, '/proposals/dismiss.php', ['proposal' => $p4]);

echo "5. Dismiss\n";
$other = mk_in($marco, $product, 'SMOKE Orphan candidate');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'orphan', 'title' => 'An orphan', 'reason' => 'Nothing links to it', 'page' => $other], $lib);
$p5 = (int) $b['record_id'];
$a0 = last_activity_id();
[$c, $b] = act($priya, '/proposals/dismiss.php', ['proposal' => $p5, 'reason' => 'It is a scratch page, on purpose']);
ok($c === 200 && one('SELECT status FROM librarian_proposals WHERE id = :p', ['p' => $p5]) === 'dismissed' && one('SELECT decision_note FROM librarian_proposals WHERE id = :p', ['p' => $p5]) === 'It is a scratch page, on purpose' && (int) one('SELECT decided_by FROM librarian_proposals WHERE id = :p', ['p' => $p5]) === 26, 'Priya dismisses with a reason: kept (db/021 decision_note)');
$lg = activity_after('librarian.dismiss', $a0);
ok(count($lg) === 1 && !str_contains($lg[0]['after'], 'scratch') && json_decode($lg[0]['after'], true)['has_reason'] === true, 'librarian.dismiss logged: that there was a reason, never its words');
[$c, $b] = act($priya, '/proposals/dismiss.php', ['proposal' => $p5]);
ok($c === 422, 'dismissing twice: 422');
$recent = function (int $days) { return json_decode((string) shell_exec('php -r ' . escapeshellarg('$_SESSION = ["member_id" => 26]; require "' . dirname(__DIR__, 3) . '/app/bootstrap.php"; require "' . dirname(__DIR__, 3) . '/app/features/proposals/queries.php"; echo json_encode(recently_dismissed(db(), ' . $days . '));') . ' 2>/dev/null'), true) ?: []; };
$rd = $recent(90);
ok(count($rd) >= 1 && $rd[0]['proposal_id'] == $p5 && $rd[0]['subject_page_id'] === $other && $rd[0]['decision_note'] === 'It is a scratch page, on purpose', 'recently_dismissed(90) lists it with its subject and its reason');
pdo()->exec("UPDATE librarian_proposals SET decided_at = now() - interval '91 days' WHERE id = $p5");
ok(array_filter($recent(90), fn ($x) => $x['proposal_id'] == $p5) === [], 'dismissed 91 days ago: no longer "recent"');
$r = page($priya, '/proposals/?status=dismissed');
ok(str_contains($r['body'], 'id="proposal-card-' . $p5 . '"') && str_contains($r['body'], 'Why: It is a scratch page, on purpose'), 'the Dismissed tab shows it with the reason');

echo "6. Who sees what\n";
[$c, $b] = act_token('/pages/save.php', ['title' => 'SMOKE General page', 'space' => $w['general'], 'markdown' => 'For everyone.'], $lib);
$gen = (string) $b['record_id'];
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'stale', 'title' => 'A general page is stale', 'reason' => 'Not edited for months', 'page' => $gen], $lib);
$pg = (int) $b['record_id'];
ok($c === 200 && count(notes(1, 'proposal', 0)) >= 0, 'a proposal about a page in General');
[$c, $js] = screen($bea, '/proposals/?status=proposed');
$ids = array_column($js['proposals'] ?? [], 'proposal_id');
ok($c === 200 && in_array($pg, $ids, true) && !in_array($p3, $ids, true) && !in_array($p4, $ids, true), 'Bea (General only) sees the proposal about General\'s page and none about Product\'s threads or pages');
[$c, $js] = screen($marco, '/proposals/?status=proposed');
ok(in_array($pg, array_column($js['proposals'] ?? [], 'proposal_id'), true) && $js['counts']['proposed'] >= 1, 'Marco sees both');
$guest = as_member(29);
$r = page($guest, '/proposals/');
ok($r['code'] === 403, 'a guest is refused in words: ' . substr(strip_tags($r['body']), 0, 0) . $r['code']);
[$c, $b] = act($guest, '/proposals/dismiss.php', ['proposal' => $pg]);
ok($c === 403, 'a guest may not dismiss');
finish();
function is_uuid_s(string $v): bool { return (bool) preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/', $v); }
