<?php
/** Proof — saving and the version (spec "Proof", 2): the version travels with every save; stale is 409 with the current HTML; locked, trashed, a reader, a row. */
require __DIR__ . '/lib.php';
$w = editor_world();
$rb = $w['runbook'];
$marco = as_member(27); $priya = as_member(26); $ann = as_member(29); $dana = as_member(30); $bea = as_member(28);
[, $b] = act($marco, '/pages/save.php', ['title' => 'SMOKE Save page', 'space' => $w['product']]);
$sp = (string) $b['record_id'];
[$c, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'paragraph', 'content' => para('first words')]);
$blk = (string) $b['record_id'];

echo "1. The version travels\n";
ok($c === 200 && is_uuid($blk) && ($b['version'] ?? 0) === 1 && str_contains((string) $b['html'], 'first words') && str_contains((string) $b['html'], 'contenteditable="true"') && ($b['content_rev'] ?? 0) === content_rev($sp), 'block_insert: version 1, the editor HTML, the page\'s content_rev');
$since = last_activity_id();
[$c, $b] = act($priya, '/blocks/update.php', ['block' => $blk, 'version' => 1, 'content' => para('second words')]);
ok($c === 200 && ($b['version'] ?? 0) === 2 && str_contains((string) $b['html'], 'second words'), 'block_update with version 1 → version 2 and the new HTML');
$log = activity('block.update', $since);
$after = json_decode((string) $log[0]['after'], true);
ok(count($log) === 1 && $log[0]['entity_uuid'] === $blk && (int) $log[0]['space_id'] === $w['product'] && $after['page_id'] === $sp && $after['version'] === 2 && !str_contains((string) $log[0]['after'], 'second words'), 'block.update logged: entity_uuid the block, space_id, page_id, version — never the words');
[$c, $b] = act($marco, '/blocks/update.php', ['block' => $blk, 'version' => 1, 'content' => para('Marco\'s words')]);
ok($c === 409 && ($b['error']['code'] ?? '') === 'stale' && ($b['error']['version'] ?? 0) === 2 && str_contains((string) $b['error']['html'], 'second words') && !str_contains((string) $b['error']['html'], 'Marco'), 'the same version again: 409 stale with the current HTML (nothing merged)');
ok(block_row($blk)['plain_text'] === 'second words' && block_row($blk)['version'] === 2, 'the block is as Priya left it');
[$c, $b] = act($marco, '/blocks/update.php', ['block' => $blk, 'content' => para('x')]);
ok($c === 422 && isset(fields($b)['version']), 'no version: 422 (field version)');
[$c, $b] = act($marco, '/blocks/update.php', ['block' => $blk, 'version' => 2, 'markdown' => 'from **markdown**']);
ok($c === 200 && ($b['version'] ?? 0) === 3 && json_decode(block_row($blk)['content'], true)['rich_text'][1]['annotations']['bold'] === true, 'markdown= updates the text (bold run)');
[$c, $b] = act($marco, '/blocks/update.php', ['block' => $blk, 'version' => 3, 'type' => 'heading_2']);
ok($c === 200 && block_row($blk)['type'] === 'heading_2' && str_starts_with(trim((string) $b['html']), '<h3'), 'type= turns it into a heading (the HTML follows)');
[$c, $b] = act($marco, '/blocks/update.php', ['block' => $blk, 'version' => 4, 'type' => 'nope']);
ok($c === 422 && isset(fields($b)['type']), 'an unknown type: 422');
[$c, $d] = screen($marco, '/blocks/get.php?block=' . $blk);
ok($c === 200 && ($d['version'] ?? 0) === 4 && ($d['type'] ?? '') === 'heading_2' && str_contains((string) $d['html'], 'contenteditable'), '/blocks/get.php answers the block as the editor sees it');

echo "2. Who may\n";
[$c, $b] = act($ann, '/blocks/update.php', ['block' => $blk, 'version' => 4, 'content' => para('guest')]);
ok($c === 404, 'Ann (view on Runbook, nothing on this page): 404');
act($marco, '/pages/share-guest.php', ['page' => $sp, 'guest' => 29, 'level' => 'view']);
[$c, $b] = act($ann, '/blocks/update.php', ['block' => $blk, 'version' => 4, 'content' => para('guest')]);
ok($c === 403 && str_contains(msg($b), 'edit'), 'Ann at view: 403 in words on a write');
[$c, $b] = act($ann, '/blocks/insert.php', ['page' => $sp, 'type' => 'paragraph']);
ok($c === 403, 'nor may she insert');
[$c, $b] = act($ann, '/blocks/delete.php', ['block' => $blk]);
ok($c === 403, 'nor delete');
[$c, $r] = [page($ann, '/pages/' . $sp)['code'], page($ann, '/pages/' . $sp)['body']];
ok($c === 200 && !str_contains($r, 'id="editor"') && !str_contains($r, 'contenteditable="true"'), 'she reads the page without an editor');
$r = page($marco, '/pages/' . $sp)['body'];
ok(str_contains($r, 'id="editor"') && str_contains($r, 'id="page-tree"') && str_contains($r, 'contenteditable="true"') && str_contains($r, 'editor.js') && str_contains($r, 'id="slash-menu"') && str_contains($r, 'id="stale-box-template"'), 'Marco gets the editor: the tree JSON, editable regions, the slash menu, the stale box');
[$c, $b] = act($marco, '/pages/lock.php', ['page' => $sp, 'locked' => 'yes']);
[$c, $b] = act($priya, '/blocks/update.php', ['block' => $blk, 'version' => 4, 'content' => para('locked?')]);
ok($c === 422 && msg($b) === 'Page "SMOKE Save page" is locked: unlock it to edit', 'a locked page: the sentence');
ok(!str_contains(page($marco, '/pages/' . $sp)['body'], 'contenteditable="true"'), 'and the page shows no editor while locked');
act($marco, '/pages/lock.php', ['page' => $sp, 'locked' => 'no']);
act($marco, '/pages/trash.php', ['page' => $sp]);
[$c, $b] = act($marco, '/blocks/update.php', ['block' => $blk, 'version' => 4, 'content' => para('trashed?')]);
ok($c === 422 && str_contains(msg($b), 'is in the trash'), 'a trashed page: the sentence');
act($marco, '/pages/restore.php', ['page' => $sp]);
[$c, $b] = act($dana, '/blocks/update.php', ['block' => $blk, 'version' => 4, 'content' => para('Dana was here')]);
ok($c === 200, 'Dana (a Product member, edit) may save');
[$c, $b] = act($bea, '/blocks/update.php', ['block' => $blk, 'version' => 5, 'content' => para('Bea?')]);
ok($c === 404, 'Bea (not in Product): 404');

echo "3. A row's blocks need edit_content; the appended text of a row\n";
pdo()->exec("SELECT set_config('app.member_id', '27', false)");
$db = (string) one("INSERT INTO pages (space_id, kind, title, owner_member_id) VALUES (:s, 'database', CAST(:t AS jsonb), 27) RETURNING id::text", ['s' => $w['product'], 't' => json_encode(rt('SMOKE Rows db'))]);
pdo()->prepare("INSERT INTO databases (id, properties) VALUES (CAST(:d AS uuid), '{\"title\": {\"type\": \"title\", \"name\": \"Name\"}}')")->execute(['d' => $db]);
$row = (string) one("INSERT INTO pages (space_id, kind, parent_database_id, title, owner_member_id) VALUES (:s, 'page', CAST(:d AS uuid), CAST(:t AS jsonb), 27) RETURNING id::text", ['s' => $w['product'], 'd' => $db, 't' => json_encode(rt('SMOKE Row one'))]);
act($marco, '/pages/restrict.php', ['page' => $db]);
[$c, $b] = act($marco, '/pages/share.php', ['page' => $db, 'member' => 30, 'level' => 'edit_content']);
ok($c === 200, 'the database restricted, Dana shared at edit_content' . ($c === 200 ? '' : ' — ' . msg($b)));
ok(level_of(30, $row) === 'edit_content', "Dana has edit_content on the row (through the restricted database)");
[$c, $b] = act($dana, '/blocks/insert.php', ['page' => $row, 'type' => 'paragraph', 'content' => para('row words')]);
ok($c === 200, 'edit_content lets her write the row\'s blocks');
[$c, $b] = act($dana, '/blocks/insert.php', ['page' => $db, 'type' => 'paragraph', 'content' => para('schema?')]);
ok($c === 403, 'but not the database page itself (edit needed): 403');
finish();
