<?php
/** Proof — structure (spec "Proof", 3): split, merge, nest, un-nest, the database's structural words, move, append after a block. */
require __DIR__ . '/lib.php';
$w = editor_world();
$marco = as_member(27);
[, $b] = act($marco, '/pages/save.php', ['title' => 'SMOKE Structure', 'space' => $w['product']]);
$sp = (string) $b['record_id'];
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'paragraph', 'content' => para('hello world')]);
$a = (string) $b['record_id'];

echo "1. Enter splits\n";
$left = json_encode(['rich_text' => rt('hello ')]); $right = json_encode(['rich_text' => rt('world')]);
[$c, $b] = act($marco, '/blocks/split.php', ['block' => $a, 'version' => 1, 'left' => $left, 'right' => $right, 'right_type' => 'paragraph']);
$bId = (string) ($b['right']['block_id'] ?? '');
ok($c === 200 && is_uuid($bId) && ($b['left']['version'] ?? 0) === 2 && str_contains((string) $b['right']['html'], 'world') && array_column(root_blocks($sp), 'plain_text') === ['hello ', 'world'], 'split: the left half stays (version 2), the right half is a new block after it');
[$c, $b] = act($marco, '/blocks/split.php', ['block' => $a, 'version' => 1, 'left' => $left, 'right' => $right, 'right_type' => 'paragraph']);
ok($c === 409 && ($b['error']['code'] ?? '') === 'stale', 'a split with an old version: 409 stale');
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'bulleted_list_item', 'content' => para('item'), 'after' => $bId]);
$li = (string) $b['record_id'];
[$c, $b] = act($marco, '/blocks/split.php', ['block' => $li, 'version' => 1, 'left' => para('it'), 'right' => para('em'), 'right_type' => 'bulleted_list_item']);
ok($c === 200 && block_row((string) $b['right']['block_id'])['type'] === 'bulleted_list_item', 'a list item splits into a list item');
$li2 = (string) $b['right']['block_id'];
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'heading_2', 'content' => para('Head tail'), 'after' => $li2]);
$h = (string) $b['record_id'];
[$c, $b] = act($marco, '/blocks/split.php', ['block' => $h, 'version' => 1, 'left' => para('Head'), 'right' => para(' tail'), 'right_type' => 'paragraph']);
ok($c === 200 && block_row((string) $b['right']['block_id'])['type'] === 'paragraph', 'a heading\'s tail is a paragraph');
$tail = (string) $b['right']['block_id'];

echo "2. Backspace merges and re-parents children\n";
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'paragraph', 'content' => para('child of tail'), 'parent' => $tail]);
$kid = (string) $b['record_id'];
$merged = json_encode(['rich_text' => rt('Head tail')]);
[$c, $b] = act($marco, '/blocks/merge.php', ['block' => $tail, 'version' => 1, 'into' => $h, 'into_version' => 2, 'content' => $merged]);
$ids = array_column(root_blocks($sp), 'id');
ok($c === 200 && ($b['into']['version'] ?? 0) === 3 && block_row($tail) === [] && block_row($h)['plain_text'] === 'Head tail' && block_row($kid)['parent_block_id'] === null && array_search($kid, $ids, true) === array_search($h, $ids, true) + 1, 'merge into a heading: it took the words, the tail is gone, the child landed right after the heading (a heading holds no children)');
[$c, $b] = act($marco, '/blocks/merge.php', ['block' => $kid, 'version' => 1, 'into' => $h, 'into_version' => 1, 'content' => $merged]);
ok($c === 409, 'a merge with a stale target version: 409');
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'paragraph', 'content' => para('grandchild'), 'parent' => $kid]);
$gk = (string) $b['record_id'];
[$c, $b] = act($marco, '/blocks/merge.php', ['block' => $kid, 'version' => 1, 'into' => $bId, 'into_version' => 1, 'content' => json_encode(['rich_text' => rt('worldchild of tail')])]);
ok($c === 200 && block_row($gk)['parent_block_id'] === $bId && block_row($kid) === [], 'merge into a paragraph: the child re-parents under it');
$kid = $gk;

echo "3. Tab nests, Shift-Tab un-nests; the database's words\n";
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $li2, 'parent' => $li]);
ok($c === 200 && block_row($li2)['parent_block_id'] === $li, 'Tab: the second item nests under the first');
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $li2, 'parent' => '', 'after' => $li]);
ok($c === 200 && block_row($li2)['parent_block_id'] === null && block_row($li2)['position'] > block_row($li)['position'], 'Shift-Tab: back to the root, after its old parent');
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'divider']);
$div = (string) $b['record_id'];
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $li2, 'parent' => $div]);
ok($c === 422 && msg($b) === 'A divider block holds no children', 'dropping into a divider: the database\'s sentence');
[$c, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'table_row', 'content' => json_encode(['cells' => [[], []]])]);
ok($c === 422 && msg($b) === 'A table row lives under a table', 'a table row at the root: the sentence');
[$c, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'column']);
ok($c === 422 && msg($b) === 'A column lives under a column list', 'a column at the root: the sentence');
[, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'column_list']);
$cl = (string) $b['record_id'];
[$c, $b] = act($marco, '/blocks/insert.php', ['page' => $sp, 'type' => 'paragraph', 'parent' => $cl]);
ok($c === 422 && msg($b) === 'A column list holds only columns', 'a paragraph under a column list: the sentence');
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $bId, 'parent' => $kid]);
ok($c === 422 && msg($b) === 'A block cannot be moved under its own child', 'under its own child: the sentence');
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $h, 'parent' => $w['runbook']]);
ok($c === 422 && isset(fields($b)['parent']), 'a parent on another page: 422 (field parent)');

echo "4. Drag reorders\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $div, 'parent' => '', 'after' => '']);
ok($c === 200 && root_blocks($sp)[0]['id'] === $div, 'moved first (after empty)');
$log = activity('block.move', $since);
ok(count($log) === 1 && $log[0]['entity_uuid'] === $div && json_decode((string) $log[0]['after'], true)['page_id'] === $sp, 'block.move logged');
[$c, $b] = act($marco, '/blocks/move.php', ['block' => $div, 'parent' => '', 'after' => $h]);
$ids = array_column(root_blocks($sp), 'id');
ok(array_search($div, $ids, true) === array_search($h, $ids, true) + 1, 'moved right after the heading');
$positions = array_column(root_blocks($sp), 'position');
ok($positions === array_values(array_unique($positions)) && $positions === (function ($p) { sort($p); return $p; })($positions), 'positions are unique and ascending');

echo "5. block_append after a named block; delete\n";
[$c, $b] = act($marco, '/blocks/append.php', ['page' => $sp, 'markdown' => "one\n\ntwo\n\nthree", 'after' => $div]);
$ids = array_column(root_blocks($sp), 'id');
$i = array_search($div, $ids, true);
ok($c === 200 && ($b['count'] ?? 0) === 3 && count($b['block_ids'] ?? []) === 3 && array_slice($ids, $i + 1, 3) === $b['block_ids'] && block_row($b['block_ids'][2])['plain_text'] === 'three', 'three blocks in order after the divider');
[$c, $b] = act($marco, '/blocks/append.php', ['page' => $sp, 'markdown' => "- a\n- b", 'parent' => $li]);
ok($c === 200 && count(children_of($li)) === 2, 'appended under a parent');
$since = last_activity_id();
$n = (int) one('SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid)', ['p' => $sp]);
[$c, $b] = act($marco, '/blocks/delete.php', ['block' => $li]);
ok($c === 200 && ($b['count'] ?? 0) === 3 && (int) one('SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid)', ['p' => $sp]) === $n - 3, 'block_delete removes the item and its two children (count 3)');
$log = activity('block.delete', $since);
ok(count($log) === 1 && json_decode((string) $log[0]['after'], true)['had_children'] === true, 'block.delete logged with had_children');
ok(content_rev($sp) > 1, 'the page\'s content_rev moved with the edits');
finish();
