<?php /** The page menu — a popover (never a modal). Data: p, may, pub, here */ $pid = (string) $p['page_id']; $ret = '/pages/' . $pid;
$form = static fn (string $action, array $fields, string $label, string $id, ?string $confirm = null, string $cls = 'dropdown-item'): string =>
    '<form method="post" action="' . e($action) . '" hx-post="' . e($action) . '" hx-target="#flash"' . ($confirm !== null ? ' hx-confirm="' . e($confirm) . '"' : '') . ' class="m-0">' . csrf_field() . '<input type="hidden" name="page" value="' . e($pid) . '"><input type="hidden" name="return_to" value="' . e($ret) . '">'
    . implode('', array_map(static fn ($k, $v) => '<input type="hidden" name="' . e($k) . '" value="' . e($v) . '">', array_keys($fields), $fields)) . '<button type="submit" class="' . $cls . ' btn-touch" id="' . e($id) . '">' . $label . '</button></form>'; ?>
<details class="sp-menu" id="page-menu">
    <summary class="btn btn-light btn-touch" aria-label="Page menu"><i class="feather-more-horizontal"></i></summary>
    <div class="sp-menu-popover card shadow" id="page-menu-popover"><div class="list-group list-group-flush">
        <?php if ($may['full']): ?><?= hx_link(with_back('/pages/' . $pid . '/share', $here), '<i class="feather-share-2 me-2"></i>Share', 'list-group-item list-group-item-action', 'id="page-menu-share"') ?><?php endif; ?>
        <?php if ($may['publish']): ?><?= hx_link(with_back('/pages/' . $pid . '/publish', $here), '<i class="feather-globe me-2"></i>' . ($p['is_published'] ? 'Published' : 'Publish'), 'list-group-item list-group-item-action', 'id="page-menu-publish"') ?><?php endif; ?>
        <?php if ($may['edit']): ?><?= hx_link(with_back('/pages/' . $pid . '/edit', $here), '<i class="feather-edit-2 me-2"></i>Title, icon, cover', 'list-group-item list-group-item-action', 'id="page-menu-edit"') ?><?php endif; ?>
        <?php if ($may['full'] && $p['archived_at'] === null): ?><?= $form('/pages/lock.php', ['locked' => $p['is_locked'] ? 'no' : 'yes'], '<i class="feather-' . ($p['is_locked'] ? 'unlock' : 'lock') . ' me-2"></i>' . ($p['is_locked'] ? 'Unlock' : 'Lock'), 'page-menu-lock', null, 'list-group-item list-group-item-action text-start w-100 border-0') ?><?php endif; ?>
        <?php if ($may['verify']): ?><?= $form('/pages/verify.php', [], '<i class="feather-check-circle me-2"></i>Verify', 'page-menu-verify', null, 'list-group-item list-group-item-action text-start w-100 border-0') ?><?php endif; ?>
        <?php if ($p['archived_at'] === null): ?><?= $form('/pages/favorite.php', ['favorite' => $p['is_favorite'] ? 'no' : 'yes'], '<i class="feather-star me-2"></i>' . ($p['is_favorite'] ? 'Unfavorite' : 'Favorite'), 'page-menu-favorite', null, 'list-group-item list-group-item-action text-start w-100 border-0') ?><?php endif; ?>
        <?php if ($may['full'] && $p['archived_at'] === null): ?><?= hx_link(with_back('/pages/' . $pid . '/move', $here), '<i class="feather-corner-up-right me-2"></i>Move', 'list-group-item list-group-item-action', 'id="page-menu-move"') ?><?php endif; ?>
        <?php if ($p['archived_at'] === null): ?><?= $form('/pages/duplicate.php', [], '<i class="feather-copy me-2"></i>Duplicate', 'page-menu-duplicate', null, 'list-group-item list-group-item-action text-start w-100 border-0') ?><?php endif; ?>
        <?php if ($may['export']): ?><span class="list-group-item text-muted"><i class="feather-download me-2"></i>Export <span class="fs-11">(slice 8)</span></span><?php endif; ?>
        <?= hx_link(with_back('/pages/' . $pid . '/history', $here), '<i class="feather-clock me-2"></i>History', 'list-group-item list-group-item-action', 'id="page-menu-history"') ?>
        <?php if (!empty($editor)): ?><?= hx_link('/pages/' . $pid . '?reader=1', '<i class="feather-book-open me-2"></i>Read as a reader', 'list-group-item list-group-item-action', 'id="page-menu-reader"') ?><?php endif; ?>
        <?php if ($may['template']): ?><?= $form('/pages/template-publish.php', ['template' => $p['is_template'] ? 'no' : 'yes'], '<i class="feather-layout me-2"></i>' . ($p['is_template'] ? 'Stop being a template' : 'Make a template'), 'page-menu-template', null, 'list-group-item list-group-item-action text-start w-100 border-0') ?><?php endif; ?>
        <?php if ($may['trash']): ?><?= $form('/pages/trash.php', [], '<i class="feather-trash-2 me-2"></i>Move to trash', 'page-menu-trash', 'Move ' . ($p['plain_title'] ?: 'this page') . ' and its subpages to the trash?', 'list-group-item list-group-item-action text-start w-100 border-0 text-danger') ?><?php endif; ?>
        <?php if ($may['restore']): ?><?= $form('/pages/restore.php', [], '<i class="feather-rotate-ccw me-2"></i>Restore', 'page-menu-restore', null, 'list-group-item list-group-item-action text-start w-100 border-0') ?><?php endif; ?>
        <?php if ($may['purge']): ?><?= $form('/pages/purge.php', [], '<i class="feather-x-circle me-2"></i>Delete for good', 'page-menu-purge', 'Delete ' . ($p['plain_title'] ?: 'this page') . ' for good? This cannot be undone.', 'list-group-item list-group-item-action text-start w-100 border-0 text-danger') ?><?php endif; ?>
    </div></div>
</details>
