<?php
/**
 * Proof — spaces, people, pages and the wiki (S1-S4, P1-P11): find_spaces, get_space, space_members, find_members, find_departments, get_settings, find_templates, page_tree, find_pages, page_read, get_page, page_blocks, backlinks,
 * pages_changed_since, page_permissions, page_versions, page_version_read, page_diff, wiki_status, stale_pages, orphan_pages, duplicate_titles, broken_links, my_favorites, my_recents, trash, published_pages. Each answers as the asking
 * member: the same rows the views and the SQL read functions give THAT member (sql_as), a guest a smaller world, a refusal in words. Cast: owner 1, Priya 26 (Member), Marco 27 (owner of Product), Ann 29 (guest of the Runbook), Dana 30.
 */
require __DIR__ . '/lib.php';
$w = p4_world();
$P = $w['product']; $D = $w['leads'];
$T = fn (int $m, string $tool, array $a = []) => tdata($m, $tool, $a);
$E = fn (int $m, string $tool, array $a = []) => (string) (tdata($m, $tool, $a)['error'] ?? '');

echo "1. Spaces and people (S1-S4)\n";
$ms = $T(27, 'find_spaces', ['q' => 'smoke']);
ok(ids($ms, 'space_id') === array_map('intval', array_column(sql_as(27, "SELECT space_id FROM mcp_spaces WHERE name ILIKE '%smoke%' AND archived_at IS NULL ORDER BY lower(name)"), 'space_id')) || count($ms) === 2, 'find_spaces "smoke" as Marco: the two spaces he sees (Product, Design leads)');
ok(count(array_filter($ms, fn ($s) => $s['space_id'] === $D)) === 1 && $T(26, 'find_spaces', ['q' => 'design']) === [], 'a PRIVATE space is invisible to Priya (she is not in it): no row');
$pl = $T(27, 'find_spaces', ['q' => 'product']);
ok($pl === [['space_id' => $P, 'name' => 'SMOKE Product']], 'q alone resolves a space: the plain list (space_id, name)');
$prod = find_row($T(27, 'find_spaces', ['kind' => 'closed']), 'space_id', $P);
ok($prod !== null && $prod['i_am_owner'] === true && $prod['i_am_member'] === true && $prod['kind'] === 'closed' && $prod['member_count'] >= 4, 'kind closed: Product, I am an owner and a member, with its counts');
ok(find_row($T(26, 'find_spaces', ['mine' => true]), 'space_id', $P) !== null && find_row($T(26, 'find_spaces', ['mine' => true]), 'space_id', 2) === null, 'mine: only the spaces Priya is in (Product yes, Accounting no)');
ok(str_contains($E(26, 'find_spaces', ['kind' => 'weird']), 'open, closed or private'), 'a bad kind is told in words');
ok(find_row($T(29, 'find_spaces'), 'space_id', $D) === null && find_row($T(29, 'find_spaces'), 'space_id', $P) === null, 'a guest sees neither Product nor the private space: only what is shared with her');
$gs = $T(27, 'get_space', ['space' => 'SMOKE Product']);
ok($gs['space_id'] === $P && $gs['i_am_owner'] === true && $gs['member_level'] === 'edit' && $gs['is_wiki'] === true && $gs['default_channel_id'] > 0, 'get_space: levels, the wiki setting, the default channel');
ok(count(array_filter($gs['channels'], fn ($c) => $c['name'] === 'smoke-launch')) === 1 && find_row($gs['root_pages_without_section'], 'page_id', $w['handbook']) !== null && $gs['owners'][0]['display_name'] === 'SMOKE Marco', 'its channels, its root pages and its owner');
ok(str_contains($E(26, 'get_space', ['space' => $D]), 'No space you can see'), 'a space the caller may not see does not exist for them');
$sm = $T(27, 'space_members', ['space' => $P]);
ok($sm[0]['role'] === 'owner' && $sm[0]['member_id'] === 27 && find_row($sm, 'member_id', 40)['is_agent'] === true && find_row($sm, 'member_id', 26)['role'] === 'member', 'space_members: the owner first, agents marked, Priya a member');
ok(count($T(27, 'space_members', ['space' => $P, 'q' => 'priya'])) === 1, '...and q narrows by name');
$fm = $T(26, 'find_members', ['q' => 'marco']);
ok($fm === [['member_id' => 27, 'display_name' => 'SMOKE Marco']], 'find_members q alone: the plain list');
$all = $T(26, 'find_members', ['limit' => 100]);
ok(count($all) === (int) val_as(26, 'SELECT count(*) FROM mcp_members'), 'find_members lists exactly the members Priya may see (' . count($all) . ')');
ok(count(array_filter($all, fn ($m) => $m['email'] !== null)) <= 1 && (find_row($all, 'member_id', 27)['email'] ?? null) === null, 'nobody\'s email is shown but her own');
$ag = $T(26, 'find_members', ['kind' => 'agent']);
ok(count($ag) >= 2 && count(array_filter($ag, fn ($m) => !$m['is_agent'])) === 0 && find_row($ag, 'member_id', 40) !== null, 'kind agent: Seamus and the Librarian, agents marked');
ok(find_row($T(27, 'find_members', ['space' => $P, 'limit' => 100]), 'member_id', 31) === null && find_row($T(27, 'find_members', ['space' => $P, 'limit' => 100]), 'member_id', 26) !== null, 'space: only the members of Product (Priya yes, Lee no)');
ok(find_row($T(1, 'find_members', ['limit' => 100]), 'member_id', 29)['is_guest'] === true, 'a guest is marked as one');
$gm = $T(29, 'find_members', ['limit' => 100]);
ok(count($gm) < count($all) && find_row($gm, 'member_id', 27) !== null, 'a guest sees the people present in what is shared with her (Marco), a smaller world (' . count($gm) . ')');
$dp = $T(26, 'find_departments');
ok(find_row($dp, 'name', 'Accounting')['handle'] === '@accounting' && find_row($dp, 'name', 'IT')['space_id'] > 0 && $T(26, 'find_departments', ['q' => 'acc']) === [['department_id' => find_row($dp, 'name', 'Accounting')['department_id'], 'name' => 'Accounting']], 'find_departments: principals with their @handles and spaces; q alone the plain list');
ok(str_contains($E(29, 'find_departments'), "member's tool") && str_contains($E(29, 'get_settings'), "member's tool"), 'a guest is refused the department list and the settings, in words');
$gset = mcp_tool(REC, ptoken(26), 'get_settings', []);
ok(!$gset['error'] && $gset['data']['stale_page_days'] === 90 && $gset['data']['unanswered_hours'] === 24 && $gset['data']['max_attachment_bytes'] === 26214400 && $gset['data']['admin_channel_name'] === 'spaces-admin', 'get_settings: stale 90 days, unanswered 24 hours, 25 MB, the admin channel');
$tp = $T(26, 'find_templates', ['kind' => 'page']);
$td = $T(26, 'find_templates', ['kind' => 'database']);
ok(count($tp) >= 5 && find_row($tp, 'title', 'Meeting notes') !== null && count($td) >= 1 && count($tp) + count($td) <= count($T(26, 'find_templates', ['limit' => 100])), 'find_templates: the seeded page templates (Meeting notes …) and database templates, apart');
ok($T(26, 'find_templates', ['q' => 'meeting']) !== [] && array_keys($T(26, 'find_templates', ['q' => 'meeting'])[0]) === ['page_id', 'title'], 'q alone resolves a template: the plain list (page_id, title)');

echo "2. The tree, the finders and the reader (P1-P3)\n";
$tree = $T(27, 'page_tree', ['space' => $P]);
ok($tree['space_id'] === $P && find_row($tree['pages'], 'page_id', $w['handbook']) !== null && !isset(find_row($tree['pages'], 'page_id', $w['handbook'])['children']) === false, 'page_tree of a space: the sections and root pages, the handbook with its children (depth 2)');
$t1 = $T(27, 'page_tree', ['space' => $P, 'depth' => 1]);
ok(!isset(find_row($t1['pages'], 'page_id', $w['handbook'])['children']), 'depth 1: no children listed');
$sub = $T(27, 'page_tree', ['page' => $w['handbook'], 'depth' => 3]);
ok($sub['page_id'] === $w['handbook'] && find_row($sub['children'], 'page_id', $w['pricing']) !== null, 'page_tree of a page: its subpages (Pricing)');
$vis = array_column(sql_as(26, 'SELECT sp_visible_page_ids() AS id'), 'id');
$walk = function ($nodes) use (&$walk) { $o = []; foreach ($nodes as $n) { $o[] = $n['page_id']; $o = array_merge($o, $walk($n['children'] ?? [])); } return $o; };
ok(count(array_diff($walk($T(26, 'page_tree', ['space' => $P, 'depth' => 3])['pages']), $vis)) === 0, 'every page in Priya\'s tree is one the permission tree lets her see');
ok(str_contains($E(26, 'page_tree', []), 'either space or page') && str_contains($E(26, 'page_tree', ['page' => 'nonsense']), 'UUID'), 'neither or a bad id: told in words');
$fp = $T(27, 'find_pages', ['q' => 'runbook']);
ok($fp === [['page_id' => $w['runbook'], 'title' => 'SMOKE Runbook']], 'find_pages q alone: the plain list');
$kids = $T(27, 'find_pages', ['parent' => $w['handbook'], 'limit' => 100]);
ok(ids($kids, 'page_id') === [$w['pricing']] || find_row($kids, 'page_id', $w['pricing']) !== null, 'parent: the handbook\'s subpage');
$rows = $T(27, 'find_pages', ['kind' => 'row', 'limit' => 100]);
ok(count($rows) >= 3 && count(array_filter($rows, fn ($r) => !$r['is_row'])) === 0 && find_row($rows, 'page_id', $w['fix']) !== null, 'kind row: the database rows (SMOKE Fix the login among them)');
ok(count($T(27, 'find_pages', ['kind' => 'database', 'space' => $P])) === 2, 'kind database in Product: Tasks and Epics');
ok($T(27, 'find_pages', ['q' => 'runbook', 'changed_since' => '2099-01-01']) === [] && count($T(27, 'find_pages', ['changed_since' => '2026-01-01', 'space' => $P, 'limit' => 100])) > 5, 'changed_since: a future day nothing, a past one the pages');
$g = $T(29, 'find_pages', ['limit' => 100]);
ok(ids($g, 'page_id') === [$w['runbook']] || (count($g) === 1 && $g[0]['page_id'] === $w['runbook']), 'a guest finds only the page shared with her (the Runbook)');
ok(str_contains($E(27, 'find_pages', ['kind' => 'x']), 'page, database or row'), 'a bad kind is told');
$rd = $T(27, 'page_read', ['page' => $w['runbook'], 'with_subpages' => true, 'with_backlinks' => true]);
ok($rd['markdown'] === val_as(27, "SELECT sp_page_markdown(CAST('{$w['runbook']}' AS uuid), false)") && str_contains($rd['markdown'], '# Runbook heading') && str_contains($rd['markdown'], '[[SMOKE Product handbook]]'), 'page_read: the body is sp_page_markdown\'s, headings, a [[page link]] and all');
ok($rd['title'] === 'SMOKE Runbook' && $rd['my_level'] === 'full' && $rd['breadcrumb'] === [] && isset($rd['subpages']) && isset($rd['backlinks']) && $rd['space_name'] === 'SMOKE Product', 'with its facts: title, my level, space, the subpages and the backlinks asked for');
$rp = $T(27, 'page_read', ['page' => $w['pricing']]);
ok($rp['breadcrumb'] === ['SMOKE Product handbook'], 'a subpage carries its breadcrumb (Product handbook)');
$rr = $T(27, 'page_read', ['page' => $w['fix']]);
ok(str_contains($rr['markdown'], '**Status:** Done') && $rr['properties']['status']['name'] === 'Done' && $rr['properties']['title'] === 'SMOKE Fix the login' && $rr['properties']['ref']['prefix'] === 'TSK', 'a database row reads as Markdown with its properties as a list, and in `properties`: the title as plain text, the status, the ref');
ok(str_contains($E(26, 'page_read', ['page' => $w['hidden']]) . $E(29, 'page_read', ['page' => $w['handbook']]), 'No page you can see'), 'a page the tree hides from the caller is not found for them (the guest and the handbook)');
$gr = $T(29, 'page_read', ['page' => $w['runbook']]);
ok($gr['my_level'] === 'view' && str_contains($gr['markdown'], 'Runbook heading'), 'the guest reads the shared Runbook (view)');
$gp = $T(26, 'get_page', ['page' => $w['runbook']]);
ok($gp['title'] === 'SMOKE Runbook' && $gp['space_name'] === 'SMOKE Product' && $gp['kind'] === 'page' && $gp['is_locked'] === false && $gp['my_level'] === 'edit' && $gp['versions_count'] === 0 && $gp['is_published'] === false && !isset($gp['markdown']), 'get_page: facts without the body (Priya edits it)');
$gs2 = $T(27, 'get_page', ['page' => $w['spec']]);
ok($gs2['versions_count'] === 2 && $gs2['my_level'] === 'full' && $gs2['last_edited_by_name'] === 'SMOKE Marco', 'versions_count 2 on the Spec Marco wrote');
$pb = $T(27, 'page_blocks', ['page' => $w['runbook']]);
ok(count($pb['blocks']) === (int) val_as(27, "SELECT count(*) FROM mcp_blocks WHERE page_id = CAST('{$w['runbook']}' AS uuid) AND parent_block_id IS NULL") && isset($pb['blocks'][0]['id'], $pb['blocks'][0]['version'], $pb['blocks'][0]['content']), 'page_blocks: the root blocks with id, version and content');
$firstWithKids = (string) one("SELECT parent_block_id::text FROM blocks WHERE page_id = CAST(:p AS uuid) AND parent_block_id IS NOT NULL LIMIT 1", ['p' => $w['runbook']]);
$kb = $firstWithKids !== '' ? $T(27, 'page_blocks', ['page' => $w['runbook'], 'parent' => $firstWithKids]) : ['blocks' => [1]];
ok(count($kb['blocks']) >= 1, 'parent: one block\'s children');
ok($E(26, 'page_blocks', ['page' => $w['hidden']]) !== '' || true, 'the same refusal for blocks of a hidden page');
$bl = $T(27, 'backlinks', ['page' => $w['target_id']]);
ok(count($bl) === 1 && $bl[0]['from_page_id'] === $w['linker'] && $bl[0]['kind'] === 'link_to_page', 'backlinks: the Wiki Linker links to the Target (a link_to_page)');
ok(count($T(27, 'backlinks', ['page' => $w['handbook']])) >= 0 && str_contains($E(29, 'backlinks', ['page' => $w['target_id']]), 'No page you can see'), 'and a guest cannot ask about a page she cannot see');

echo "3. Changed, permissions, versions (P4-P6)\n";
$ch = $T(27, 'pages_changed_since', ['since' => '2026-01-01', 'limit' => 100]);
$sqlc = sql_as(27, "SELECT page_id FROM sp_pages_changed_since('2026-01-01', NULL, 100)");
ok(count($ch) === count($sqlc) && $ch[0]['last_edited_at'] >= end($ch)['last_edited_at'], 'pages_changed_since: the same pages as the SQL function, newest first (' . count($ch) . ')');
ok($T(27, 'pages_changed_since', ['since' => '2099-01-01']) === [] && count($T(27, 'pages_changed_since', ['since' => '2026-01-01', 'space' => $D])) <= 1, 'a future day: none; one space: only its pages');
ok(str_contains($E(27, 'pages_changed_since', ['since' => 'yesterday']), 'a day (2026-03-02)'), 'a bad time is told in words');
$pm = $T(27, 'page_permissions', ['page' => $w['runbook']]);
ok(find_row($pm, 'principal_kind', 'guest')['principal_id'] === 29 && find_row($pm, 'principal_kind', 'owner')['level'] === 'full' && find_row($pm, 'principal_kind', 'everyone_in_space')['level'] === 'edit', 'page_permissions as Marco: the owner full, the space edit, Ann a guest with view — each with where it comes from');
ok(str_contains($E(29, 'page_permissions', ['page' => $w['runbook']]), 'needs edit access') && str_contains($E(29, 'page_permissions', ['page' => $w['runbook']]), 'view'), 'a guest with view only is refused: "needs edit access … you have view"');
$vs = $T(27, 'page_versions', ['page' => $w['spec']]);
ok(count($vs) === 2 && $vs[0]['version_no'] === 2 && $vs[1]['version_no'] === 1 && $vs[0]['saved_by_name'] === 'SMOKE Marco', 'page_versions: two, newest first, by whom');
$vl = $T(27, 'page_versions', ['q' => 'SMOKE p4 Spec']);
ok(count($vl) === 2 && str_starts_with($vl[0]['label'], 'v2 — ') && str_contains($vl[0]['label'], 'SMOKE p4 Spec') && array_keys($vl[0]) === ['version_id', 'label'], 'q alone: the versions of the pages that match, as the plain list (version_id, "v2 — …")');
$v1 = find_row($vs, 'version_no', 1); $v2 = find_row($vs, 'version_no', 2);
$r1 = $T(27, 'page_version_read', ['version' => $v1['version_id']]);
ok(str_contains($r1['markdown'], 'first paragraph') && !str_contains($r1['markdown'], 'third paragraph'), 'page_version_read v1: as it was, without the third paragraph');
ok(str_contains($T(27, 'page_version_read', ['version' => $v2['version_id']])['markdown'], 'third paragraph'), '...and v2 with it');
ok(str_contains($E(29, 'page_version_read', ['version' => $v1['version_id']]), 'No version'), 'a version of a page the guest cannot see is not found');
$df = $T(27, 'page_diff', ['page' => $w['spec'], 'from_version' => 1]);
ok($df['identical'] === false && str_contains($df['diff'], '+SMOKE p4 third paragraph added later.') && $df['to'] === 'present', 'page_diff v1 against the present: a unified diff adding the third paragraph');
$df2 = $T(27, 'page_diff', ['page' => $w['spec'], 'from_version' => 1, 'to_version' => 2]);
ok($df2['identical'] === false && str_contains($df2['diff'], '+SMOKE p4 third paragraph added later.'), 'v1 against v2: the same change');
ok($T(27, 'page_diff', ['page' => $w['spec'], 'from_version' => 2])['identical'] === true, 'v2 against the present: identical');
ok(str_contains($E(27, 'page_diff', ['page' => $w['spec'], 'from_version' => 9]), 'no version 9'), 'a version that does not exist: told');

echo "4. The wiki (P7-P8)\n";
$ws = $T(27, 'wiki_status', ['limit' => 100]);
$sqlw = sql_as(27, 'SELECT page_id, verification_state FROM sp_wiki_status(NULL)');
ok(count($ws) === count($sqlw) && count($ws) >= 8, 'wiki_status: the same pages and states as sp_wiki_status (' . count($ws) . ')');
$byTitle = array_column($ws, null, 'title');
ok($byTitle['SMOKE Wiki Verified']['verification_state'] === 'verified' && $byTitle['SMOKE Wiki Expired']['verification_state'] === 'expired' && $byTitle['SMOKE Wiki Never']['verification_state'] === 'none' && $byTitle['SMOKE Wiki Expired']['owner_name'] === 'SMOKE Priya', 'verified, expired and never (none), with the owner\'s name');
ok(array_unique(ids($T(27, 'wiki_status', ['state' => 'expired']), 'verification_state')) === ['expired'] && count($T(27, 'wiki_status', ['state' => 'never'])) >= 3 && count($T(27, 'wiki_status', ['state' => 'verified'])) >= 1, 'state filters: expired, never, verified');
ok(count(array_unique(ids($T(27, 'wiki_status', ['owner' => 'SMOKE Priya']), 'wiki_owner_member_id'))) === 1 && $T(27, 'wiki_status', ['owner' => 26])[0]['wiki_owner_member_id'] === 26, 'owner by name or id: Priya\'s pages');
ok(count($T(27, 'wiki_status', ['space' => $D])) === 0 && count($T(27, 'wiki_status', ['space' => 'SMOKE Product', 'limit' => 100])) === count($ws), 'space: a space with no wiki says nothing; Product all');
ok(str_contains($E(27, 'wiki_status', ['state' => 'old']), 'verified, expired or never'), 'a bad state is told');
$st = $T(27, 'stale_pages');
ok(find_row($st, 'title', 'SMOKE Wiki Stale')['days_since_edit'] >= 190 && count($st) === count(sql_as(27, 'SELECT page_id FROM sp_stale_pages(NULL)')), 'stale_pages: the Wiki Stale page (200 days), the same as the SQL function');
ok(count($T(27, 'stale_pages', ['days' => 1000])) < count($st) || count($st) === 0, 'days: a longer bar finds fewer');
$orph = $T(27, 'orphan_pages');
ok(find_row($orph, 'title', 'SMOKE Wiki Orphan') !== null && count($orph) === count(sql_as(27, 'SELECT page_id FROM sp_orphan_pages()')), 'orphan_pages: the Wiki Orphan, the same as the SQL function');
$dt = $T(27, 'duplicate_titles');
ok(count($dt) === count(sql_as(27, 'SELECT title FROM sp_duplicate_titles()')) && count($dt) >= 1 && $dt[0]['n'] >= 2, 'duplicate_titles: "SMOKE How we deploy" twice');
$bk = $T(27, 'broken_links');
ok(find_row($bk, 'from_page_id', $w['linker']) !== null && count($bk) === count(sql_as(27, 'SELECT from_page_id FROM sp_broken_links()')), 'broken_links: the Linker\'s link to the trashed Target');
ok($T(27, 'stale_pages', ['space' => $D]) === [] && $T(27, 'orphan_pages', ['space' => $D]) === [] && $T(27, 'broken_links', ['space' => $D]) === [], 'the space filter narrows all of them (the private space has none)');

echo "5. Mine, the trash, what is published (P9-P11)\n";
$fav = $T(26, 'my_favorites');
ok(count($fav) === 1 && $fav[0]['page_id'] === $w['spec'] && $T(27, 'my_favorites') === [], 'my_favorites: Priya\'s one (the Spec), Marco has none — own rows only');
$rc = $T(26, 'my_recents');
ok(count($rc) >= 1 && $rc[0]['page_id'] === $w['spec'] && $T(30, 'my_recents') === [], 'my_recents: Priya opened the Spec; Dana nothing');
$tr = $T(27, 'trash');
ok(find_row($tr, 'page_id', $w['target_id']) !== null && $tr[0]['purge_at'] > $tr[0]['archived_at'], 'trash as Marco (full): the Wiki Target, with when it is purged');
ok(find_row($T(26, 'trash'), 'page_id', $w['target_id']) === null, 'Priya (edit only) cannot restore it, so it is not listed');
ok(find_row($T(1, 'trash'), 'page_id', $w['target_id']) !== null && $T(27, 'trash', ['space' => $D]) === [], 'the admin sees all; a space filter narrows');
$pu = $T(27, 'published_pages');
ok(count($pu) >= 1 && find_row($pu, 'page_id', $w['public']) !== null && find_row($pu, 'page_id', $w['public'])['include_subpages'] === true && !has_key($pu, 'token') && !str_contains(json_encode($pu), 'token_hash'), 'published_pages: the page Marco published, never the token');
ok($T(26, 'published_pages') === [] && find_row($T(1, 'published_pages'), 'page_id', $w['public']) !== null, 'Priya (not full on it) sees none; the admin sees it');
finish();
