<?php
/** Proof — channels (spec "Proof", 1): create, the names, who sees what, archive and the refusals, unarchive, delete, join/follow/leave, notify, star. */
require __DIR__ . '/lib.php';
$w = channel_world();
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30); $bea = as_member(28); $ann = as_member(29); $owner = as_member(1);
$launch = $w['launch']; $leads = $w['leads_channel'];

echo "1. The world\n";
ok($launch !== null && channel_row($launch)['kind'] === 'public' && (int) channel_row($launch)['space_id'] === $w['product'], '#smoke-launch is public in Product');
ok($leads !== null && channel_row($leads)['kind'] === 'private' && in_channel($leads, 27) && in_channel($leads, 26) && !in_channel($leads, 30), '#smoke-leads-only is private: Marco and Priya');
ok(in_channel($launch, 40) && in_channel($launch, 29), 'Seamus and the guest Ann are in #smoke-launch');
ok((int) one('SELECT count(*) FROM space_members WHERE space_id = :s AND member_id = 40', ['s' => $w['product']]) === 1, 'Seamus is a member of Product');

echo "2. Create: the database's words\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/channels/save.php', ['space' => $w['product'], 'name' => 'Smoke Capitals']);
ok($c === 422 && isset(fields($b)['name']), 'a name with capitals: 422 (field name — the form lowercases, the handler refuses)');
[$c, $b] = act($marco, '/channels/save.php', ['space' => $w['product'], 'name' => 'smoke-launch']);
ok($c === 422 && msg($b) === 'That name is already taken.', 'a duplicate: the sentence');
[$c, $b] = act($dana, '/channels/save.php', ['space' => $w['leads'], 'name' => 'smoke-intruder']);
ok($c === 422 && isset(fields($b)['space']), 'Dana in a space she is not in: 422 (field space)');
[$c, $b] = act($ann, '/channels/save.php', ['space' => $w['product'], 'name' => 'smoke-guest']);
ok($c === 403, 'Ann (guest): 403');
[$c, $b] = act($priya, '/channels/save.php', ['space' => $w['product'], 'name' => 'smoke-design', 'topic' => 'Design talk', 'kind' => 'public']);
$design = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $design > 0 && ($b['did'] ?? '') === 'Made #smoke-design' && str_ends_with((string) $b['location'], '/channels/' . $design . '?notice=created') && in_channel($design, 26), 'Priya (channels.create) makes #smoke-design and is in it');
$log = activity('channel.create', $since);
ok(count($log) === 1 && (int) $log[0]['channel_id'] === $design && (int) $log[0]['space_id'] === $w['product'] && json_decode((string) $log[0]['after'], true)['name'] === 'smoke-design', 'channel.create logged with channel_id and space_id');

echo "3. Who sees what\n";
ok(page($dana, '/channels/' . $leads)['code'] === 404, 'Dana (not in the private channel): 404');
ok(page($bea, '/channels/' . $launch)['code'] === 404, 'Bea (not in Product): 404 on the public channel too');
ok(page($bea, '/channels/' . $w['general_channel'])['code'] === 200, 'Bea reads General\'s #general');
ok(page($owner, '/channels/' . $leads)['code'] === 200 && page($owner, '/channels/' . $launch)['code'] === 200, 'the admin reads both');
[$c, $d] = screen($dana, '/channels/');
$names = array_column(array_merge(...array_map(fn ($s) => $s['channels'], $d['spaces'])), 'name');
ok($c === 200 && in_array('smoke-launch', $names, true) && !in_array('smoke-leads-only', $names, true), 'channel-browse for Dana: #smoke-launch, never #smoke-leads-only');
[$c, $d] = screen($marco, '/channels/?q=leads');
ok($c === 200 && in_array('smoke-leads-only', array_column(array_merge(...array_map(fn ($s) => $s['channels'], $d['spaces'])), 'name'), true), 'the search finds the private one for Marco');
ok(page($ann, '/channels/' . $launch)['code'] === 200 && page($ann, '/channels/' . $w['product_general'])['code'] === 404, 'Ann reads #smoke-launch (added) and not #general of Product');

echo "4. Update: topic for a member, the rest the owner's\n";
[$c, $b] = act($dana, '/channels/save.php', ['channel' => $launch, 'topic' => 'Dana\'s topic']);
ok($c === 200 && channel_row($launch)['topic'] === 'Dana\'s topic', 'a follower changes the topic');
[$c, $b] = act($dana, '/channels/save.php', ['channel' => $launch, 'name' => 'smoke-launch-2']);
ok($c === 403 && msg($b) === 'You may not manage #smoke-launch.', 'but not the name: 403 in words');
[$c, $b] = act($marco, '/channels/save.php', ['channel' => $launch, 'topic' => 'The launch', 'kind' => 'private']);
ok($c === 200 && channel_row($launch)['kind'] === 'private', 'the owner turns it private');
[$c, $b] = act($marco, '/channels/save.php', ['channel' => $launch, 'kind' => 'public']);
ok($c === 200 && channel_row($launch)['kind'] === 'public', 'and back');
[$c, $b] = act($marco, '/channels/save.php', ['channel' => $w['product_general'], 'name' => 'smoke-x']);
ok($c === 422 && str_contains(msg($b), 'default channel'), 'the default channel keeps its name: the sentence');
[$c, $b] = act($marco, '/channels/retention.php', ['channel' => $launch, 'days' => 30]);
ok($c === 200 && (int) channel_row($launch)['retention_days'] === 30, 'retention_set by the owner (channel.manage): 30 days');
[$c, $b] = act($priya, '/channels/retention.php', ['channel' => $launch, 'days' => 10]);
ok($c === 403, 'Priya: 403');
act($marco, '/channels/retention.php', ['channel' => $launch, 'days' => '']);
ok(channel_row($launch)['retention_days'] === null, 'empty keeps forever');

echo "5. Archive, unarchive, delete\n";
[$c, $b] = act($priya, '/channels/archive.php', ['channel' => $design]);
ok($c === 403, 'Priya (not an owner) cannot archive');
[$c, $b] = act($marco, '/channels/archive.php', ['channel' => $design]);
ok($c === 200 && channel_row($design)['archived_at'] !== null, 'Marco (the space owner) archives #smoke-design');
ok(page($priya, '/channels/' . $design)['code'] === 200 && str_contains(page($priya, '/channels/' . $design)['body'], 'id="channel-view-archived"'), 'it reads, marked archived');
[$c, $b] = post($priya, $design, 'anyone?');
ok($c === 422 && str_contains(msg($b), 'archived'), 'a post is refused in words');
[$c, $b] = act($marco, '/channels/save.php', ['channel' => $design, 'topic' => 'x']);
ok($c === 422 && str_contains(msg($b), 'archived'), 'a change too');
[$c, $b] = act($marco, '/channels/delete.php', ['channel' => $design]);
ok($c === 403, 'Marco cannot delete (the admin\'s)');
[$c, $b] = act($owner, '/channels/delete.php', ['channel' => $launch]);
ok($c === 422 && str_contains(msg($b), 'Archive the channel first'), 'a live channel is not deleted');
[$c, $b] = act($marco, '/channels/unarchive.php', ['channel' => $design]);
ok($c === 200 && channel_row($design)['archived_at'] === null, 'unarchived');
act($marco, '/channels/archive.php', ['channel' => $design]);
[$c, $b] = act($owner, '/channels/delete.php', ['channel' => $design]);
ok($c === 200 && channel_row($design) === [], 'the admin deletes the archived one');
[$c, $b] = act($marco, '/channels/archive.php', ['channel' => $w['product_general']]);
ok($c === 422 && str_contains(msg($b), 'default channel cannot be archived'), 'the default channel: the sentence');

echo "6. Join, follow, leave, notify, star\n";
[$c, $b] = act($bea, '/channels/join.php', ['channel' => $launch]);
ok($c === 404, 'Bea (not in Product) cannot follow: 404');
[$c, $b] = act($dana, '/channels/join.php', ['channel' => $leads]);
ok($c === 404, 'nor Dana the private one: 404 (she cannot see it)');
act($marco, '/channels/members/add.php', ['channel' => $leads, 'member' => 30]);
ok(in_channel($leads, 30), 'Marco adds Dana to the private channel');
[$c, $b] = act($dana, '/channels/leave.php', ['channel' => $leads]);
ok($c === 200 && !in_channel($leads, 30), 'she leaves it');
[$c, $b] = act($bea, '/channels/leave.php', ['channel' => $w['general_channel']]);
ok($c === 422 && msg($b) === 'Nobody leaves the default space\'s #general', 'General\'s #general: the guard\'s words');
[$c, $b] = act($dana, '/channels/notify.php', ['channel' => $launch, 'notify' => 'none', 'starred' => 'yes', 'section' => 'Work']);
ok($c === 200 && q('SELECT notify, starred, section FROM channel_members WHERE channel_id = :c AND member_id = 30', ['c' => $launch])[0] == ['notify' => 'none', 'starred' => true, 'section' => 'Work'], 'notify none, starred, a section');
$side = page($dana, '/')['body'];
ok(str_contains($side, 'id="sidebar-channel-' . $launch . '"'), 'the channel shows in Dana\'s sidebar');
[$c, $b] = act($dana, '/channels/notify.php', ['channel' => $launch, 'notify' => 'loud']);
ok($c === 422 && isset(fields($b)['notify']), 'a bad notify: 422');
[$c, $b] = act($bea, '/channels/notify.php', ['channel' => $launch, 'notify' => 'none']);
ok($c === 404, 'Bea: 404');
[$c, $d] = screen($dana, '/channels/' . $launch);
ok($c === 200 && ($d['channel']['notify'] ?? '') === 'none' && ($d['channel']['starred'] ?? false) === true && is_array($d['messages']) && is_array($d['hashes']), 'channel-view as JSON carries my settings, the messages and the hashes');
finish();
