<?php
/** Proof — join, request, decide, leave; add, owners, remove (spec "Proof", 4 and 5). */
require __DIR__ . '/lib.php';
$w = spaces_world();
$priya = as_member(26); $marco = as_member(27); $bea = as_member(28); $ann = as_member(29); $owner = as_member(1); $dana = as_member(30); $lee = as_member(31);

echo "1. Join and leave\n";
[$c, $b] = act($dana, '/spaces/save.php', ['name' => 'SMOKE Open club', 'kind' => 'open']);
$club = (int) $b['record_id'];
$since = last_activity_id();
[$c, $b] = act($lee, '/spaces/join.php', ['space' => $club]);
ok($c === 200 && ($b['did'] ?? '') === 'You are in SMOKE Open club now' && q("SELECT role FROM space_members WHERE space_id = :s AND member_id = 31", ['s' => $club])[0]['role'] === 'member', 'Lee joins the open club: a member row; the handler says so');
$log = activity('space.member_add', $since);
ok(count($log) === 1 && json_decode((string) $log[0]['after'], true) == ['member_id' => 31, 'role' => 'member', 'via' => 'join'] && (int) $log[0]['space_id'] === $club, 'space.member_add logged (member_id = me, via join, space_id)');
[$c, $b] = act($lee, '/spaces/join.php', ['space' => $club]);
ok($c === 200 && ($b['did'] ?? '') === 'You are already in SMOKE Open club' && count(activity('space.member_add', $since)) === 1, 'joining again: idempotent, nothing logged');
[$c, $b] = act($lee, '/spaces/join.php', ['space' => $w['general']]);
ok($c === 200 && str_starts_with((string) $b['did'], 'You are already in'), 'General: everyone is in it already');
[$c, $b] = act($lee, '/spaces/join.php', ['space' => $w['product']]);
ok($c === 422 && msg($b) === 'Space "SMOKE Product" is closed: ask to join it.', 'joining a closed space: 422 pointing at a request');
[$c, $b] = act($ann, '/spaces/join.php', ['space' => $club]);
ok($c === 403 && msg($b) === 'You may not join spaces.', 'a guest: 403 in words');
[$c, $b] = act($lee, '/spaces/leave.php', ['space' => $club]);
ok($c === 200 && (int) one('SELECT count(*) FROM space_members WHERE space_id = :s AND member_id = 31', ['s' => $club]) === 0 && ($b['location'] ?? '') === '/spaces/?notice=left', 'Lee leaves the club: the row gone, lands on the list');
[$c, $b] = act($lee, '/spaces/leave.php', ['space' => $w['general']]);
ok($c === 422 && msg($b) === 'Nobody leaves the default space', 'leaving General: the guard\'s words');
[$c, $b] = act($bea, '/spaces/leave.php', ['space' => $w['accounting']]);
ok($c === 422 && msg($b) === 'You are in Accounting through the department; leave the department in HR.', 'Bea leaving Accounting (derived): the handler\'s words');
[$c, $b] = act($dana, '/spaces/leave.php', ['space' => $club]);
ok($c === 422 && msg($b) === 'Space "SMOKE Open club" needs an owner: name another owner first', 'Dana, the last owner, cannot leave (the guard)');
[$c, $b] = act($lee, '/spaces/leave.php', ['space' => $club]);
ok($c === 422 && msg($b) === 'You are not in SMOKE Open club.', 'leaving a space one is not in: 422');

echo "2. Request, withdraw, decide\n";
$since = last_activity_id();
[$c, $b] = act($dana, '/spaces/request.php', ['space' => $w['product'], 'message' => 'SMOKE Let me in please']);
$rid = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $rid > 0 && ($b['did'] ?? '') === 'Asked to join SMOKE Product' && q('SELECT status, message FROM space_join_requests WHERE id = :r', ['r' => $rid])[0] === ['status' => 'pending', 'message' => 'SMOKE Let me in please'], "Dana asks to join Product: request $rid pending with her message");
$log = activity('space.join_request', $since);
ok(count($log) === 1 && json_decode((string) $log[0]['after'], true)['message_length'] === 22 && !str_contains((string) $log[0]['after'], 'Let me in'), 'space.join_request logs the message\'s length, never its words');
ok((int) one("SELECT count(*) FROM notifications WHERE member_id = 27 AND kind = 'join_request' AND record_id = :s", ['s' => $w['product']]) === 1 && (int) one("SELECT count(*) FROM notifications WHERE member_id = 26 AND kind = 'join_request'") === 0, 'Marco (the owner) is told; Priya (a member) is not');
[$c, $b] = act($dana, '/spaces/request.php', ['space' => $w['product']]);
ok($c === 422 && msg($b) === 'You already asked to join SMOKE Product.', 'a second request: 422 in words');
[$c, $b] = act($priya, '/spaces/request.php', ['space' => $w['product']]);
ok($c === 422 && msg($b) === 'You are already in SMOKE Product.', 'a member asking: "already in"');
[$c, $b] = act($dana, '/spaces/request.php', ['space' => $club]);
ok($c === 422 && msg($b) === 'Space "SMOKE Open club" is open: join it.', 'asking for an open space: "join it"');
[$c, $d] = screen($dana, '/spaces/' . $w['product']);
ok($d['my_request']['status'] === 'pending' && $d['may']['request'] === false, 'her space home shows the pending request and no Request button');
[$c, $d] = screen($marco, '/spaces/' . $w['product']);
ok($d['pending_requests'] === 1, 'Marco\'s shows 1 pending');
[$c, $b] = act($dana, '/spaces/request-withdraw.php', ['space' => $w['product']]);
ok($c === 200 && q('SELECT status FROM space_join_requests WHERE id = :r', ['r' => $rid])[0]['status'] === 'withdrawn', 'withdrawn');
[$c, $b] = act($dana, '/spaces/request-withdraw.php', ['space' => $w['product']]);
ok($c === 422 && msg($b) === 'You have no pending request here.', 'withdrawing again: 422');
[$c, $b] = act($dana, '/spaces/request.php', ['space' => $w['product']]);
$rid2 = (int) $b['record_id'];
[$c, $b] = act($lee, '/spaces/request.php', ['space' => $w['product'], 'message' => 'SMOKE me too']);
$rid3 = (int) $b['record_id'];
ok($rid2 > $rid && $rid3 > $rid2, 'Dana asks again; Lee asks too');
[$c, $d] = screen($marco, '/spaces/' . $w['product'] . '/requests');
ok($c === 200 && count($d['requests']) === 3 && $d['requests'][0]['status'] === 'pending' && $d['requests'][2]['status'] === 'withdrawn', 'the requests screen: the two pending first, the withdrawn one below');
ok(page($priya, '/spaces/' . $w['product'] . '/requests')['code'] === 403, 'a member may not open it: 403');
[$c, $b] = act($priya, '/spaces/request-decide.php', ['request' => $rid2, 'decision' => 'approve']);
ok($c === 404, 'nor decide: 404 (the request does not exist to her — the view shows a request to its owner and its author)');
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/request-decide.php', ['request' => $rid2, 'decision' => 'approve']);
ok($c === 200 && ($b['did'] ?? '') === 'Approved the request' && q("SELECT role FROM space_members WHERE space_id = :s AND member_id = 30", ['s' => $w['product']])[0]['role'] === 'member' && q('SELECT status, decided_by FROM space_join_requests WHERE id = :r', ['r' => $rid2])[0] == ['status' => 'approved', 'decided_by' => 27], 'Marco approves Dana: a member now, the request approved by him');
ok((int) one("SELECT count(*) FROM notifications WHERE member_id = 30 AND kind = 'join_decided' AND title = 'You are in SMOKE Product now'") === 1, 'Dana is told "You are in SMOKE Product now"');
ok(count(activity('space.join_decide', $since)) === 1 && count(activity('space.member_add', $since)) === 1, 'space.join_decide and space.member_add logged');
[$c, $b] = act($marco, '/spaces/request-decide.php', ['request' => $rid3, 'decision' => 'decline']);
ok($c === 200 && (int) one('SELECT count(*) FROM space_members WHERE space_id = :s AND member_id = 31', ['s' => $w['product']]) === 0 && (int) one("SELECT count(*) FROM notifications WHERE member_id = 31 AND kind = 'join_decided' AND title LIKE '%declined%'") === 1, 'Lee declined: not a member, told');
[$c, $b] = act($marco, '/spaces/request-decide.php', ['request' => $rid3, 'decision' => 'approve']);
ok($c === 422 && msg($b) === 'This request was already declined.', 'deciding a decided request: 422');
[$c, $b] = act($marco, '/spaces/request-decide.php', ['request' => $rid2, 'decision' => 'maybe']);
ok($c === 422 && isset(fields($b)['decision']), 'a decision that is neither: 422 (field decision)');
[$c, $b] = act($dana, '/spaces/leave.php', ['space' => $w['product']]);
ok($c === 200, 'Dana leaves Product again');

echo "3. Members and owners\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'member' => 28]);
ok($c === 200 && ($b['rows'] ?? 0) === 1 && ($b['did'] ?? '') === 'Added 1 to SMOKE Product' && (int) one("SELECT count(*) FROM notifications WHERE member_id = 28 AND kind = 'share' AND title = 'SMOKE Marco added you to SMOKE Product'") === 1, 'add Bea: one row; she is told');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'department' => 8]);
ok($c === 200 && ($b['rows'] ?? 0) === 2 && (int) one('SELECT count(*) FROM space_members WHERE space_id = :s AND member_id IN (30, 31)', ['s' => $w['product']]) === 2, 'add Engineering: two rows (Dana and Lee)');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'department' => 8]);
ok($c === 200 && ($b['rows'] ?? -1) === 0 && str_starts_with((string) $b['did'], 'Already in'), 'adding Engineering again: 0 rows');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'member' => 40]);
ok($c === 200 && ($b['rows'] ?? 0) === 1, 'add Seamus (an agent): D10 — an agent joins a space by being added');
[$c, $d] = screen($marco, '/spaces/' . $w['product'] . '/members');
$seamus = array_values(array_filter($d['members'], fn ($m) => $m['member_id'] === 40))[0] ?? null;
ok($seamus !== null && $seamus['is_agent'] === true && $seamus['role'] === 'member' && count($d['members']) === 6, 'the members screen lists six, Seamus with the agent chip');
$h = page($marco, '/spaces/' . $w['product'] . '/members')['body'];
ok(str_contains($h, 'id="member-row-40"') && str_contains($h, '>agent<') && str_contains($h, 'id="member-add-form"') && str_contains($h, 'id="member-row-28-remove-btn"'), 'the table: Seamus\'s row with "agent", the add form, a Remove per member');
$log = activity('space.member_add', $since);
ok(count($log) === 4 && json_decode((string) $log[1]['after'], true) == ['department_id' => 8, 'role' => 'member', 'rows' => 2] && (int) $log[1]['department_id'] === 8, 'space.member_add logged each time, the department one with department_id and rows');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'member' => 29, 'role' => 'owner']);
ok($c === 422 && msg($b) === 'A guest never owns a space', 'a guest as owner: the guard');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product']]);
ok($c === 422 && isset(fields($b)['member']), 'nobody named: 422');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'member' => 41]);
ok($c === 422 && isset(fields($b)['member']), 'the Watcher (not admitted): 422 — "not here"');
[$c, $b] = act($marco, '/spaces/members/owner.php', ['space' => $w['product'], 'member' => 26, 'owner' => 'yes']);
ok($c === 200 && q("SELECT role FROM space_members WHERE space_id = :s AND member_id = 26", ['s' => $w['product']])[0]['role'] === 'owner', 'Priya made an owner');
[$c, $b] = act($marco, '/spaces/members/owner.php', ['space' => $w['product'], 'member' => 27, 'owner' => 'no']);
ok($c === 200 && q("SELECT role FROM space_members WHERE space_id = :s AND member_id = 27", ['s' => $w['product']])[0]['role'] === 'member', 'Marco steps down (Priya still owns it)');
[$c, $b] = act($marco, '/spaces/members/owner.php', ['space' => $w['product'], 'member' => 26, 'owner' => 'no']);
ok($c === 403, 'and may no longer manage it: 403');
[$c, $b] = act($priya, '/spaces/members/owner.php', ['space' => $w['product'], 'member' => 26, 'owner' => 'no']);
ok($c === 422 && msg($b) === 'Space "SMOKE Product" needs an owner: name another owner first', 'Priya, the last owner, cannot step down (the guard)');
[$c, $b] = act($priya, '/spaces/members/owner.php', ['space' => $w['product'], 'member' => 27, 'owner' => 'yes']);
ok($c === 200 && count(activity('space.owner_set', $since)) === 3, 'Marco an owner again; space.owner_set logged thrice');
[$c, $b] = act($marco, '/spaces/members/remove.php', ['space' => $w['product'], 'member' => 31]);
ok($c === 200 && (int) one('SELECT count(*) FROM space_members WHERE space_id = :s AND member_id = 31', ['s' => $w['product']]) === 0, 'Lee removed');
[$c, $b] = act($marco, '/spaces/members/remove.php', ['space' => $w['product'], 'member' => 31]);
ok($c === 422 && msg($b) === 'SMOKE Lee is not in SMOKE Product.', 'removing him again: 422');
[$c, $b] = act($owner, '/spaces/members/remove.php', ['space' => $w['accounting'], 'member' => 28]);
ok($c === 422 && msg($b) === 'SMOKE Bea is in Accounting through the department; they leave with it, in HR.', 'removing a derived member: the handler\'s words');
[$c, $b] = act($owner, '/spaces/members/remove.php', ['space' => $w['general'], 'member' => 31]);
ok($c === 422 && msg($b) === 'Nobody leaves the default space', 'removing from General: the guard');
[$c, $b] = act($priya, '/spaces/members/owner.php', ['space' => $w['product'], 'member' => 26, 'owner' => 'no']);
ok($c === 200, 'Priya steps down (Marco owns it)');
[$c, $d] = screen($priya, '/spaces/' . $w['product'] . '/members');
ok($c === 200 && $d['may']['owner'] === false, 'a member sees the members, read-only');
$h = page($priya, '/spaces/' . $w['product'] . '/members')['body'];
ok(!str_contains($h, 'id="member-add-form"') && !str_contains($h, '-remove-btn"'), 'no add form, no Remove for her');
ok(page($dana, '/spaces/' . $w['accounting'] . '/members')['code'] === 200 && str_contains(page($dana, '/spaces/' . $w['accounting'] . '/members')['body'], 'via department'), 'anyone sees a closed space\'s members; Bea marked "via department"');
ok(page($lee, '/spaces/' . $w['leads'] . '/members')['code'] === 404, 'a private space\'s members: 404 to an outsider');
finish();
