<?php
/** Proof — sections and root pages (spec "Proof", 6). */
require __DIR__ . '/lib.php';
$w = spaces_world();
$priya = as_member(26); $marco = as_member(27);
$p = $w['product'];
$pA = mkpage($p, 'SMOKE Alpha'); $pB = mkpage($p, 'SMOKE Beta'); $pC = mkpage($p, 'SMOKE Gamma');
$order = fn () => array_column(q('SELECT name FROM space_sections WHERE space_id = :s ORDER BY position, id', ['s' => $p]), 'name');

echo "1. Make and order\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'name' => 'Docs']);
$docs = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $docs > 0 && ($b['did'] ?? '') === 'Added the section Docs' && ($b['location'] ?? '') === '/spaces/' . $p . '/sections?notice=section', "Docs made ($docs), lands on the sections screen");
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'name' => 'Decisions']);
$dec = (int) $b['record_id'];
ok($c === 200 && $order() === ['Docs', 'Decisions'], 'Decisions after Docs');
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'section' => $dec, 'after' => '']);
ok($c === 200 && $order() === ['Decisions', 'Docs'], 'moved first (after empty)');
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'name' => 'Meetings', 'after' => $dec]);
$meet = (int) $b['record_id'];
ok($c === 200 && $order() === ['Decisions', 'Meetings', 'Docs'], 'Meetings made after Decisions');
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'section' => $meet, 'after' => $docs]);
ok($c === 200 && $order() === ['Decisions', 'Docs', 'Meetings'], 'Meetings moved after Docs');
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'section' => $meet, 'name' => 'Notes']);
ok($c === 200 && $order() === ['Decisions', 'Docs', 'Notes'], 'renamed in place');
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'name' => 'docs']);
ok($c === 422 && msg($b) === 'SMOKE Product already has a section named docs.', 'a duplicate name (any case): 422 in words');
[$c, $b] = act($marco, '/spaces/sections/save.php', ['space' => $p, 'name' => str_repeat('x', 61)]);
ok($c === 422 && isset(fields($b)['name']), 'a name over 60: 422');
[$c, $b] = act($priya, '/spaces/sections/save.php', ['space' => $p, 'name' => 'Mine']);
ok($c === 403, 'a member may not: 403');
ok(count(activity('section.save', $since)) === 6, 'section.save logged six times (three made, two moved, one renamed)');

echo "2. Pages into sections\n";
$pages = fn (?int $sec) => array_column(q('SELECT plain_title FROM pages WHERE space_id = :s AND section_id IS NOT DISTINCT FROM :sec AND parent_page_id IS NULL ORDER BY position, created_at', ['s' => $p, 'sec' => $sec]), 'plain_title');
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pA, 'section' => $docs]);
ok($c === 200 && $pages($docs) === ['SMOKE Alpha'] && ($b['did'] ?? '') === 'Moved the page into its section', 'Alpha into Docs');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pB, 'section' => $docs]);
ok($c === 200 && $pages($docs) === ['SMOKE Alpha', 'SMOKE Beta'], 'Beta after it (last)');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pC, 'section' => $docs, 'after' => '']);
ok($c === 200 && $pages($docs) === ['SMOKE Gamma', 'SMOKE Alpha', 'SMOKE Beta'], 'Gamma first');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pC, 'section' => $docs, 'after' => $pA]);
ok($c === 200 && $pages($docs) === ['SMOKE Alpha', 'SMOKE Gamma', 'SMOKE Beta'], 'Gamma after Alpha');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pC, 'section' => $dec]);
ok($c === 200 && $pages($dec) === ['SMOKE Gamma'] && $pages($docs) === ['SMOKE Alpha', 'SMOKE Beta'], 'Gamma to Decisions');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pC, 'section' => '']);
ok($c === 200 && $pages(null) === ['SMOKE Gamma'] && ($b['did'] ?? '') === 'Moved the page to the root', 'Gamma to none (the root)');
$log = activity('page.section_set', $since);
ok(count($log) === 6 && $log[0]['entity_uuid'] === $pA && (int) $log[0]['space_id'] === $p, 'page.section_set logged with entity_uuid and space_id');
$child = (string) one("INSERT INTO pages (space_id, parent_page_id, title, created_by, last_edited_by, owner_member_id) VALUES (:s, CAST(:p AS uuid), sp_rich_text('SMOKE Child'), 27, 27, 27) RETURNING id::text", ['s' => $p, 'p' => $pA]);
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $child, 'section' => $docs]);
ok($c === 422 && msg($b) === 'Only a root page of this space goes into a section.', 'a child page: refused in words');
$other = (int) one("INSERT INTO space_sections (space_id, name) VALUES (:g, 'SMOKE Elsewhere') RETURNING id", ['g' => $w['general']]);
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pA, 'section' => $other]);
ok($c === 422 && msg($b) === 'That section is not in this space.', 'a section of another space: refused');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => $pA, 'section' => $docs, 'after' => $pC]);
ok($c === 422 && msg($b) === 'The page to follow is not in that section.', 'after a page outside the section: refused');
[$c, $b] = act($marco, '/spaces/sections/assign.php', ['page' => 'nonsense']);
ok($c === 422 && isset(fields($b)['page']), 'no page: 422');
[$c, $d] = screen($marco, '/spaces/' . $p);
$sec = array_values(array_filter($d['sections'], fn ($x) => $x['name'] === 'Docs'))[0];
ok(array_map(fn ($x) => $x['name'], $d['sections']) === ['Decisions', 'Docs', 'Notes'] && array_map(fn ($x) => $x['title'], $sec['pages']) === ['SMOKE Alpha', 'SMOKE Beta'] && array_map(fn ($x) => $x['title'], $d['pages']) === ['SMOKE Gamma'], 'the space home: sections in order with their pages, the loose page last');
$h = page($marco, '/spaces/' . $p . '/sections')['body'];
ok(str_contains($h, 'id="section-sortable"') && str_contains($h, 'id="section-row-' . $docs . '"') && str_contains($h, 'id="section-page-' . $pA . '-select"') && str_contains($h, 'id="section-loose"'), 'the sections screen: the sortable list, a select per page, the loose list');

echo "3. Delete\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/sections/delete.php', ['section' => $docs]);
$root = $pages(null); sort($root);
ok($c === 200 && ($b['pages_moved'] ?? -1) === 2 && $root === ['SMOKE Alpha', 'SMOKE Beta', 'SMOKE Gamma'] && $order() === ['Decisions', 'Notes'] && str_contains((string) $b['did'], '2 pages moved to the root'), 'Docs deleted: its two pages at the root (they keep their order among themselves); the handler counts them');
ok(count(activity('section.delete', $since)) === 1 && json_decode((string) activity('section.delete', $since)[0]['after'], true)['pages_moved'] === 2, 'section.delete logged with pages_moved');
[$c, $b] = act($marco, '/spaces/sections/delete.php', ['section' => $docs]);
ok($c === 404, 'deleting it again: 404');
[$c, $b] = act($priya, '/spaces/sections/delete.php', ['section' => $dec]);
ok($c === 403, 'a member may not delete one: 403');
q('DELETE FROM pages WHERE id IN (CAST(:c AS uuid))', ['c' => $child]);
q('DELETE FROM pages WHERE space_id = :s', ['s' => $p]);
q('DELETE FROM space_sections WHERE id = :o', ['o' => $other]);
finish();
