<?php
/** Proof — create, update, kind, archive, restore, delete, the wiki (spec "Proof", 2 and 3). */
require __DIR__ . '/lib.php';
$w = spaces_world();
$priya = as_member(26); $marco = as_member(27); $ann = as_member(29); $owner = as_member(1); $dana = as_member(30);

echo "1. Create\n";
$since = last_activity_id();
[$c, $b] = act($dana, '/spaces/save.php', ['name' => 'SMOKE Product', 'kind' => 'closed', 'everyone_level' => 'edit', 'description' => 'SMOKE a second one']);
$p2 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $p2 > 0 && ($b['location'] ?? '') === '/spaces/' . $p2 . '?notice=created' && ($b['did'] ?? '') === 'Made SMOKE Product', "space_create: 200, record_id $p2, lands on the space (did: " . ($b['did'] ?? '') . ')');
$row = q('SELECT slug, kind, everyone_level, member_level, default_channel_id FROM spaces WHERE id = :s', ['s' => $p2])[0];
ok($row['slug'] === 'smoke-product-2' && $row['kind'] === 'closed' && $row['everyone_level'] === 'none' && $row['member_level'] === 'edit' && $row['default_channel_id'] !== null, 'a second "SMOKE Product": slug smoke-product-2; everyone_level forced to none on a closed space; member level the default (edit); a #general made');
ok(q("SELECT role FROM space_members WHERE space_id = :s AND member_id = 30", ['s' => $p2])[0]['role'] === 'owner', 'Dana owns what she made');
$log = activity('space.create', $since);
$after = json_decode((string) ($log[0]['after'] ?? '{}'), true);
ok(count($log) === 1 && (int) $log[0]['space_id'] === $p2 && $after['kind'] === 'closed' && $after['description_length'] === 18 && !str_contains((string) $log[0]['after'], 'second one'), 'space.create logged with space_id, the kind and the description\'s length — never its words');
[$c, $b] = act($ann, '/spaces/save.php', ['name' => 'SMOKE Guest space']);
ok($c === 403 && msg($b) === 'You may not join spaces.', 'a guest cannot make a space: 403 in words');
[$c, $b] = act($dana, '/spaces/save.php', ['name' => '', 'kind' => 'odd', 'member_level' => 'boss', 'verify_months' => '5']);
ok($c === 422 && isset(fields($b)['name'], fields($b)['kind'], fields($b)['member_level'], fields($b)['verify_months']), 'a bad name, kind, level and verify months: 422 with each field named');
[$c, $b] = act($dana, '/spaces/save.php', ['name' => 'SMOKE Open one', 'kind' => 'open']);
$open = (int) $b['record_id'];
ok($c === 200 && q('SELECT everyone_level FROM spaces WHERE id = :s', ['s' => $open])[0]['everyone_level'] === 'view', 'an open space gets the workspace\'s everyone level (view)');
[$c, $b] = act($dana, '/spaces/save.php', ['name' => 'SMOKE Wiki', 'kind' => 'closed', 'is_wiki' => 'yes', 'verify_months' => '3']);
$wiki = (int) $b['record_id'];
ok($c === 200 && q('SELECT is_wiki, wiki_default_verify_months FROM spaces WHERE id = :s', ['s' => $wiki])[0] == ['is_wiki' => true, 'wiki_default_verify_months' => 3], 'a wiki space with verification every 3 months');

echo "2. Update keeps what it is not sent; a member may not\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/save.php', ['space' => $w['product'], 'name' => 'SMOKE Product!', 'member_level' => 'comment']);
$row = q('SELECT name, icon, description, member_level, kind FROM spaces WHERE id = :s', ['s' => $w['product']])[0];
ok($c === 200 && $row['name'] === 'SMOKE Product!' && $row['member_level'] === 'comment' && $row['icon'] === '🚀' && str_starts_with((string) $row['description'], 'What we build') && $row['kind'] === 'closed', 'the owner renames and sets the level; the icon and description stay');
$log = activity('space.update', $since);
ok(count($log) === 1 && json_decode((string) $log[0]['after'], true) == ['name' => 'SMOKE Product!', 'member_level' => 'comment'] && json_decode((string) $log[0]['before'], true)['member_level'] === 'edit', 'space.update logs the changed fields only, before and after');
[$c, $b] = act($marco, '/spaces/save.php', ['space' => $w['product'], 'name' => 'SMOKE Product', 'member_level' => 'edit']);
ok($c === 200 && count(activity('space.update', $since)) === 2, 'and back');
[$c, $b] = act($marco, '/spaces/save.php', ['space' => $w['product'], 'member_level' => 'edit']);
ok($c === 200 && count(activity('space.update', $since)) === 2, 'saving the same again logs nothing');
[$c, $b] = act($priya, '/spaces/save.php', ['space' => $w['product'], 'name' => 'Mine now']);
ok($c === 403 && msg($b) === 'You may not manage this space.' && q('SELECT name FROM spaces WHERE id = :s', ['s' => $w['product']])[0]['name'] === 'SMOKE Product', 'a member\'s update: 403 in words, nothing changed');
[$c, $b] = act($marco, '/spaces/save.php', ['space' => $w['product'], 'kind' => 'open']);
ok($c === 422 && str_contains(msg($b), 'space_kind_set'), 'the kind through space_update: 422 pointing at space_kind_set');
[$c, $b] = act($marco, '/spaces/save.php', ['space' => 999999, 'name' => 'x']);
ok($c === 404, 'an unknown space: 404');
[$c, $b] = act($priya, '/spaces/save.php', ['space' => $w['leads'], 'name' => 'x']);
ok($c === 404, 'a private space she is not in: 404 (it does not exist to her)');

echo "3. The kind\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/kind.php', ['space' => $w['product'], 'kind' => 'open']);
ok($c === 200 && q('SELECT kind, everyone_level FROM spaces WHERE id = :s', ['s' => $w['product']])[0] === ['kind' => 'open', 'everyone_level' => 'view'], 'closed → open: everyone at the workspace\'s default (view)');
[$c, $d] = screen($dana, '/spaces/' . $w['product']);
ok($d['space']['my_level'] === 'view' && $d['may']['join'] === true, 'Dana, outside it, now reads it at view and may join');
[$c, $b] = act($marco, '/spaces/kind.php', ['space' => $w['product'], 'kind' => 'private']);
ok($c === 200 && q('SELECT kind, everyone_level FROM spaces WHERE id = :s', ['s' => $w['product']])[0] === ['kind' => 'private', 'everyone_level' => 'none'], 'open → private: everyone back to none');
ok(page($dana, '/spaces/' . $w['product'])['code'] === 404, 'and Dana no longer sees it');
[$c, $b] = act($marco, '/spaces/kind.php', ['space' => $w['product'], 'kind' => 'closed']);
ok($c === 200 && count(activity('space.kind_set', $since)) === 3, 'private → closed; space.kind_set logged thrice');
[$c, $b] = act($marco, '/spaces/kind.php', ['space' => $w['product'], 'kind' => 'closed']);
ok($c === 422 && msg($b) === 'Space "SMOKE Product" is already closed.', 'the same kind again: 422 in words');
[$c, $b] = act($owner, '/spaces/kind.php', ['space' => $w['general'], 'kind' => 'closed']);
ok($c === 422 && msg($b) === 'The default space is open to everyone in the business', 'General\'s kind: the guard\'s sentence');
[$c, $b] = act($marco, '/spaces/kind.php', ['space' => $w['product'], 'kind' => 'secret']);
ok($c === 422 && isset(fields($b)['kind']), 'a kind that is not one: 422 (field kind)');

echo "4. Archive, restore, delete\n";
$pg = mkpage($w['product'], 'SMOKE Roadmap');
$since = last_activity_id();
[$c, $b] = act($marco, '/spaces/archive.php', ['space' => $w['product']]);
ok($c === 200 && one('SELECT archived_at FROM spaces WHERE id = :s', ['s' => $w['product']]) !== null && ($b['did'] ?? '') === 'Archived SMOKE Product', 'the owner archives Product');
[$c, $d] = screen($priya, '/spaces/' . $w['product']);
ok($c === 200 && $d['space']['archived'] === true && count($d['pages']) === 1 && $d['may']['leave'] === false, 'archived: still readable (its page listed), nothing to do in it');
[$c, $b] = act($marco, '/spaces/save.php', ['space' => $w['product'], 'name' => 'Renamed']);
ok($c === 422 && str_contains(msg($b), 'archived'), 'a save in an archived space: refused in words');
[$c, $b] = act($marco, '/spaces/members/add.php', ['space' => $w['product'], 'member' => 30]);
ok($c === 422 && msg($b) === 'Space "SMOKE Product" is archived: nothing changes in it.', 'adding a member to it: "nothing changes in it"');
ok(str_contains(page($marco, '/spaces/')['body'], 'id="space-card-' . $w['product'] . '-archived"') === false && str_contains(page($marco, '/spaces/?archived=1')['body'], 'id="space-card-' . $w['product'] . '-archived"'), 'the archived card is hidden from the list until "Archived" is ticked, then marked');
[$c, $b] = act($owner, '/spaces/archive.php', ['space' => $w['general']]);
ok($c === 422 && msg($b) === 'The default space cannot be archived', 'General cannot be archived (the guard)');
[$c, $b] = act($owner, '/spaces/delete.php', ['space' => $w['product']]);
ok($c === 422 && msg($b) === 'Space "SMOKE Product" still holds 1 page; trash them first.', 'delete while a page lives: refused, naming the count');
[$c, $b] = act($marco, '/spaces/restore.php', ['space' => $w['product']]);
ok($c === 200 && one('SELECT archived_at FROM spaces WHERE id = :s', ['s' => $w['product']]) === null && count(activity('space.restore', $since)) === 1, 'restore: back, logged');
[$c, $b] = act($marco, '/spaces/delete.php', ['space' => $open]);
ok($c === 403, 'the admin alone deletes: an owner gets 403');
[$c, $b] = act($owner, '/spaces/delete.php', ['space' => $open]);
ok($c === 422 && msg($b) === 'Space "SMOKE Open one" is not archived: archive it first.', 'a live space is not deleted');
act($dana, '/spaces/archive.php', ['space' => $open]);
$since = last_activity_id();
[$c, $b] = act($owner, '/spaces/delete.php', ['space' => $open]);
ok($c === 200 && (int) one('SELECT count(*) FROM spaces WHERE id = :s', ['s' => $open]) === 0 && (int) one('SELECT count(*) FROM channels WHERE space_id = :s', ['s' => $open]) === 0 && count(activity('space.delete', $since)) === 1 && ($b['location'] ?? '') === '/spaces/?notice=deleted', 'archived and empty: deleted with its channel; logged; lands on the list');
q('DELETE FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pg]);

echo "5. The wiki\n";
$since = last_activity_id();
$pA = mkpage($w['product'], 'SMOKE Page A', null, 26);
$pB = mkpage($w['product'], 'SMOKE Page B', null, 27);
q('UPDATE pages SET wiki_owner_member_id = 1 WHERE id = CAST(:p AS uuid)', ['p' => $pB]);
[$c, $b] = act($marco, '/spaces/wiki.php', ['space' => $w['product'], 'wiki' => 'yes', 'verify_months' => '6']);
ok($c === 200 && ($b['owners_set'] ?? -1) === 1 && q('SELECT is_wiki, wiki_default_verify_months FROM spaces WHERE id = :s', ['s' => $w['product']])[0] == ['is_wiki' => true, 'wiki_default_verify_months' => 6], 'space_wiki_set on: one page given an owner (the other kept its own), every 6 months');
ok((int) one('SELECT wiki_owner_member_id FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pA]) === 26 && (int) one('SELECT wiki_owner_member_id FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pB]) === 1, 'Page A\'s creator Priya became its wiki owner; Page B kept the owner it had');
[$c, $d] = screen($marco, '/spaces/' . $w['product']);
ok($d['wiki'] == ['verified' => 0, 'expired' => 0, 'never' => 2], 'the home shows the wiki\'s counts (2 never verified)');
[$c, $b] = act($marco, '/spaces/wiki.php', ['space' => $w['product'], 'wiki' => 'yes', 'verify_months' => '5']);
ok($c === 422 && isset(fields($b)['verify_months']), 'verify every 5 months: 422');
[$c, $b] = act($marco, '/spaces/wiki.php', ['space' => $w['product'], 'wiki' => 'no']);
ok($c === 200 && q('SELECT is_wiki FROM spaces WHERE id = :s', ['s' => $w['product']])[0]['is_wiki'] === false && (int) one('SELECT wiki_owner_member_id FROM pages WHERE id = CAST(:p AS uuid)', ['p' => $pA]) === 26 && count(activity('space.wiki_set', $since)) === 2, 'off: the owners stay; space.wiki_set logged twice');
[$c, $b] = act($priya, '/spaces/wiki.php', ['space' => $w['product'], 'wiki' => 'yes']);
ok($c === 403, 'a member may not: 403');
q('DELETE FROM pages WHERE id IN (CAST(:a AS uuid), CAST(:b AS uuid))', ['a' => $pA, 'b' => $pB]);
finish();
