<?php
/** Proof — read (spec "Proof", 2): the reader renders every block type; data-block-id; the breadcrumb; recents; 404 to an outsider. */
require __DIR__ . '/lib.php';
$w = pages_world();
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30);
[$c, $b] = act($marco, '/pages/save.php', ['title' => 'SMOKE Every block', 'space' => $w['product']]);
$eb = (string) $b['record_id'];
$h1 = mkblock($eb, 'heading_1', ['rich_text' => rt('Heading one')]);
$h2 = mkblock($eb, 'heading_2', ['rich_text' => rt('Heading two'), 'is_toggleable' => true]);
mkblock($eb, 'paragraph', ['rich_text' => rt('Inside the toggle heading')], $h2);
$para = mkblock($eb, 'paragraph', ['rich_text' => [['type' => 'text', 'text' => ['content' => 'Bold ', 'link' => null], 'annotations' => ['bold' => true]], ['type' => 'text', 'text' => ['content' => 'linked', 'link' => ['url' => 'https://example.invalid/x']], 'annotations' => []], ['type' => 'text', 'text' => ['content' => ' red', 'link' => null], 'annotations' => ['color' => 'red']], ['type' => 'mention', 'mention' => ['type' => 'member', 'id' => '26', 'name' => 'SMOKE Priya'], 'plain_text' => '@SMOKE Priya']]]);
$b1 = mkblock($eb, 'bulleted_list_item', ['rich_text' => rt('Bullet one')]);
mkblock($eb, 'bulleted_list_item', ['rich_text' => rt('Nested bullet')], $b1);
mkblock($eb, 'bulleted_list_item', ['rich_text' => rt('Bullet two')]);
mkblock($eb, 'numbered_list_item', ['rich_text' => rt('First')]);
mkblock($eb, 'numbered_list_item', ['rich_text' => rt('Second')]);
mkblock($eb, 'to_do', ['rich_text' => rt('Done thing'), 'checked' => true]);
mkblock($eb, 'to_do', ['rich_text' => rt('Open thing'), 'checked' => false]);
$tg = mkblock($eb, 'toggle', ['rich_text' => rt('A toggle')]);
mkblock($eb, 'paragraph', ['rich_text' => rt('Hidden until opened')], $tg);
mkblock($eb, 'quote', ['rich_text' => rt('A quote')]);
mkblock($eb, 'callout', ['rich_text' => rt('Mind this'), 'icon' => ['emoji' => '💡'], 'color' => 'yellow_background']);
mkblock($eb, 'code', ['rich_text' => rt('print(1 < 2)'), 'language' => 'python']);
mkblock($eb, 'divider', []);
$img = mkblock($eb, 'image', ['caption' => rt('A pixel')]);
$att = mkimage($img);
q('UPDATE blocks SET content = content || jsonb_build_object(\'attachment_id\', CAST(:a AS integer)) WHERE id = CAST(:b AS uuid)', ['a' => $att, 'b' => $img]);
mkblock($eb, 'bookmark', ['url' => 'https://example.invalid/bookmark', 'caption' => rt('Example')]);
mkblock($eb, 'embed', ['url' => 'https://www.youtube.com/embed/xyz']);
mkblock($eb, 'embed', ['url' => 'https://evil.invalid/embed']);
mkblock($eb, 'equation', ['expression' => 'E = mc^2']);
mkblock($eb, 'table_of_contents', []);
$cl = mkblock($eb, 'column_list', []);
$c1 = mkblock($eb, 'column', [], $cl); mkblock($eb, 'paragraph', ['rich_text' => rt('Left column')], $c1);
$c2 = mkblock($eb, 'column', [], $cl); mkblock($eb, 'paragraph', ['rich_text' => rt('Right column')], $c2);
$tb = mkblock($eb, 'table', ['has_column_header' => true, 'table_width' => 2]);
mkblock($eb, 'table_row', ['cells' => [rt('Col A'), rt('Col B')]], $tb);
mkblock($eb, 'table_row', ['cells' => [rt('a1'), rt('b1')]], $tb);
// a synced block: the original on the handbook, a copy here
$orig = mkblock($w['handbook'], 'synced_block', []);
mkblock($w['handbook'], 'paragraph', ['rich_text' => rt('Synced words from the handbook')], $orig);
$copy = (string) one("INSERT INTO blocks (page_id, type, position, content, synced_from) VALUES (CAST(:p AS uuid), 'synced_block', 'zz', '{}', CAST(:o AS uuid)) RETURNING id::text", ['p' => $eb, 'o' => $orig]);
mkblock($eb, 'link_to_page', ['page_id' => $w['pricing']]);
mkblock($eb, 'unsupported', ['original_type' => 'whiteboard']);
[$c, $b] = act($marco, '/pages/save.php', ['title' => 'SMOKE Child of every block', 'parent' => $eb]);
$child = (string) $b['record_id'];

echo "1. The reader renders every block type\n";
$r = page($marco, '/pages/' . $eb . '?reader=1');   // since slice 3 an editor gets the editor; ?reader=1 asks for the reader
$h = $r['body'];
ok($r['code'] === 200 && str_contains($h, 'id="page-body"') && str_contains($h, 'id="page-title">SMOKE Every block<'), 'the page renders with its title');
ok(preg_match('/<h2[^>]*id="h-' . $h1 . '"[^>]*>Heading one<\/h2>/', $h) === 1 && str_contains($h, '<details') && str_contains($h, 'Heading two'), 'headings (a toggleable one as details)');
ok(str_contains($h, '<strong>Bold </strong>') && str_contains($h, 'href="https://example.invalid/x"') && str_contains($h, 'rt-color-red') && str_contains($h, 'rt-mention-member') && str_contains($h, '@SMOKE Priya'), 'rich text: bold, a link, a colour, a mention chip');
ok(preg_match('/<ul class="rt-list rt-bulleted_list_item">.*Bullet one.*<ul class="rt-list rt-bulleted_list_item">.*Nested bullet.*Bullet two/s', $h) === 1, 'bullets nested');
ok(preg_match('/<ol class="rt-list rt-numbered_list_item">.*First.*Second.*<\/ol>/s', $h) === 1, 'numbered items in one list');
ok(str_contains($h, 'rt-done') && str_contains($h, 'disabled checked') && str_contains($h, 'Open thing'), 'to-dos as disabled checkboxes, the done one marked');
ok(str_contains($h, '<summary>A toggle</summary>') && str_contains($h, 'Hidden until opened'), 'a toggle as details');
ok(str_contains($h, '<blockquote') && str_contains($h, 'rt-callout-box') && str_contains($h, 'rt-color-yellow_background') && str_contains($h, '💡'), 'a quote; a callout with its icon and colour');
ok(str_contains($h, 'class="language-python"') && str_contains($h, 'print(1 &lt; 2)'), 'code with its language class, escaped');
ok(str_contains($h, '<hr class="rt-block rt-divider"'), 'a divider');
ok(str_contains($h, 'src="/files/' . $att . '"') && str_contains($h, 'alt="A pixel"'), 'an image through /files/{id} with its caption as alt');
ok(str_contains($h, 'rt-bookmark-card') && str_contains($h, 'example.invalid') && str_contains($h, 'youtube.com/embed/xyz') && preg_match('/<iframe[^>]*youtube/', $h) === 1 && preg_match('/<iframe[^>]*evil\.invalid/', $h) === 0, 'a bookmark; an embed iframe only for an allowed host');
ok(str_contains($h, 'rt-equation') && str_contains($h, 'E = mc^2'), 'an equation as text');
ok(preg_match('/<ul class="rt-toc">.*Heading one.*Heading two/s', $h) === 1, 'a table of contents from the headings');
ok(str_contains($h, 'rt-columns') && str_contains($h, 'Left column') && str_contains($h, 'Right column'), 'columns');
ok(preg_match('/<table class="table table-bordered rt-table-grid"><tr[^>]*><th>Col A<\/th><th>Col B<\/th><\/tr><tr[^>]*><td>a1<\/td>/', $h) === 1, 'a table with a header row');
ok(str_contains($h, 'data-synced-from="' . $orig . '"') && str_contains($h, 'Synced words from the handbook'), 'a synced copy shows the original\'s children');
ok(str_contains($h, 'rt-page-link') && str_contains($h, 'href="/pages/' . $w['pricing'] . '"') && str_contains($h, 'SMOKE Pricing'), 'link_to_page as a link by title');
ok(str_contains($h, 'rt-child-link') && str_contains($h, 'href="/pages/' . $child . '"') && str_contains($h, 'SMOKE Child of every block'), 'a child page as a link');
ok(str_contains($h, 'An unsupported block (whiteboard)'), 'an unsupported block muted');
ok(preg_match_all('/data-block-id="[0-9a-f-]{36}"/', $h) >= 30, 'data-block-id on every block');
ok(preg_match('/id="page-breadcrumb".*SMOKE Product/s', $h) === 1, 'the breadcrumb names the space');
$r = page($marco, '/pages/' . $child);
ok(preg_match('/id="page-breadcrumb".*SMOKE Product.*SMOKE Every block/s', $r['body']) === 1, 'the child\'s breadcrumb walks the ancestors');
ok((int) one('SELECT count(*) FROM page_recents WHERE member_id = 27 AND page_id = CAST(:p AS uuid)', ['p' => $eb]) === 1, 'the visit landed in recents');
ok(count(activity('page.view', 0)) >= 2, 'page.view logged');
[$c, $d] = screen($marco, '/pages/' . $eb);
ok($c === 200 && count($d['blocks']) >= 25 && str_contains($d['markdown'], '# Heading one') && str_contains($d['markdown'], '- [x] Done thing'), 'the JSON carries the tree and the Markdown');
ok(page($dana, '/pages/' . $eb)['code'] === 404 && str_contains(page($dana, '/pages/' . $eb)['body'], 'Page not found.'), 'Dana\'s page-view of a Product page: 404 "Page not found."');
// the synced original on a page the reader may not see
act($marco, '/pages/save.php', ['title' => 'SMOKE Hidden original', 'private' => 'yes']);
$hid = page_by_title('SMOKE Hidden original');
$orig2 = mkblock($hid, 'synced_block', []);
mkblock($hid, 'paragraph', ['rich_text' => rt('Secret')], $orig2);
$copy2 = (string) one("INSERT INTO blocks (page_id, type, position, content, synced_from) VALUES (CAST(:p AS uuid), 'synced_block', 'zzz', '{}', CAST(:o AS uuid)) RETURNING id::text", ['p' => $eb, 'o' => $orig2]);
$h = page($priya, '/pages/' . $eb)['body'];
ok(!str_contains($h, 'Secret') && str_contains($h, 'A synced block you cannot see.'), 'a synced copy of an original Priya cannot see says so, never the words');
ok(str_contains(page($marco, '/pages/' . $eb)['body'], 'Secret'), 'Marco, who owns the original, sees it');
ok(page($marco, '/files/' . $att)['code'] === 200 && page($dana, '/files/' . $att)['code'] === 404, 'the image door: 200 to Marco, 404 to Dana');
finish();
