<?php
/** Proof — share, restrict, guests (spec "Proof", 5): the tree's levels change as the database says; the share screen explains each row. */
require __DIR__ . '/lib.php';
$w = pages_world();
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30); $ann = as_member(29); $bea = as_member(28);
$pr = $w['pricing']; $hb = $w['handbook']; $p27 = $w['pricing2027'];
$rows = fn (string $p) => q('SELECT principal_kind, principal_id, level FROM page_permissions WHERE page_id = CAST(:p AS uuid) ORDER BY principal_kind, principal_id', ['p' => $p]);

echo "1. Share with a department\n";
ok(level_of(30, $pr) === 'none' && page($dana, '/pages/' . $pr)['code'] === 404, 'before: Dana (Engineering, not in Product) has nothing on Pricing');
$since = last_activity_id();
[$c, $b] = act($marco, '/pages/share.php', ['page' => $pr, 'department' => 8, 'level' => 'comment']);
ok($c === 200 && ($b['did'] ?? '') === 'Shared SMOKE Pricing at comment', 'Marco shares Pricing with Engineering at comment');
ok(level_of(30, $pr) === 'comment' && level_of(30, $p27) === 'comment' && level_of(30, $hb) === 'none', 'Dana sees Pricing and Pricing 2027 at comment, not the handbook');
ok(in_array(['principal_kind' => 'everyone_in_space', 'principal_id' => null, 'level' => 'edit'], $rows($pr), false), 'the everyone_in_space row appeared with the space\'s default (edit)');
ok(level_of(26, $pr) === 'edit' && level_of(27, $pr) === 'full', 'Priya keeps edit; Marco full');
$log = activity('page.share', $since);
ok(count($log) === 1 && json_decode((string) $log[0]['after'], true) == ['principal_kind' => 'department', 'principal_id' => 8, 'level' => 'comment'] && (int) $log[0]['department_id'] === 8, 'page.share logged with the principal and level, department_id stamped');
ok((int) one("SELECT count(*) FROM notifications WHERE member_id IN (30, 31) AND kind = 'share'") === 2, 'Dana and Lee (Engineering) are told (the trigger)');
ok(page($dana, '/pages/' . $pr)['code'] === 200, 'Dana opens Pricing');
[$c, $d] = screen($dana, '/pages/');
ok(in_array('SMOKE Pricing', array_column($d['pages'], 'title'), true), 'it lists in her pages');

echo "2. Share with a guest\n";
[$c, $b] = act($marco, '/pages/share.php', ['page' => $pr, 'member' => 29, 'level' => 'view']);
ok($c === 422 && str_contains(msg($b), 'is a guest: share to a guest with its own action'), 'a guest through Share: 422 pointing at share_guest');
[$c, $b] = act($marco, '/pages/share-guest.php', ['page' => $pr, 'guest' => 26, 'level' => 'view']);
ok($c === 422 && msg($b) === 'SMOKE Priya is a member: use Share.', 'a member through share_guest: 422 in words');
[$c, $b] = act($marco, '/pages/share-guest.php', ['page' => $pr, 'guest' => 29, 'level' => 'full']);
ok($c === 422 && isset(fields($b)['level']), 'a guest at full: 422');
$since = last_activity_id();
[$c, $b] = act($marco, '/pages/share-guest.php', ['page' => $pr, 'guest' => 29, 'level' => 'view']);
ok($c === 200 && level_of(29, $pr) === 'view' && level_of(29, $p27) === 'view', 'Ann (guest) at view on Pricing and its subpage');
ok(count(activity('page.share_guest', $since)) === 1, 'page.share_guest logged');
$h = page($ann, '/')['body'];
ok(str_contains($h, 'id="sidebar-page-' . $pr . '"') && preg_match('/id="sidebar-shared".*sidebar-page-' . $pr . '/s', $h) === 1, 'her sidebar shows it under Shared with me');
pdo()->exec("SELECT set_config('app.member_id', '29', false)");
$names = array_column(q('SELECT display_name FROM mcp_members ORDER BY display_name'), 'display_name');
ok(in_array('SMOKE Marco', $names, true) && in_array('SMOKE Ann', $names, true) && !in_array('SMOKE Bea', $names, true), 'her mcp_members names Marco (the sharer) and herself, not Bea');
ok(page($ann, '/pages/' . $pr)['code'] === 200 && page($ann, '/pages/' . $hb)['code'] === 404, 'she opens Pricing, not the handbook');
[$c, $b] = act($marco, '/pages/unshare.php', ['page' => $pr, 'guest' => 29]);
ok($c === 200 && level_of(29, $pr) === 'none' && page($ann, '/pages/' . $pr)['code'] === 404, 'unshare Ann: gone');

echo "3. Restrict\n";
$since = last_activity_id();
[$c, $b] = act($marco, '/pages/share.php', ['page' => $p27, 'member' => 30, 'level' => 'comment']);
ok($c === 200 && level_of(30, $p27) === 'comment', 'Dana named on Pricing 2027 at comment');
[$c, $b] = act($marco, '/pages/restrict.php', ['page' => $p27]);
ok($c === 200 && level_of(26, $p27) === 'none' && level_of(27, $p27) === 'full' && level_of(30, $p27) === 'comment', 'restrict Pricing 2027: Priya loses it, Marco keeps full, Dana keeps comment');
ok(page($priya, '/pages/' . $p27)['code'] === 404, 'Priya: 404 on it now');
[$c, $d] = screen($marco, '/pages/' . $p27 . '/share');
ok($d['restricted'] === true && !in_array('everyone_in_space', array_column($d['permissions'], 'principal_kind'), true), 'the share screen says restricted; no everyone row');
[$c, $b] = act($marco, '/pages/unrestrict.php', ['page' => $p27]);
ok($c === 200 && level_of(26, $p27) === 'edit' && count(activity('page.restrict', $since)) === 1 && count(activity('page.unrestrict', $since)) === 1, 'unrestrict: Priya back at edit; both logged');
[$c, $d] = screen($marco, '/pages/' . $p27 . '/share');
$sources = array_unique(array_column($d['permissions'], 'source'));
ok(in_array('inherited', $sources, true) || in_array('this page', $sources, true), 'the share screen explains each row\'s source (' . implode(', ', $sources) . ')');
$h = page($marco, '/pages/' . $p27 . '/share')['body'];
ok(str_contains($h, 'id="permission-table"') && str_contains($h, 'id="share-form"') && str_contains($h, 'id="page-share-restrict-btn"'), 'the screen: the table, the share form, Restrict');
ok(page($priya, '/pages/' . $pr . '/share')['code'] === 403, 'Priya (edit) may not open Share: 403');

echo "4. Unshare and a private page\n";
[$c, $b] = act($marco, '/pages/unshare.php', ['page' => $pr, 'department' => 8]);
ok($c === 200 && level_of(30, $pr) === 'none' && $rows($pr) === [], 'unshare Engineering: the last explicit row gone, the everyone rows went with it (back to the space\'s default)');
ok(level_of(26, $pr) === 'edit', 'Priya still at edit through the space');
[$c, $b] = act($marco, '/pages/unshare.php', ['page' => $pr, 'department' => 8]);
ok($c === 422 && msg($b) === 'This page is not shared with them.', 'unsharing again: 422');
$notes = $w['notes'];
ok(page($priya, '/pages/' . $notes)['code'] === 404, "Bea's private notes: 404 to Priya");
[$c, $b] = act($bea, '/pages/share.php', ['page' => $notes, 'member' => 26, 'level' => 'edit']);
ok($c === 200 && level_of(26, $notes) === 'edit' && page($priya, '/pages/' . $notes)['code'] === 200, 'Bea shares her private page with Priya at edit');
$h = page($priya, '/')['body'];
ok(preg_match('/id="sidebar-shared".*sidebar-page-' . $notes . '/s', $h) === 1, 'it shows under Priya\'s Shared with me');
[$c, $b] = act($bea, '/pages/share.php', ['page' => $notes, 'member' => 28, 'level' => 'view']);
ok($c === 422 && msg($b) === 'The owner already has full access.', 'a level on the owner herself: refused');
[$c, $b] = act($bea, '/pages/share.php', ['page' => $notes, 'member' => 40, 'level' => 'view']);
ok($c === 200 && q("SELECT principal_kind FROM page_permissions WHERE page_id = CAST(:p AS uuid) AND principal_id = 40", ['p' => $notes])[0]['principal_kind'] === 'agent' && level_of(40, $notes) === 'view', 'shared with Seamus: the row\'s kind is agent');
[$c, $b] = act($bea, '/pages/share.php', ['page' => $notes, 'member' => 26, 'level' => 'maybe']);
ok($c === 422 && isset(fields($b)['level']), 'a level that is not one: 422');
finish();
