<?php
/** Proof — the wiki and templates (spec "Proof", 7). */
require __DIR__ . '/lib.php';
$w = pages_world();
$marco = as_member(27); $priya = as_member(26); $dana = as_member(30); $owner = as_member(1); $bea = as_member(28);

echo "1. Verify\n";
act($owner, '/spaces/wiki.php', ['space' => $w['product'], 'wiki' => 'yes', 'verify_months' => '6']);
$pr = $w['pricing']; $p27 = $w['pricing2027'];
ok((int) page_row($p27)['wiki_owner_member_id'] === 26 && (int) page_row($pr)['wiki_owner_member_id'] === 27, 'Product a wiki: Priya owns Pricing 2027 (she made it), Marco Pricing');
$since = last_activity_id();
[$c, $b] = act($priya, '/pages/verify.php', ['page' => $p27, 'months' => '3']);
$row = page_row($p27);
ok($c === 200 && $row['verification_state'] === 'verified' && $row['verify_until'] !== null && (new DateTimeImmutable($row['verify_until']))->getTimestamp() > time() + 80 * 86400, 'Priya verifies her page for 3 months: verified, verify_until ~3 months out');
ok(count(activity('page.verify', $since)) === 1 && json_decode((string) activity('page.verify', $since)[0]['after'], true)['months'] === 3, 'page.verify logged with the months');
$h = page($priya, '/pages/' . $p27)['body'];
ok(str_contains($h, 'id="page-badge-verified"'), 'the badge shows');
[$c, $b] = act($priya, '/pages/verify.php', ['page' => $pr]);
ok($c === 403 && str_contains(msg($b), 'wiki owner or the space'), 'Priya verifying Marco\'s page: 403 in words');
[$c, $b] = act($marco, '/pages/verify.php', ['page' => $p27]);
ok($c === 200, 'Marco (the space owner) verifies anyone\'s');
[$c, $b] = act($dana, '/pages/verify.php', ['page' => $p27]);
ok($c === 403, 'Dana (shared at comment, no owner of anything): 403');
[$c, $b] = act($priya, '/pages/verify.php', ['page' => $p27, 'months' => '5']);
ok($c === 422 && isset(fields($b)['months']), '5 months: 422');
[$c, $b] = act($marco, '/pages/verify.php', ['page' => $w['notes']]);
ok($c === 404, 'a private page (not a wiki\'s): 404 to him');
$since = last_activity_id();
[$c, $b] = act($marco, '/pages/owner.php', ['page' => $p27, 'member' => 30]);
ok($c === 200 && (int) page_row($p27)['wiki_owner_member_id'] === 30, 'owner set to Dana (any admitted member may own a wiki page)');
[$c, $b] = act($marco, '/pages/owner.php', ['page' => $p27, 'member' => 26]);
ok($c === 200 && (int) page_row($p27)['wiki_owner_member_id'] === 26, 'owner set (to Priya again)');
[$c, $b] = act($marco, '/pages/owner.php', ['page' => $pr, 'member' => 26]);
ok($c === 200 && (int) one("SELECT count(*) FROM notifications WHERE member_id = 26 AND kind = 'share' AND title = 'You now own SMOKE Pricing'") === 1, 'Priya now owns Pricing and is told');
[$c, $b] = act($priya, '/pages/owner.php', ['page' => $pr, 'member' => 27]);
ok($c === 403, 'the owner of the page (edit, not full) may not hand it over: 403');
pdo()->exec("UPDATE pages SET verify_until = now() - interval '1 day' WHERE id = '" . $pr . "'");
pdo()->exec("UPDATE pages SET verification_state = 'verified', verified_at = now() - interval '200 days', verify_until = now() - interval '1 day' WHERE id = '" . $pr . "'");
[$c, $d] = screen($priya, '/pages/' . $pr);
ok($c === 200 && $d['page']['verification']['state'] === 'expired' && str_contains(page($priya, '/pages/' . $pr)['body'], 'id="page-badge-expired"'), 'expired is a badge: the page still opens');
[$c, $d] = screen($marco, '/spaces/' . $w['product'] . '/wiki');
ok($c === 200 && $d['pages'][0]['title'] === 'SMOKE Pricing' && $d['pages'][0]['state'] === 'expired', 'wiki-view orders the expired first');
$h = page($marco, '/spaces/' . $w['product'] . '/wiki')['body'];
ok(str_contains($h, 'id="wiki-table"') && str_contains($h, 'id="wiki-row-' . $pr . '-verify-btn"'), 'the screen with Verify on the rows');
ok(page($dana, '/spaces/' . $w['product'] . '/wiki')['code'] === 200, 'anyone who sees the space sees its wiki status');
ok(page($marco, '/spaces/' . $w['leads'] . '/wiki')['code'] === 404, 'a space that is not a wiki: 404');

echo "2. Templates\n";
act($marco, '/pages/save.php', ['title' => 'SMOKE Checklist', 'space' => $w['product']]);
$ck = page_by_title('SMOKE Checklist');
mkblock($ck, 'to_do', ['rich_text' => rt('Step one'), 'checked' => false]);
[$c, $b] = act($priya, '/pages/template-publish.php', ['page' => $ck, 'template' => 'yes']);
ok($c === 403, 'a member may not publish a template: 403');
$since = last_activity_id();
[$c, $b] = act($marco, '/pages/template-publish.php', ['page' => $ck, 'template' => 'yes']);
ok($c === 200 && page_row($ck)['is_template'] === true && count(activity('page.template_publish', $since)) === 1, 'Marco makes Checklist a template');
$h = page($marco, '/')['body'];
ok(!str_contains($h, 'id="sidebar-page-' . $ck . '"'), 'gone from the sidebar');
[$c, $d] = screen($marco, '/pages/?q=Checklist');
ok($d['pages'] === [], 'and from the page list');
[$c, $d] = screen($marco, '/templates/');
ok(in_array('SMOKE Checklist', array_column($d['templates'], 'title'), true) && in_array('Meeting notes', array_column($d['templates'], 'title'), true), 'present in the gallery with the seeded ones');
$h = page($marco, '/templates/')['body'];
ok(str_contains($h, 'id="template-card-' . $ck . '-use-btn"') && str_contains($h, 'id="template-card-' . $ck . '-stop-btn"'), 'the gallery: Use, and Stop for its space owner');
[$c, $b] = act($bea, '/pages/template-apply.php', ['template' => $ck, 'space' => $w['general'], 'title' => 'SMOKE My checklist']);
ok($c === 404, 'Bea (not in Product) cannot see Product\'s template: 404');
[$c, $b] = act($marco, '/pages/template-apply.php', ['template' => $ck, 'space' => $w['general'], 'title' => 'SMOKE My checklist']);
$applied = (string) ($b['record_id'] ?? '');
ok($c === 200 && is_uuid($applied) && (int) page_row($applied)['space_id'] === $w['general'] && page_row($applied)['is_template'] === false && (int) one("SELECT count(*) FROM blocks WHERE page_id = CAST(:p AS uuid) AND type = 'to_do'", ['p' => $applied]) === 1, 'Marco applies it in General: a page with the to-do, not a template');
[$c, $b] = act($priya, '/pages/template-apply.php', ['template' => $ck, 'space' => $w['it']]);
ok($c === 403, 'Priya applying it into IT (she is not in it): 403');
[$c, $b] = act($marco, '/pages/template-publish.php', ['page' => $ck, 'template' => 'no']);
ok($c === 200 && page_row($ck)['is_template'] === false, 'and back to a page');
[$c, $b] = act($marco, '/pages/template-publish.php', ['page' => $ck, 'template' => 'no']);
ok($c === 422, 'again: 422');
finish();
